### ISSUE TITLE
Batch img2img is using the same wildcard line of text. Possible to randomize it? (automatic1111)

### ISSUE THREAD

**Issue by adieyal** [adieyal/sd-dynamic-prompts#107]
### Discussed in https://github.com/adieyal/sd-dynamic-prompts/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **sevenstyles** December 11, 2022</sup>
Hi, 

Thank you for such a useful script! I'm using batch img2img in automatic1111 with a wildcard but noticed it's using the same line of text from the wildcard for each image it creates.

Is it possible to have it select a random line of text from the wildcard file for each image processed through batch img2img?</div>

**Comment by sevenstyles** [comment]
Yes that worked! absolutely brilliant, thanks so much!
