### ISSUE TITLE
sd-dynamic-prompts [object Object]

### ISSUE THREAD

**Issue by Stanley050677** [adieyal/sd-dynamic-prompts#109]
**Describe the bug**

Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to 'EXTENSIONS' next go to Dynamic Prompts script
2. Click on 'instal'
3. See error - [object Object]

**Expected behaviour**
should instal the extension Dynamic Prompts
script

<img width="1440" alt="Zrzut ekranu 2022-12-11 o 13 17 44" src="https://user-images.githubusercontent.com/73586409/206903242-050fd02a-326d-478b-b90e-b0b8d9f43bc2.png">

**Comment by Stanley050677** [comment]
Hello, any idea how to fix that? Regards

**Comment by adieyal** [comment]
According to the error message, it looks like you might have disabled extensions in the configuration file. Do you recall doing something like that?

**Comment by Stanley050677** [comment]
Hi, no I do not recall it.

**Comment by adieyal** [comment]
From what I can see, --enable-insecure-extension-access is what is causing this. See this https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ccf1a15412ef6b518f9f54cc26a0ee5edf458108#diff-15faa364afc7fd40ccc1e6a38893b2dac62c846715710dfbe44f25fb65205440 - by default it should be true, but in your case it is false. 

You can look for this in COMMANDLINE_ARGS, where that is set depends on your operating system, some possibilities are webui-user.sh, webui-macos-env.sh, webui-user.bat, webui.bat, webui.sh. It could also be set in an environment variable.

Test other extensions as well - I suspect that this happens with any extension, not only Dynamic Prompts, in which case you should report the issue with auto1111

**Comment by adieyal** [comment]
Is this still an issue?

**Comment by Stanley050677** [comment]
Hi, I can’t find where to change the settings from false to true.

W dniu czw., 22.12.2022 o 03:41 Adi Eyal ***@***.***>
napisał(a):

**Comment by adieyal** [comment]
Look for a line in the files suggested above with the following: COMMANDLINE_ARGS

**Comment by Stanley050677** [comment]
Found it but it shows TRUE

[image: Zrzut ekranu 2022-12-22 o 23.33.08.png]

**Comment by akx** [comment]
You can't install any extensions if you're using the `--listen` or `--share` flags, because that would make it possible for anyone with access to the webui to run arbitrary code on your machine.

To install or update extensions, don't use those flags, or enable the unsafe extension access flag, which **is unsafe and you shouldn't do that.**

**Comment by Stanley050677** [comment]
How do I avoid using the listen or share flags? They were not used by me.
