### ISSUE TITLE
Attention Grabber is giving attention to every 'a' randomly

### ISSUE THREAD

**Issue by Jonseed** [adieyal/sd-dynamic-prompts#113]
**Describe the bug**
Sometimes the prompt will be littered with (a:1.1) or (a:1.9), where every single letter _**a**_ has been given attention in the prompt.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Turn on attention grabber
2. Generate

Also mention which checkboxes have been set.
Attention Grabber

**Expected behaviour**
Every 'a' should not be given attention

**Additional context**
This is random and doesn't happen with every prompt.

**Comment by adieyal** [comment]
I'm closing this issue - please re-open if it is still an issue.
