### ISSUE TITLE
no dynamic prompt menu in webui anymore

### ISSUE THREAD

**Issue by nagaisa** [adieyal/sd-dynamic-prompts#119]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to 'webui'
2. Click on 'txt2img'
3. Scroll down to 'nothingnis'

Also mention which checkboxes have been set.

**Expected behaviour**
there should be a menu for dynamic prompts in the webui but its no longer there

**Additional context**
not sure when it stopped but i know it worked before

**Comment by adieyal** [comment]
Not sure if you're looking for it under scripts, but it moved to its own section in the interface, have a look at this screenshot. 
![Screenshot from 2022-12-24 08-28-11](https://user-images.githubusercontent.com/420786/209424447-927cf76b-18a7-4970-975f-041ab8a896d9.png)

Could you confirm if it is there or not?

**Comment by bardicone** [comment]
I have the same issue - Dynamic Prompts is installed and up to date, but doesn't show up anywhere.

![2022-12-26 12_42_26-Stable Diffusion](https://user-images.githubusercontent.com/121439155/209550826-2b005406-0a1b-4e03-b732-3e8b14fbdce4.png)

**Comment by bardicone** [comment]
I had the same issue - I solved it, but I am not sure how.
I installed Python 3.11.1, but I'm not sure if that is what made a difference (I was doing a bunch of other, not SD related, stuff - not actively trying to fix this issue).  Regardless, I now have the menu showing up.

Perhaps, @nagaisa , you could try updating/re-installing python and restarting SD to see if that makes a difference?

**Comment by adieyal** [comment]
@bardicone thanks for the update - this suggests that there might be a python version incompatibility. @nagaisa , could you please check in your terminal if there is any error message?

**Comment by ClashSAN** [comment]
@bardicone python 3.11 is surprising as generally users have an issue starting webui with that version. Is there a reason you need 3.11 or is it just that you get that version automatically installed from the microsoft store?

**Comment by a56444c** [comment]
I just installed the extension through the webui and I too was unable to see the extension's menu.
Turns out restarting the ui with the buttons, either in the extensions or the settings tabs, was not enough.
Problem solved after terminating the console and restarting it. Using Python 3.10.6 by the way.

**Comment by adieyal** [comment]
any error messages in the console?

**Comment by a56444c** [comment]
Sorry, I didn't pay attention. No errors since the restart though, basic syntax and wildcards are working fine.

**Comment by adieyal** [comment]
@nagaisa  I would like to close this issue - could you confirm whether this is a still a problem?
