### ISSUE TITLE
Feature request: Repeated usage of a wildcard chooses the same value

### ISSUE THREAD

**Issue by moreRGB** [adieyal/sd-dynamic-prompts#125]
Hello, 

i have the following **simplified** prompt scenario:

> A \_\_epoch\_\_ house in front of a river. \_\_epoch\_\_ garden, \_\_epoch\_\_ fence [..]

I would like to have an option or something like triple _ to have always the same value choosen from the **same** wildcard.

So for the above example I would like the following prompt result:
>- A 1920's house in front of a river. 1920's garden, 1920's fence 
>- A edwardian house in front of a river. edwardian garden, edwardian fence

This seem to be not possible with the current version, but please correct my iif i'm wrong here.

**Comment by RafaRed** [comment]
Same here

**Comment by adieyal** [comment]
> Hello,
> 
> i have the following **simplified** prompt scenario:
> 
> > A __epoch__ house in front of a river. __epoch__ garden, __epoch__ fence [..]
> 
> I would like to have an option or something like triple _ to have always the same value choosen from the **same** wildcard.
> 
> So for the above example I would like the following prompt result:
> 
> > * A 1920's house in front of a river. 1920's garden, 1920's fence
> > * A edwardian house in front of a river. edwardian garden, edwardian fence
> 
> This seem to be not possible with the current version, but please correct my iif i'm wrong here.

It isn't possible with the standard templating language, although jinja2 templates can do it, e.g.
```
{% with  decade = choice('1920s', '1930s', '1940s')  %}
    {% prompt %}
        A {{ decade }} house in front of a river. {{ decade }} garden, {{ decade }} fence
    {% endprompt %}
{% endwith %}
```

most people find jinja2 templates to be too complicated though. It's a good suggestion, i'll add it to my todo list to develop a simpler way to do it. In the meanwhile, perhaps try jinja2.

**Comment by adieyal** [comment]
> @moreRGB Same here, its a conflict with Unprompted extension. Removed the extension, and now its working.

Unprompted and Dynamic Prompts sometimes conflict with each other since they both process the raw prompt. If you need to, you can disable Dynamic Prompts using the Dynamic Prompts enabled checkbox. Unprompted may also have such a feature but I'm not sure.

![Screenshot from 2022-12-24 09-43-16](https://user-images.githubusercontent.com/420786/209426397-c64fd335-ef46-492a-9b64-35ab33fbb294.png)

**Comment by adieyal** [comment]
Recent versions of the extension now support a cyclical syntax which makes this possible, e.g.
`A __@epoch__ house in front of a river. __@epoch__ garden, __@epoch__ fence`

Here is how you do it with variants

`A {@1920s|1930s} house in front of a river. {@1920s|1930s} garden, {@1920s|1930s} fence`

You can read more about it here: https://github.com/adieyal/dynamicprompts#samplers
