### ISSUE TITLE
Multiple prompts no longer picked from wildcards

### ISSUE THREAD

**Issue by TimStewartJ** [adieyal/sd-dynamic-prompts#131]
**Describe the bug**
Multiple prompts no longer picked from wildcards

**To Reproduce**
1. Use `{n$$__wildcard__}` as a prompt, where n > 1

**Expected behaviour**
I expect n prompts to be chosen. However, only 1 is chosen.

**Additional context**
This only happens in v1.4.1. This does not happen in v1.4.0.

**Comment by adieyal** [comment]
Could you please test and re-open if the bug persists?

**Comment by thelittlemike** [comment]
I'm still having this issue as well.

**Comment by TimStewartJ** [comment]
> Could you please test and re-open if the bug persists?

Not seeing this issue in v1.4.4 anymore, thanks!

**Comment by thelittlemike** [comment]
Strange, working for me now too. I'm using it via Automatic1111 and going to extensions and check for update, it said I was up to date. I went back, stopped the service, ran a git pull and it gave me a new checksum. Then when I ran my webuser-ui batch again, it said downloading send2trash which I know you added.

Anyway, it's all working now, so thanks!
