### ISSUE TITLE
only using p.all_prompts[0] and ignoring p.all_prompts[1:]

### ISSUE THREAD

**Issue by mix1009** [adieyal/sd-dynamic-prompts#138]
**Describe the bug**
My extension https://github.com/mix1009/model-keyword also replaces prompts and insert keywords to prompt for custom models.
When I change the extension option to use "iterate", it replaces the p.all_prompts. But Dynamic Prompts only reads all_prompts[0] and ignores the rest.

**To Reproduce**
1. Install model-keyword extension
2. Select sd model with multiple keywords. (https://civitai.com/models/13/comic-diffusion has 6 keywords)
3. From Model-Keyword extension,  select "iterate" from multiple keyword option. (when there is multiple keywords associated with a model, this options iterates between keywords for each image generated)
4. Increase batch size or batch count to 6.
5. Generate image with prompt "cat".
6. All images have the same keyword. (first keyword)
```
charliebo artstyle cat
```

**Expected behaviour**
If Dynamic Prompts is disabled, 6 images have 6 different prompt with 6 different keywords(trigger words)
```
charliebo artstyle cat
holliemengert artstyle cat
marioalberti artstyle cat
pepelarraz artstyle cat
andreasrocha artstyle cat
jamesdaly artstyle cat
```

Also mention which checkboxes have been set.
Dynamic Prompts default settings.

**Additional context**
Below line ignores all_prompts[1:].
```
        original_prompt = p.all_prompts[0] if len(p.all_prompts) > 0 else p.prompt
```
I'm not sure, but changing the ordering of the extension processing might solve the issue. But for whatever reason, my extension processes first on my machine.

**Comment by adieyal** [comment]
This might get complicated because Dynamic Prompts also generates a new set of prompts from a provided prompt. In random(standard) mode, batch_size * batch_count new prompts are created from `all_prompts[0]`. In combinatorial mode, the number is the upper bound of the number of prompts, i.e. the actual number of prompts can be less than that.

Given that your extension is already creating new prompts, what do you think the best course of action is on my end? The easiest solution is to simply apply the same treatment to each of your 6 prompts that I currently do for `all_prompts[0]`. This may result in many images created than expected. 

Do you have an other suggestions?

**Comment by mix1009** [comment]
I agree that generating unexpected number of images is not the solution. If dynamic prompts processes the prompt first, there will be no problem. I'll check the code if extension developers could change the ordering of the extension chain. 

I guess users that intentionally use these extensions at same time will be few. I was confused about a bug report, that model-keyword is not working with "iter" option. I'll just add a note to model-keyword documentation about the issue.

You can close the issue, since there seems no easy fix without users getting confused.

Thank you.

Happy new year!

**Comment by adieyal** [comment]
Happy new year to you to :)

I'm happy to explore a fix with you if we can come up with a good way to address the issue. I'll keep this issue open for a little while.

**Comment by adieyal** [comment]
Closing this for new - we can re-open if either of us comes up with an idea for how to move forward on this.

**Comment by mix1009** [comment]
I've added some note about the issue on my extension readme:

<img width="791" alt="Screenshot 2023-01-10 at 2 08 15 PM" src="https://user-images.githubusercontent.com/1288793/211466863-65c026a5-0f5a-434e-8c2d-1c090170b054.png">

The source code of webui seems to sort the extension using extension folder name. So changing the project name should workaround the problem. But it's too late to rename it :<

Thank you.
