### ISSUE TITLE
Dynamic Parameters in the Prompt and range parameters

### ISSUE THREAD

**Issue by Koronos** [adieyal/sd-dynamic-prompts#14]
Could be helpfull something like the grid generation but using the prompt, something like:

%CFG_SCALE=29|30|31|32% %SAMPLIG_METHOD=Euler a|Euler% etc etc.

And maybe better, something like ranges as the number of parameters to print:

%CFG_SCALE=$$29-35% //This could be also applyed to the basic prompting, but is not helpier than the usage with generation params

**Comment by adieyal** [comment]
I like the idea - it might be easier for users if it was implemented in the ui with sliders or input boxes instead of the prompt box to make it easier to remember the keywords - what do you think?

**Comment by Koronos** [comment]
Could be good, remember the name of each parameter is going to be difficult. The input boxes was worked really well in the grid x/y generation and users are familiar with the interface. I like it.

**Comment by stysmmaker** [comment]
@Koronos I've made an extension for this available here, should be what you're looking for.
https://github.com/stysmmaker/stable-diffusion-webui-randomize

**Comment by adieyal** [comment]
Nice script - I've been meaning to play with AlwaysVisible. Given that you're implementing your code in `process` and not `process_batch`, does that mean that your settings are the same for every image in a generation? Have you considered process_batch?

**Comment by stysmmaker** [comment]
Good point, I hadn't considered it, thanks for pointing that out! Updated the script to use that now.

**Comment by adieyal** [comment]
I'm closing this issue because the randomize script addresses it. Since both scripts are set as AlwaysVisible, they are compatible with each other.
