### ISSUE TITLE
magic prompt not working

### ISSUE THREAD

**Issue by gsgoldma** [adieyal/sd-dynamic-prompts#141]
**Describe the bug**
i get this error when trying to use magic prompt: 

Error running process: D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 338, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 405, in process
    generator = self._create_generator(
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 188, in _create_generator
    generator = AttentionGenerator(generator, min_attention=min_attention, max_attention=max_attention)
TypeError: AttentionGenerator.__init__() got an unexpected keyword argument 'min_attention'

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to '...' magic prmpt and enable it, enable im feeling lucky, test a prompt
2. Click on '....' generate, then it adds nothing to the prompt and gets an error in the readout

Also mention which checkboxes have been set.

dynamic prompts checked, magic prompts checked

**Expected behaviour**

i expected it to either change up the prompt or add a new prompt.
 this happens whether or not im feeling lucky is checked
**Additional context**

**Comment by gsgoldma** [comment]
my bad, i guess you can't have both checked at same time

**Comment by adieyal** [comment]
It doesn't make sense to have both the magic prompt and I'm feeling lucky enabled at the same time, but it shouldn't break. I'll look into it. However, the error that you posted is related to the Attention Generator, I'm surprised that that threw an error. If after you've completely restarted Auto1111 you still see it, please let me know.
