### ISSUE TITLE
Attention Grabber sliders don't work, range is always between 0.0 and 0.5

### ISSUE THREAD

**Issue by AncalagonX** [adieyal/sd-dynamic-prompts#143]
The sliders don't seem to work for the attention grabber, and all random attention grabber weights always fall in the range of 0.0 to 0.5, reducing their attention rather than increasing it. For testing/troubleshooting, I removed all parenthesis/manually adjusted weights and was just using a simple plain text prompt.

**Using this prompt:**
`this is a test of the dynamic prompt attention weighting`

**...results in these example outputs regardless of what I've set the min/max attention grabber sliders to:**
`this is a test of (the dynamic prompt attention weighting:0.48)`
`(this:0.12) is a test of the dynamic prompt attention weighting`
`this is (a test:0.41) of the dynamic prompt attention weighting`

Also, when you have time perhaps it would be a good idea to have a checkbox to enable attention grabber for positive prompts and another checkbox to enable it for negative prompts, rather than both at once.

I really like this feature, so I'm looking forward to seeing this working as intended later!  The attention grabber is great, and allows me to inject a new kind of variability into my gens.

**Comment by adieyal** [comment]
This should be fixed in 1.5.9

**Comment by AncalagonX** [comment]
Beautiful, it works perfectly! Thanks for all the hard work pushing out all these changes!
