### ISSUE TITLE
New lines are removed from the PNG info, which ruins the format of the prompt in PNG info, and makes it into a mess

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [adieyal/sd-dynamic-prompts#148]
**Describe the bug**
New lines are removed from the PNG info, which ruins the format of the prompt in PNG info, and makes it into a mess.

**To Reproduce**:
1. Use any prompt with a new line, it gets removed from PNG info.
2. New lines should remain in the PNG info just as they appear in the prompt.

**Expected behavior**
New lines should remain in PNG info, they are an essential part of prompt formatting.

**Additional context**
The problem does not appear when this extension is turned off.
The problem appeared when I upgraded the extension to the latest version.

**Comment by adieyal** [comment]
Could you provide an example? The update ignores whitespace to enable developing of more intricate prompts. I can look into what's involved in retaining them, but it might not be a trivial change

**Comment by a-l-e-x-d-s-9** [comment]
I mainly care about new lines. I use new lines as a way to format the prompt, to separate different sections of the prompts into different logical blocks, usually my prompt is structured something like this: character description, new line, background description, new line, and styles.
Here is an example of a prompt:
``` 
cat, black cat, standing,

city, dirty streets, night,

hires, trending on artstation, 4k, oil painting  
```
The prompt always used to appear in PNG info the way it was written, so when copied from PNG info into the prompt, it was formatted as I wrote it, and I could easily continue to work on it.
But in the last update, the prompt in PNG info looks like this:
``` cat, black cat, standing, city, dirty streets, night, hires, trending on artstation, 4k, oil painting ```
i.e. single blob of text without newlines. And it ruins my whole organization method. Also, it doesn't contain any wildcards or other special features.
I'm not sure why would you want to reformat the prompt in PNG info, unless you need to replace the wildcard with an actual value. But if you reformat and due to some bug make a mistake, it makes the PNG info unreliable source of information. It will prevent the reproduction of the image at all, and can potentially influence many images. I think that my issue is an example of this problem, also issue #144 is another example of such future problems.
Can you explain why you need to reformat the prompt instead of just filling instances of wildcards?
Can't you just add a new field at the end of the PNG info, as a new section that would be ignored by WebUI, but the Dynamic Prompts extension would be able to read it and use it for whatever you want?
Actually, it is something that I wanted to request for a long time, when a wildcard is replaced in the prompt, you would add a section that would contain the prompt with wildcards as it appeared in the prompt.

**Comment by adieyal** [comment]
I like the png info idea. I haven't investigated it yet, but I'll have a look. With regards the white space, I hear you. The use case I was anticipating (which I find to be useful), is multiple levels of nested prompts. Given that only a few components of the template would actually appear in the final prompt, I would end up with many blank lines.

**Comment by a-l-e-x-d-s-9** [comment]
I'm not sure what you mean by "nested prompts", is it when you use __wildcard1__ and inside one of its lines there is a __wildcard2__?
But usually, when you replace  __wildcard__ with one of the lines from the file, it doesn't add a new line, so why a new line is added in "nested prompts" case?
I wonder if the case of "nested prompts" should be handled as an edge case and not influence all prompts.
Sorry, I like my new lines and I like wildcards, and I don't understand why suddenly I can't have both of them...

**Comment by adieyal** [comment]
There are three different types of tokens that dynamic prompts understands, literals (regular text), variants (`{a|b|c}`, and wildcards (`__wildcard__`)

The language definition is roughly:
```
  prompt :: one_or_more(chunks)
  chunk  :: literal | variant | wildcard
  literal:: regular strings
  variant:: literal("{") + prompt + zero_or_more(literal("|") + prompt) + literal("})
```
Notice that you can have complete prompts as each option in a variant. Wildcard files are interepreted as if each line is a prompt and so you can have the same level of flexibility there. Here is an example how this might play out:
```
  wisdom {
	  woman, __colours__ eyes, braided hair
	  |man using a __war/weapons/swords/european__, red turban
	  |dwarf weilding a warhammer, __colours__ beard
  }, 
  knows the meaning of life, warrior, hyper-realistic, peaceful, dark fantasy, unreal engine, 8k
```
Sample sentences could be:
* wisdom woman, blue eyes, braded hair, knows the meaning of life, warrior, hyper-realistic, peaceful, dark fantasy, unreal engine, 8k
* wisdom man using a bastard sword, red turban, knows the meaning of life .....
* wisdom dwarf weilding a warhammer, red beard knows the meaning of life....

If we didn't remove whitespaces, the first prompt would look like this:
```
  wisdom
    woman, blue eyes, braided hair
	   
          
          
  knows the meaning of life, warrior, hyper-realistic, peaceful, dark fantasy, unreal engine, 8k
```
Comments also pose a problem, e.g.:
```
  Test string
  # This  a comment until the end of the line
  // this is also a comment until the end of the line
  {A|/* this is an inline comment */B}
```

**Comment by a-l-e-x-d-s-9** [comment]
I see, but the new lines are not something that your language requires, you are using them just like me, to format your prompt.

You could have formatted your prompt:
```
wisdom { woman, __colours__ eyes, braided hair | man using a __war/weapons/swords/european__, red turban | dwarf weilding a warhammer, __colours__ beard }, 

knows the meaning of life, warrior, hyper-realistic, peaceful, dark fantasy, unreal engine, 8k
```
But you chose to use new lines and it only proves that new lines are important for prompt formatting, and probably should not be just removed. Also, I would argue that this very particular case that 90% of users would never even see. But if you remove all new lines all the time, most people will see it.
Even with your formatting of the example, I think it is better to have extra new lines, than not to have new lines at all.
If you want to remove the "extra" new lines that you added after "{", before "|", before and after "}", in case somebody using a variant in the exact way you are using it, it should be a special case that influence only these areas.
If you have a variant that looks like this:
```
text_before {
    orange
    | green,
    apple
    | banana
}

text_after
```
I don't think that you should remove the new line after "green,". When selected in my opinion it should be:
```
text_before green,
apple

text_after
```
The two most easy options to handle new lines:
1. Just ignore them as it was before, and let people format the prompt as they wish.
2. Remove white spaces only inside the variant itself, and do not touch anything outside.

**Comment by adieyal** [comment]
I plan to look into this to figure out the best way forward, but it's lower on my to do list I'm afraid since there are a few more urgent issues that need to be address first.

**Comment by a-l-e-x-d-s-9** [comment]
That's fine. Meanwhile, I'll just change it for myself. From a glimpse at commits I only need to remove squash_whitespace from the commit 8d06ee799bffe85443bbe5b07b757ea90561fc02, to revert this change, right?

**Comment by adieyal** [comment]
no - i don't think it's an easy fix as it is baked into the parser. If you're keen to roll up your sleeves then let me know and I can point you in the right direction. In the worst case, go to the extension directory and type 
`git checkout v1.4.4`

that will revert you to the version before the change

**Comment by a-l-e-x-d-s-9** [comment]
I looked at the code and got lost...
I'll revert to v1.4.4 for now.

**Comment by adieyal** [comment]
You might be interested in trying v2.1.0 - whitespace is being left untouched by default - let me know it goes

**Comment by a-l-e-x-d-s-9** [comment]
Thanks for letting me. I'll check it out.

**Comment by a-l-e-x-d-s-9** [comment]
I have been using version 2.1.1 today. I had an unrelated OOM crash, but on the next launch, I got this error:
```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/home/user/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/home/user/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 23, in <module>
    from prompts.generator_builder import GeneratorBuilder
  File "/home/alexds9/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generator_builder.py", line 21, in <module>
    class GeneratorBuilder:
  File "/home/user/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generator_builder.py", line 98, in GeneratorBuilder
    unlink_seed_from_prompt=constants.UNLINK_SEED_FROM_PROMPT,
AttributeError: module 'dynamicprompts.constants' has no attribute 'UNLINK_SEED_FROM_PROMPT'
```

**Comment by adieyal** [comment]
can you try updating - that looks like nn older version

**Comment by a-l-e-x-d-s-9** [comment]
Sure

**Comment by a-l-e-x-d-s-9** [comment]
Looks good, the latest issue seems to be gone.
The png info has lines as before, which is great.
Also, there is a template, it would be super useful!
Thank you very much!
