### ISSUE TITLE
A fixed seed no longer chooses the same wildcards

### ISSUE THREAD

**Issue by ange321** [adieyal/sd-dynamic-prompts#150]
**Describe the bug**

"Unlink seed from prompt" is unchecked but different wildcards are chosen for the same seed.

No checkboxes are ticked apart from "Dynamic Prompts enabled".

**To Reproduce**
1. Set prompt to {cat|dog|rabbit} and seed to 1
2. Click "Generate" a few times
3. Different wildcards are chosen for the prompt.

**Expected behaviour**
The same seed should choose the same wildcard unless the "Unlink seed from prompt" option is ticked.

This worked OK until the extension was updated in the last few days.

**Comment by adieyal** [comment]
I'm aware of this - will get it working again

**Comment by ange321** [comment]
Seems like this problem was introduced in v1.5.0 (a12227915738da9b816669bebe88523b88ec19fb)

**Comment by adieyal** [comment]
sorry, there have been a few other more pressing issues which is why I haven't addressed this yet, will get to it next.

**Comment by ange321** [comment]
No worries, my intention wasn't to get you to hurry up! I was just trying to find a version I could go back to in the meantime so I thought I've give you the info in case it helped.

**Comment by AncalagonX** [comment]
@adieyal There is a major bug (easily fixable) on Line 98 of generator_builder.py involving the `unlink_seed_from_prompt` variable that prevents the config dropdown from appear on the txt2img and other tabs.

**Comment by adieyal** [comment]
Ya, my deployment broke halfway. You should be able to update now

**Comment by AncalagonX** [comment]
It works now! Thanks a million for your crazy pace of updates, this is an extension I make great use of every day.

**Comment by adieyal** [comment]
:-)
