### ISSUE TITLE
A prompt with multiple wildcards from a file causes a hang when generating a batch.

### ISSUE THREAD

**Issue by ange321** [adieyal/sd-dynamic-prompts#151]
**Describe the bug**
Using a prompt with multiple file wildcards causes a hang when a hang/delay when a batch size is selected.

**To Reproduce**
1. Create a file based wildcard, e.g. __artist__ and include it a dozen or so times in a prompt
2. Set batch size to 20
3. Click "Generate"
4. The process hangs for several seconds with high CPU usage before generation starts.

No checkboxes are ticked apart from "Dynamic Prompts enabled".

**Expected behaviour**
There should be no appreciable delay when using multiple file wildcards.

This worked OK until the extension was updated in the last few days.

**Comment by adieyal** [comment]
thanks for reporting - i'll look into it

**Comment by ange321** [comment]
@adieyal, I've pulled the latest release but I'm still seeing the same problem. I think I'll try going back to an older version in the meantime.

**Comment by adieyal** [comment]
I tried this prompt

`__colours__ __colours__ __colours__ __colours__ __colours__ __colours__ __colours__ __colours__`

colours.txt has 13 entries which means there are 13**8 different possible prompts. I set my batch count to 20.  On my machine it took 32 secs.  Is your prompt any different to mine?

**Comment by ange321** [comment]
@adieyal 

The problem was introduced in commit 927f9392694c0e85804cf4fe6bc4e6944ff5a1cb (Fixed wildcard in random generator)

I've replicated using the same test you performed, colours.txt with 13 entries, batch count 20. I set steps to 1 to highlight the delay.

This is the batch time with commit 927f9392694c0e85804cf4fe6bc4e6944ff5a1cb
![image](https://user-images.githubusercontent.com/113105609/211192624-3335e88c-cac8-4dde-859c-e1879b5ebbea.png)

This is with 1097693e66f10fa57d9047299cef1caf271b480b
![image](https://user-images.githubusercontent.com/113105609/211192684-2cced748-e51a-4de5-8ab9-4aa248d9569b.png)

**Comment by adieyal** [comment]
Thanks for the sleuthing - will investigate further

**Comment by ange321** [comment]
I've just tested with the latest version and this now appears to be fixed.
