### ISSUE TITLE
Auto1111 prompt editing seems to clash with prompt wildcards now

### ISSUE THREAD

**Issue by Omenizer** [adieyal/sd-dynamic-prompts#156]
Prompt editing is broken when dynamic prompts are enabled
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#prompt-editing

[cow|cow|horse|man|siberian tiger|ox|man] results in [cow| with DP on, when it's off, the full bracket makes it into the prompt. 

Doesn't happen with " : ", so [cow: horse 0.5] works, but [cow|horse] doesn't. 

Everything after the 1st " | " is discarded it seems.

**Comment by Omenizer** [comment]
Thanks for the script btw, I use it all the time and it's great! 👍🙏🏼

**Comment by adieyal** [comment]
Are you using the latest version? I think that was fixed in v2.0.2. The latest version is v2.0.3. I tested your prompt on my setup and it works find. Could you check that you're up-to-date and then test again?

**Comment by Omenizer** [comment]
Will do, thanks. Might not have updated

**Comment by adieyal** [comment]
Closing this - please re-open if it happens again
