### ISSUE TITLE
Send the generated prompt into in-paint / img2img

### ISSUE THREAD

**Issue by joeyslucky22** [adieyal/sd-dynamic-prompts#16]
I'm loving this script! So much fun to mess around with!

Is it possible to send the generated prompt in txt2img over to inpainting / img2img? Currently I'm just copying and pasting the generated prompt into the in-paint tab. It's only a minor annoyance is all. Having a button to send the prompt and settings would be cool!

Thanks again!

**Comment by WASasquatch** [comment]
You could just write a script to save the result from text2img to a global var, and if that global var is not `None` and contains a path, then a result has been saved and requested for inpaint, then you can use that as a basis to load the inpaint pipeline and do a inpaint with same prompt used for text2img

**Comment by Koronos** [comment]
Could be esier just use the image browser tab. It have the generated prompt and you can send it to img2img with the button.

**Comment by adieyal** [comment]
> I'm loving this script! So much fun to mess around with!
> 
> Is it possible to send the generated prompt in txt2img over to inpainting / img2img? Currently I'm just copying and pasting the generated prompt into the in-paint tab. It's only a minor annoyance is all. Having a button to send the prompt and settings would be cool!
> 
> Thanks again!

How would this work with multiple prompts? i.e. if you create more than one batch.

**Comment by adieyal** [comment]
Closing this issue. I think @Koronos' suggestion is the best option, especially because of the multiple prompts scenario.

**Comment by fish-face** [comment]
Could I ask what the issue with multiple prompts is? When viewing txt2img images you are looking at one at a time, and you can only send one image to img2img. That image has one prompt, and that is the prompt that you almost always want to use.

Using the Image Browser is slower than copy-pasting the prompt, because you have to do at least three gradio loads - Image Browser, another time to get the new first page of results, and another to get the metadata. Gradio is slow, so this feels interminable.

**Comment by solonrice** [comment]
Ran into this issue myself.

@adieyal I would vote that this issue be opened. @fish-face is right, using another extension (image browser) by clicking a few times is not a good user experience. In txt2img you are already looking at a single image, have the generated prompt in the image pane, and almost always will want the actual generated prompt to be sent if you send the image somewhere else.
