### ISSUE TITLE
combinations repeat elements

### ISSUE THREAD

**Issue by acorderob** [adieyal/sd-dynamic-prompts#166]
**Describe the bug**

This `{0-3$$[cheek freckles]|cheek dimples|big teeth|winking an eye}` returned `winking an eye,winking an eye,cheek dimples` even though there are less combinations than options and it should not repeat them.

**To Reproduce**

See above.

**Are you using a local install or a colab?**

Local install.

**Expected behaviour**

Options should not be repeated.

**Additional context**

v2.1.1

**Comment by akx** [comment]
The random "rolls" are independent of each other at the moment, so this is quite expected.

An option would be to (add an option to) switch to a "random bag" method for alternation segments, i.e. the options are shuffled, and options are picked from the shuffled list until there are none, at which point the options are again shuffled back in. (This is how bricks are chosen in Tetris, by the way! You can use that to strategic advantage...)

**Comment by alexbfree** [comment]
Hi, commenting here as I raised a duplicate ticket #235 

Regarding the above:

> The random "rolls" are independent of each other at the moment, so this is quite expected.

I get that this is the code doing what it was coded to do, but I would question that design; when would it be useful in a prompt construction context to repeat a word? Surely it would never be useful?

> An option would be to (add an option to) switch to a "random bag" method ...

And if you agree that repeating a word is never useful, there is no need to add an option such as this, could just change the default behaviour to never repeat words. (except for the 'exception case' I mentioned in the linked ticket)

**Comment by alexbfree** [comment]
PS the linked ticket #166 also includes some more details that might be useful to whoever tackles this ticket.

**Comment by jjmenet** [comment]
While working for myself, I implemented some feature for myself and sharing the feature in form of pull requests. It will be nice if this helps the project. Let me hear what you are thinking! Thank you.

**Comment by adieyal** [comment]
This should no longer be happening in recent versions. Let me know if it happens again.
