### ISSUE TITLE
Request: Adding an option so magic prompt and get lucky does not affect negative prompts

### ISSUE THREAD

**Issue by Dravoss** [adieyal/sd-dynamic-prompts#171]
I think it would be useful if there was an option so magic prompt, get lucky and attention grabber would not add any term or modify the user negative prompt, because now some positive terms like "trending on artstation" or "artgerm" are regularly added usually lowering the quality of the end result picture. Thank you.

**Comment by adieyal** [comment]
one thing you can do is set "ignore negative prompts" in advanced settings. Not a perfect solution if you are still planning on using your own prompts in the negative prompts box.

**Comment by Dravoss** [comment]
Thank you for your response, I am doing that now and that is, in part, the reason i posted the bug #167 that you fixed earlier, in fact i misunderstood the tool tip text and though that "Disable negative prompt" functionality was what i am proposing here. I know it is not something critical, even so, I still think that it could be a nice feature to have.

**Comment by AncalagonX** [comment]
Is there an option to enable magic prompt/get lucky/attention grabber for only the positive prompt? Ideally I would like to allow them to alter the positive prompt, while leaving my negative prompt alone.

**Comment by Dravoss** [comment]
Not right now.

**Comment by adieyal** [comment]
I've pushed a new version (v2.3.4) that addresses this.

**Comment by Dravoss** [comment]
Thank you for looking into it. I have tested this new version and it worked like a charm.
