### ISSUE TITLE
[Feature Request] Option to keep the same instance of pattern for generated images

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [adieyal/sd-dynamic-prompts#173]
It can be useful in case you want to produce a single instance of the template but generate many images of it with different seeds.
Example prompt: \_\_character\_\_ inside \_\_place\_\_
Will generate the instance: Wolverine inside factory
And all generated images will use the same instance of the pattern with different seeds for images.

Many times, I want a random character, with a few variations of it.
As far as I know, there is no option to do something like this right now, right?

**Comment by a-l-e-x-d-s-9** [comment]
Currently, for each new image generated, the seed of the Dynamic Prompt increases by one. This proposal is suggesting 0 changes for every new image, so they all use the same instance of Dynamic Prompt. 
The more general idea will be an option to configure the amount of generated images needed to increase Dynamic Prompt by one. For example, if we set this value to 3, every 3 pictures will be generated with the same instance of Dynamic Prompt. That way we could control how much variation we want from each Dynamic Prompt instance.
By default, this value can be 1, which will preserve the default behavior of Dynamic Prompts.
I think it can be a very useful feature to have.

**Comment by adieyal** [comment]
Isn't what you're suggesting the same as auto1111 without Dynamic Prompts? If I understand you correctly, you want a static prompt but different seeds. There is something similar to what you're asking for (but not quite). In combinatorial mode, you can set the number of combinatorial batches. If you set it to 2 for example, then every possible combination of the prompt will generate 2 images.

**Comment by adieyal** [comment]
Closing this as I think this functionality already exists. Feel free to re-open if you think there is a good use case that isn't currently handled.
