### ISSUE TITLE
Options for changing the UI

### ISSUE THREAD

**Issue by Adil3tr** [adieyal/sd-dynamic-prompts#174]
Could we have options to hide parts of the UI for dynamic prompting, or move them to the wildcard manager tab? I constantly use the checkmark to unlink seed from the prompt, and the fixed seed checkmark, but I never use the rest of the options like Combinatorial generation, magic prompt, attention grabbers, feeling lucky, help, or templates. Alternatively, since the advanced options are most relevant to the core function of the extension, could that section be moved to the top below "Dynamic Prompts enabled?"

**Comment by adieyal** [comment]
The current order makes the most sense but I hear you regarding having to continually check boxes. I recently moved some settings into the Settings tab where their state is automatically saved. I don't think its a good idea to do that with unlink seed and fixed seed, but I can figure out the best way to save state for those as well while keeping them in advanced options.

Alternatively, I might be convinced to move them further up, but there isn't an appropriation section for them right now.

**Comment by Adil3tr** [comment]
Could the other things at least be collapsable? They're all always fully open even though they're a lot less straightforward or central than the core functionality of wildcards.

**Comment by adieyal** [comment]
Strange - mine is collapsed by default - I only see the Dynamic Prompts accordion, not even the enable checkbox. You should have a look in ui-config.json, I think you can show and hide various elements - you could probably customise the way that it looks so that suits how you work.

Are you running on a desktop or colab?

**Comment by Adil3tr** [comment]
Sorry, I mean that dynamic prompts is collapsible, but within it a lot of other things were exposed. I updated it and now there's just the combination and magic prompt/feeling lucky/attention grabber part that's always open. I guess I mean swapping the advanced settings and those so that the latter is exposed and those are collapsed. But it's not a huge deal I guess.
