### ISSUE TITLE
Save original (pre-randomized) prompt

### ISSUE THREAD

**Issue by space-nuko** [adieyal/sd-dynamic-prompts#176]
My workflow is usually, I have a dynamic prompt with a bunch of randomized variables to test out many different combinations of settings, then I pick one non-randomized prompt from the output and generate some variations from that

The problem is the original randomized prompt is never saved in this case, I have to remember to write it down separately or I might lose it when I want to go back to generating random things again

Instead of that I'm wondering if the original randomized prompt (with `{}`, etc.) could be saved alongside each generation in case I want to look at it again. Just beside the txt2img outputs per batch is fine

**Comment by adieyal** [comment]
There are two settings available for this in the settings tab.

1. Save template to metadata saves the raw prompt template to the PNG metadata
2. Write prompts to file will write a file with the same same but .txt as an extension with the raw template as well as every prompt used in the batch.

Does that work for you?

**Comment by space-nuko** [comment]
Oh I wasn't aware of those, thanks
