### ISSUE TITLE
Generated template CSV doesn't correspond to output image/txt filename

### ISSUE THREAD

**Issue by space-nuko** [adieyal/sd-dynamic-prompts#178]
**Describe the bug**
I want the .csv output by the `Write prompts to file` option to have the same naming scheme as the images, however they're named like `photorealistic-realistic-8k-unity-wallpaper-4k-ren-994.csv` instead of `000001-123478-photorealistic, realistic, 8k unity wallpaper 4k.csv`. This makes the sorting scheme I have for browsing through my outputs in Explorer inconvenient since I don't know which templates correspond to which outputs

**Expected behaviour**
The output `.csv` should use the same naming scheme as the output images/prompt files.

**Comment by adieyal** [comment]
if you're producing only a single image, then we can use `000001-123478-photorealistic, realistic, 8k unity wallpaper 4k.txt` - what name should be used if you're generating multiple batches?

**Comment by space-nuko** [comment]
I was thinking just the exact filename of the first image in the batch but with the `.csv` extension

**Comment by adieyal** [comment]
I've pushed this to a new branch - could you please test it?

In the extensions/sd-dynamic-prompts directory run these commands

```
git pull -a
git checkout chore/prompts-filename
```

**Comment by adieyal** [comment]
This is now available in v2.5.5
