### ISSUE TITLE
"Unlink seed from prompt" is always active

### ISSUE THREAD

**Issue by sialivi** [adieyal/sd-dynamic-prompts#183]
**Describe the bug**
The "Unlink seed from prompt" option seems to be active at all times, no matter if the option is checked or not, unless I'm grossly misunderstanding its purpose.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Generate two images using the same seed and the default settings ("Unlink seed from prompt" is unchecked), two different images will be generated.
2. Enable the "Unlink seed from prompt" option.
3. Generate two images using the same seed. The two images will still be different so it's not a case of the option being inverted.

**Are you using a local install or a colab?**

Local install. Both Auto1111 and the extension are up to date. Chrome browser.

**Expected behaviour**
Two identical images being generated when using the same seed and the option is unchecked.

**Comment by adieyal** [comment]
Try this:

Set batch count to 9
Set this as your prompt `I love {red|blue|green|yellow} roses`
Set your seed to `3434`

Generate with unlink seed from prompt unchecked. You'll get something that looks like this (it will differ depending on what model you're using)

![grid-0330-3434-I love green roses](https://user-images.githubusercontent.com/420786/212493260-365b038f-5f97-436e-bd88-17539abdf464.png)

Re-run that a few times and it should be the same.

Now check the unlink seed from prompt checkbox and try again. You'll get something that looks like this.

![grid-0333-3434-I love red roses](https://user-images.githubusercontent.com/420786/212493269-82c8218b-1d3f-4aa0-b8ba-7c1b33a6fdee.png)

By default, the random prompt generator uses the same seed as that used by the image generation. If that seed is fixed, the prompts will be the same every time you click generate. If you check the box, then the random generator will use a new seed.

**Comment by sialivi** [comment]
Very strange, it's working fine now with the exact same tests, prompts and seeds I tested with earlier. I must have messed up somehow.

**Comment by adieyal** [comment]
Let me know if you notice it again
