### ISSUE TITLE
"Don't generate images" option doesn't work

### ISSUE THREAD

**Issue by sialivi** [adieyal/sd-dynamic-prompts#184]
**Describe the bug**
Images are always generated no matter if the "Don't generate images" is checked or not.

**To Reproduce**
1. Generate an image with "Don't generate images" unchecked. Image is generated as expected.
2. Enable the "Don't generate images" option.
3. Click "Generate". The image is still generated.

**Are you using a local install or a colab?**

Local install. Auto1111 and extension are both up to date. Chrome browser.

**Expected behaviour**
Generate only the prompt when the "Don't generate images" option is enabled.

**Comment by adieyal** [comment]
One image always needs to be generated given how the extension interfaces with auto1111. Try setting your batch size to 100 and then generate. If you've enabled writing prompts to file, you'll see a file with 100 prompts, but only a single image.

**Comment by sialivi** [comment]
I see. It's unclear from its description that it only works for batches.

**Comment by adieyal** [comment]
yeah - I'll update the description
