### ISSUE TITLE
Pictures in Batch doesnt randomize + Spacy not installed

### ISSUE THREAD

**Issue by UBBK** [adieyal/sd-dynamic-prompts#185]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to Stable Diffusion
2. Click on Generate over 1 Batch Count
3. Generations all have same prompts, non randomized

Local Install with Commit hash: 4d158c1879bcc88dad1211cad900b927bfcfb819

At the beginning i get the error:
"Spacy not installed, attention generator will not work. Install with pip install dynamicprompts[attentiongrabber]"

**Additional context**
And seems like since last time i updated there are 2 versions of Dynamic Prompts in my UI:
![image](https://user-images.githubusercontent.com/116608006/212525421-0dba8621-5f11-4e3b-8c1a-49efdf5d7191.png)

**Comment by Nyarlathotep885** [comment]
UBBK, do  you have https://github.com/kohya-ss/sd-webui-additional-networks installed? I believe this is due to a bug with the latest version of additional networks.

See my comment on https://github.com/kohya-ss/sd-webui-additional-networks/issues/27 for potential fix.

**Comment by raidoll** [comment]
Same symptoms.This is not the root of the bug, but by unchecking one of the two "Dynamic Prompts enabled" checkboxes, it is now randomly generated.

**Comment by adieyal** [comment]
@raidoll, @UBBK  Do you have additional networks installed?

**Comment by adieyal** [comment]
Regarding spacy, please see this issue - https://github.com/adieyal/sd-dynamic-prompts/issues/181 - the most recent version should hopefully address it.

**Comment by adieyal** [comment]
Thanks for the update - hopefully that addresses this issue for everyone who is experiencing it.
