### ISSUE TITLE
Wild cards refuses to work properly on the AUTOMATIC1111 webUI

### ISSUE THREAD

**Issue by DarthMov** [adieyal/sd-dynamic-prompts#186]
**Describe the bug**
Wild cards do not work at all even when wild cards files are installed in the correct locations and the dynamic prompt script is installed correctly. Combination prompting like {2$$artist1|artist2|artist3} works fine but wild cards like __bird__ or __color__ will not work at all. Instead will treat it as a normal prompt and will simply generate it as "birdv or "color" instead of a random selection in the txt file. 

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Have stable diffusion will be wide installed on paper space using this version: https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/master/StableDiffusionUI_Voldemort_paperspace.ipynb
2.Install the dynamic prompts.py script in the scripts folder
3.Install your wild cards folder in the extensions/dynamic prompts/wildcards folder
4. Attempt to use wild cards as a prompt

Also mention which checkboxes have been set.
In the dynamic prompts tab I have dynamic prompts enabled checked

**Are you using a local install or a colab?**
Paper space. Much less limiting than collab

If a colab, which one?
https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/master/StableDiffusionUI_Voldemort_paperspace.ipynb

**Expected behaviour**
When I use the birds while card, I should get different species of birds if I set the batch size to 5. Instead it is treating the wild cards as normal words. When I remove the underscores and ensure it is using the same seed, I get the exact same pictures, which is a clear indicator it is not working at all. 

Below is a link to a screen recording of me reproducing the issue. I hope this helps. 
https://user-images.githubusercontent.com/100316723/212551226-7669bad0-f3fc-4506-be6e-ffbedf28f9f7.mp4

**Additional context**

**Comment by adieyal** [comment]
Does your wildcard file appear in the Wildcard Manager tab?  To be sure you're using the right directory. Look at bullet point 4 in the Wildcard Manager tab. It shows you the full path to the correct folder.

**Comment by DarthMov** [comment]
> Does your wildcard file appear in the Wildcard Manager tab? To be sure you're using the right directory. Look at bullet point 4 in the Wildcard Manager tab. It shows you the full path to the correct folder.

Sorry for the late response. Yes I have the wildcard files correctly installed in the right file directory.
![Screenshot_20230115_133359_Chrome](https://user-images.githubusercontent.com/100316723/212560238-51358f21-5475-466f-b871-eee38d4fd0fc.png)

**Comment by adieyal** [comment]
That doesn't look like the correct directory.  Unless you've changed the name of the extension, it should be `extensions/sd-dynamic-prompts/wildcards` - what directory is given in the Wildcards Manager in the 4th bullet point?

**Comment by DarthMov** [comment]
This is what I see on the wild cards tab: I should probably know that I installed this via the extensions tab. 
![Screenshot_20230115_143210_Chrome](https://user-images.githubusercontent.com/100316723/212562989-9e46055f-6e61-4c1e-a9bf-3784a6e308e6.png)

**Comment by adieyal** [comment]
Thanks for the screenshots and screen recording. The extension directory name looks strange, but according to your last screenshot it's correct. Do you get any error in the console? I can't imagine why wildcards aren't working if inline variants are.

**Comment by adieyal** [comment]
We can also manually test if to see that everything is working as it should. In a cell in your notebook, try adding this and running it:
```
from pathlib import Path
from dynamicprompts.wildcardmanager import WildcardManager
wm = WildcardManager("/notebooks/stable-diffusion-webui/extensions/dynamic-prompts/wildcards")
print(wm.get_all_values("__color__"))
```

Does that return a list of colours?

**Comment by DarthMov** [comment]
Unfortunately it did not. I got this error message instead:

![Screenshot_20230115_161122](https://user-images.githubusercontent.com/100316723/212567651-a1e98089-8c3e-4de5-9de2-580d94d26a7a.jpg)

**Comment by adieyal** [comment]
sorry, typo

use this instead

```
from pathlib import Path
from dynamicprompts.wildcardmanager import WildcardManager
wm = WildcardManager(Path("/notebooks/stable-diffusion-webui/extensions/dynamic-prompts/wildcards"))
print(wm.get_all_values("__color__"))

```

**Comment by DarthMov** [comment]
All right, now we're getting somewhere. Does this help?
![Screenshot_20230116_095243_Chrome](https://user-images.githubusercontent.com/100316723/212706798-9e2175ee-7632-44ed-b0f2-3d3bd6ecea53.png)

**Comment by adieyal** [comment]
That proves that dynamicprompts can find your wildcards. Could you confirm the version of Dynamic Prompts you're using? You can find it in the help section.

**Comment by DarthMov** [comment]
Currently I'm on 2.3.4. 
![Screenshot_20230116_112352_Chrome](https://user-images.githubusercontent.com/100316723/212725144-4eaa3a58-1669-446c-81d0-a5c6b6a9d099.png)

**Comment by adieyal** [comment]
I'm stumped. Everything is working as it should. The latest version is 2.3.5 - there's chance that it might address this since it updates dependencies. If you're using the same server instance, you'll need to manually uninstall dynamicprompts

`venv/bin/python -m pip uninstall dynamicprompts`

then update the extension and restart the webui.

If you're installing everything from scratch, then it should upgrade automatically.

Could you also confirm that there are no errors when you click generate?

**Comment by DarthMov** [comment]
I ran `venv/bin/python -m pip uninstall dynamicprompts`, deleted the Dynamic Prompts Folder, reinstalled dynamic prompts, did the `__bird__` test and it still doesn't appear to work. I hope this heped but these are the essages generated after I tried the `__bird__` batch again:

`{"prompt": "bird", "all_prompts": ["bird", "bird", "bird", "bird", "bird"], "negative_prompt": "", "all_negative_prompts": ["", "", "", "", ""], "seed": 1727151994, "all_seeds": [1727151994, 1727151995, 1727151996, 1727151997, 1727151998], "subseed": 3445773679, "all_subseeds": [3445773679, 3445773680, 3445773681, 3445773682, 3445773683], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler a", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "1556988a", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {"Wildcard prompt": "__bird__"}, "index_of_first_image": 1, "infotexts": ["bird\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1727151994, Size: 512x512, Model hash: 1556988a, Model: anything-v4.5-pruned_0.5-ProtoGen_X3-4_0.5-Weighted_sum-merged, Hypernet: v2, Hypernet hash: 9f172158, Wildcard prompt: __bird__", "bird\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1727151994, Size: 512x512, Model hash: 1556988a, Model: anything-v4.5-pruned_0.5-ProtoGen_X3-4_0.5-Weighted_sum-merged, Hypernet: v2, Hypernet hash: 9f172158, Wildcard prompt: __bird__", "bird\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1727151995, Size: 512x512, Model hash: 1556988a, Model: anything-v4.5-pruned_0.5-ProtoGen_X3-4_0.5-Weighted_sum-merged, Hypernet: v2, Hypernet hash: 9f172158, Wildcard prompt: __bird__", "bird\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1727151996, Size: 512x512, Model hash: 1556988a, Model: anything-v4.5-pruned_0.5-ProtoGen_X3-4_0.5-Weighted_sum-merged, Hypernet: v2, Hypernet hash: 9f172158, Wildcard prompt: __bird__", "bird\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1727151997, Size: 512x512, Model hash: 1556988a, Model: anything-v4.5-pruned_0.5-ProtoGen_X3-4_0.5-Weighted_sum-merged, Hypernet: v2, Hypernet hash: 9f172158, Wildcard prompt: __bird__", "bird\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1727151998, Size: 512x512, Model hash: 1556988a, Model: anything-v4.5-pruned_0.5-ProtoGen_X3-4_0.5-Weighted_sum-merged, Hypernet: v2, Hypernet hash: 9f172158, Wildcard prompt: __bird__"], "styles": ["None", "None"], "job_timestamp": "20230117020637", "clip_skip": 1, "is_using_inpainting_conditioning": false}


![SmartSelectImage_2023-01-16-21-10-50](https://user-images.githubusercontent.com/100316723/212794577-25445f0c-f544-4265-a6bf-2b3e8df7e3cf.png)
`

**Comment by adieyal** [comment]
In the directory tree on the left hand side of your screen, I see two wildcards folders. Also, it looks like you're using the wildcards extension at the same time as SD Dynamic Prompts - since these extensions have overlapping functionality, I don't know what the behaviour will be. Try disabling the wildcards extension and try again.

**Comment by adieyal** [comment]
@DarthMov is this still an issue for you?

**Comment by adieyal** [comment]
Closing this - re-open if it continues to be an issue.

**Comment by Drael64** [comment]
I have this same issue. Was working for a long time. Shows in wildcard manager. Just doesn't trigger on the prompt now.

**Comment by Drael64** [comment]
I get a similar thing. It's intermittent oddly. For periods of time it won't trigger at all, and then for periods it will. Wildcard manager shows. Using automatic1111 for AMD. Get the following errors:

 Traceback (most recent call last):
      File "A:\ST\stable-diffusion-webui-directml\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "A:\ST\stable-diffusion-webui-directml\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 481, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "A:\ST\stable-diffusion-webui-directml\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "A:\ST\stable-diffusion-webui-directml\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 67, in generate
        gen = self._context.sample_prompts(template, num_images)
      File "A:\ST\stable-diffusion-webui-directml\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "A:\ST\stable-diffusion-webui-directml\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "A:\ST\stable-diffusion-webui-directml\venv\lib\site-packages\pyparsing\core.py", line 1197, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 1234), (line:1, col:1235)

**Comment by akx** [comment]
A `pyparsing.exceptions.ParseException` always means there's something wrong with your prompt, and we can't help you without seeing the prompt.
