### ISSUE TITLE
Refactor Batch Count Settings

### ISSUE THREAD

**Issue by ghostsquad** [adieyal/sd-dynamic-prompts#191]
The behavior of `batch count` and `batch size` under normal conditions makes sense:

Batch Size -> The number of images to create per batch
Batch Count -> The number of batches to create

When using dynamic prompts, what I expect `Batch Size` to indicate the number of images _per_ combination instance. E.g. `{red|blue|green} flower`, I want 4 red flower images, 4 blue flower, and 4 green flower.

Then, batch count, multiple _that_ N number of times.

It doesn't really make sense to add `combinatorial batches`, and then make me set the `batch count` equal to the number of possible combinations available. Just calculate the combinations.

**Comment by adieyal** [comment]
That's not how DP interprets batch size and batch count. Those settings are division of labour, ie number of images to generate at a time * number of iterations. Combinatorial batches is used to indicate how many images you want per combination.

**Comment by ghostsquad** [comment]
I expected to be able to set them all to 1, and given a combination of N, get N images, unfortunately, I only get 1 image. I have to change the batch count to match the number of combinations.

**Comment by adieyal** [comment]
I'm happy to refactor and open to suggestions. Combinatorial batches in particular is confusing. Here are some constraints/considerations.

1. I can't change the semantics of  `batch size`. `Batch size` specifically means, how many images to generate simultaneously. I don't think your earlier suggestion that `batch size` should mean number of images per prompt instance would work. Say I want 10 images, nearly all GPUs would fall over with such a large batch. Currently `combinatorial batches` plays that role.

2. Combinatorial explosion can be problematic so I think you need a safeguard preventing the creation of an unexpectedly large number of images.

> I expected to be able to set them all to 1, and given a combination of N, get N images, unfortunately, I only get 1 image. I have to change the batch count to match the number of combinations.

One possibility would be to replace `combinatorial batches` with max images. Then `num batches`  could be used to set the number of complete sets of unique prompt instances to generate. I don't think `Batch size` can change.  The problem with that approach is that it breaks the metaphor.  If we define a batch as a complete set of prompt instances, then `batch size` becomes non-sensical.

**Comment by ghostsquad** [comment]
> One possibility would be to replace combinatorial batches with max images. Then num batches could be used to set the number of complete sets of unique prompt instances to generate. I don't think Batch size can change. The problem with that approach is that it breaks the metaphor. If we define a batch as a complete set of prompt instances, then batch size becomes non-sensical.

Yes please!

**Comment by adieyal** [comment]
But the issue with overloading the meaning of batch sounds as confusing as the current situation.

**Comment by ghostsquad** [comment]
Let's take a step back. Without dynamic prompt enabled, `batch size` == number of images to generate, each being seed + 1 from the last, and `batch count` is the # of times to do that.

With `dynamic prompts`, `batch count` is ignored, because this extension produces a certain number of images per batch based on the combination matrix. This would be easy to explain and not surprising to users.

What you could introduce then is `combination max/limit` within the settings, which is set to 0 (unlimited) by default. This setting could be explained in a couple different ways. It's like `head` in linux, as in, it takes the first N combination prompts, and does only that, regardless of how many combinations are present in the current prompt. It could be explained as a limiter, so that you can create a prompt with a lot of combinations, but if you need to iterate quickly on parts of the prompt unrelated to the dynamic variables, you can use `combination max/limit` to produce only a few combinations, until you get the desired output, then increase the max all the way, or to 0 (meaning unlimited).

**Comment by adieyal** [comment]
OK, I can go with that. But just to be clear, that only applies to
combinatorial mode. Standard / random mode remains unchanged. ie total
number of images is equal to batch count * batch size.

In combinatorial mode we ignore batch count completely and introduce a max
images option. The meaning of batch size doesn't change however.
Effectively batch count becomes `min(num_combinations, limit) / batch size`

**Comment by adieyal** [comment]
Have a look at v2.3.7 - I've added the max generation slider as discussed. Thanks for the suggestion.

**Comment by ghostsquad** [comment]
I think there's some text left behind (I just updated to latest version, seeing the Max generations)
```
Generate all possible prompts up to a maximum of Batch count * Batch size)
```

**Comment by ghostsquad** [comment]
oh, and it looks like the readme needs to be updated too:
https://github.com/adieyal/sd-dynamic-prompts#increasing-the-maximum-number-of-generations
