### ISSUE TITLE
randomize script linked under Compatible Scripts in README.md returns 404, user account not found

### ISSUE THREAD

**Issue by terbo** [adieyal/sd-dynamic-prompts#194]
**Describe the bug**
Going to the URL https://github.com/stysmmaker/stable-diffusion-webui-randomize produces a 404 error, and the user stysmmaker isn't found.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to 'https://github.com/stysmmaker/stable-diffusion-webui-randomize'

**Comment by adieyal** [comment]
Thanks - fixed
