### ISSUE TITLE
401682b - max generations overwrites batch size / count

### ISSUE THREAD

**Issue by ArrowM** [adieyal/sd-dynamic-prompts#195]
401682b  overwrites batch size/count by default and sets the number of output images to 0, which breaks the later negative_prompt code. The fix should probably be something like
```python
if max_generations > 0:
```
added to `extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py:318`

**Comment by sa-shiro** [comment]
i dont have much python knowledge, but modifying or changing `extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py:318` did not fix it for me, but reverting `scripts/dynamic_prompting` to 5a4c554c95bd96f7520113f6a7e5ff22b9ff1568 fixxed it as a quick solution

**Comment by adieyal** [comment]
Thanks - fixing it now

**Comment by adieyal** [comment]
Just pushed v2.3.8 - could you please test it and let me know if the problem is fixed?

**Comment by sa-shiro** [comment]
yeah, 408db435f1d24f5f2bbdf2836fa644c00c46c8d3 fixed it

**Comment by adieyal** [comment]
Thanks - I'll leave this issue open for a while in case there are other related bugs.
