### ISSUE TITLE
[feature request] choose which wildcards  choose sequentially and which choose randomly in combinatorial mode.



### ISSUE THREAD

**Issue by TranquilOasis** [adieyal/sd-dynamic-prompts#199]
I would like the ability to sequentially step through every line in chosen files while choosing randomly from others. Then in combinatorial mode have it only step through the first set of files.

Current behavior:
Right now combinatorial mode will step through every single line of every single wildcard file in the prompt. Exponentially growing the number of photos generated with each added wildcard. Additionally it goes in order of appearance in the prompt which forces you to make compromises on where each wildcard appears in the prompt.

Desired behavior:
Some syntax to denote in prompt which wildcards will choose randomly and which ones will sequentially step through every line in the file. Then have an option for combinatorial mode to only count the sequel wildcards.

Example:
Imagine I wanted to create many modeling photos of the same subject, but with different outfits, accessories, poses, hair color, ect. I would like to generate every single outfit and pose, but just want a variety of accessories and hair colors. Right now combinatorial mode will make hundreds of photos as it does outfits x accessories x pose x hair colors. When all you really want is outfits x pose + (random accessories and random hair color).

**Comment by adieyal** [comment]
Good suggestion - I'll look into it - does this need to be on both `__wildcards__` and `{...}`? I suspect both. I would need to make changes to the syntax which I'm not super excited about. Perhaps something like `(?R__wildcard__)` and `(?C{...})` - that way we can use the same syntax for both.

**Comment by TranquilOasis** [comment]
Yea both would be great! I have not looked into the repo at all, so I'll leave implementation to you, but having the freedom to choose random choice or sequential walk would be amazing.

While you are in there another suggestion would be to denote the number of choices from a file. for instance on random mode pick 10 random colors from the color file, and either cycle through them for the entirety of the batch or stop when you hit the 10th color. 
-- This is less important as you can get this functionality with the way the system is now, just makes the prompt HUGE.

**Comment by akx** [comment]
This was implemented in https://github.com/adieyal/dynamicprompts/issues/11
