### ISSUE TITLE
Prompts cut off at first {

### ISSUE THREAD

**Issue by thevoidwatches** [adieyal/sd-dynamic-prompts#202]
I'm trying to use Dynamic Prompts for the first time - I've attached the prompt I built for reference. However, when I attempt to use the webui to generate from the prompt, it only generates off of '(1woman), (solo)' rather than using the prompt. I tried putting the prompt all into one line without comments, and had the same issue.

[prompt.txt](https://github.com/adieyal/sd-dynamic-prompts/files/10483913/prompt.txt)

**Comment by thevoidwatches** [comment]
Nevermind, I figured out the issue - I had four _ in a row instead of two when attempting to call a wildcard, which must have screwed something up along the way. Fixing that has also fixed the prompts.

**Comment by adieyal** [comment]
that's a pretty intense prompt

**Comment by thevoidwatches** [comment]
It'll get worse before I'm done with it! Although a decent chunk of the complexity will probably end up in wildcards.
Before I discovered that dynamicprompts was a thing, I wrote a python program to do this kind of thing and spit out text files that I could feed into the webui's prompts-from-file script. These feels neater.

**Comment by adieyal** [comment]
I could tell you were a coder, simply based on the indentation :)

Is your problem sorted? Can I close this ticket?

**Comment by thevoidwatches** [comment]
Yes, problem solved. Of course, now I have other problems, but so it goes.
