### ISSUE TITLE
ModuleNotFoundError: No module named 'dynamicprompts'

### ISSUE THREAD

**Issue by Jonseed** [adieyal/sd-dynamic-prompts#209]
**Describe the bug**
After updating the extension, I get this error.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Update extension in extensions tab
2. Apply and restart UI
3. See terminal for error. And dynamic prompting doesn't show up in the UI. I'll try restarting the server.

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**
local

If a colab, which one?

**Expected behaviour**
Dynamic Prompting loads

**Comment by Jonseed** [comment]
Restarting the server looks like it is installing send2trash (what's that for?), and a new version of dynamicprompts. That will probably take care of this.

**Comment by Jonseed** [comment]
That solved it.

**Comment by adieyal** [comment]
Send2trash is used when wildcard files are deleted. Instead of deleting them forever, they are sent to trash.

When you previously upgraded DP, did you restart auto1111? Trying to understand why some people are experiencing this issue.

**Comment by Jonseed** [comment]
I only restarted the gradio UI, which is how many extensions get loaded after install. But it seems this one needs a complete reboot of the webui server.

**Comment by WASasquatch** [comment]
Having this issue as well, I did not fully restart, so going to try that next.

**Comment by WASasquatch** [comment]
Nope, full restart and still getting the error

```txt
Error running install.py for extension extensions\sd-dynamic-prompts.
Command: "E:\python\automatic\webui2\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd-dynamic-prompts\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "E:\python\automatic\webui2\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py", line 4, in <module>
    from dynamicprompts.utils import is_empty_line
ModuleNotFoundError: No module named 'dynamicprompts'
```

**Comment by adieyal** [comment]
Hmmm, DP is using auto1111's run_pip function which should find the right environment. While this issue unresolved you can install using `C:\Users\jorda\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install dynamicprompts==0.4.0`. It's not ideal but should get you going.

**Comment by adieyal** [comment]
Is this still an issue with the latest version?

**Comment by Jonseed** [comment]
It is not an issue for me, so I'll close it.
