### ISSUE TITLE
Error loading script: dynamic_prompting.py

### ISSUE THREAD

**Issue by yamkz** [adieyal/sd-dynamic-prompts#21]
I don't understand why the script is not working for me.

`Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "~~~/stable-diffusion-webui/modules/scripts.py", line 159, in load_scripts
    exec(compiled, module.__dict__)
  File "~~~/stable-diffusion-webui/scripts/dynamic_prompting.py", line 52, in <module>
    class WildcardManager:
  File "~~~/stable-diffusion-webui/scripts/dynamic_prompting.py", line 65, in WildcardManager
    def get_files(self, relative:bool=False) -> list[Path]:
TypeError: 'type' object is not subscriptable`

**Comment by adieyal** [comment]
Strange - before trying to debug it, I just released a new version with extensive changes. Could you install that and test it first? Note, it's now an extension instead of a script so it should be installed into the extensions directory (see the README)

**Comment by yamkz** [comment]
I installed it in the extensions directory 
but for some reason it doesn't work...
I get the same error.😢

/content/drive/MyDrive/AI/stable-diffusion-webui/extensions/sd-dynamic-prompting

**Comment by yamkz** [comment]
code that only works on python 3.11?

**Comment by yamkz** [comment]
I couldn't get it to start in colab.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3944

In paperspace, python 3.9 works and this extension also works.

**Comment by adieyal** [comment]
do you by any chance still have the old dynamic_prompting.py script in the webui's directory? If so, remove it and try again. Perhaps that's why it works in a new install on the paperspace server.

**Comment by krakensurf** [comment]
L:\stable-diffusion-webui>webui-user.bat

L:\stable-diffusion-webui>git pull
Already up to date.

L:\stable-diffusion-webui>pause
Press any key to continue . . .
venv "L:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Commit hash: 17a2076f72562b428052ee3fc8c43d19c03ecd1e
Installing requirements for Web UI
Launching Web UI with arguments: --vae-path models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.pt --force-enable-xformers
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "L:\stable-diffusion-webui\modules\scripts.py", line 168, in load_scripts
    exec(compiled, module.__dict__)
  File "L:\stable-diffusion-webui\extensions\dynamic-prompts\scripts\dynamic_prompting.py", line 12, in <module>
    from prompts.wildcardmanager import WildcardManager
  File "L:\stable-diffusion-webui\extensions\dynamic-prompts\prompts\wildcardmanager.py", line 4, in <module>
    from .wildcardfile import WildcardFile
  File "L:\stable-diffusion-webui\extensions\dynamic-prompts\prompts\wildcardfile.py", line 3, in <module>
    class WildcardFile:
  File "L:\stable-diffusion-webui\extensions\dynamic-prompts\prompts\wildcardfile.py", line 8, in WildcardFile
    def get_wildcards(self) -> set[str]:
TypeError: 'type' object is not subscriptable

**Comment by adieyal** [comment]
got it - you're using python 3.8. Are you able to upgrade? If not, I'll fix it, but 3.9 makes the syntax a little nicer

**Comment by krakensurf** [comment]
I'm trying to figure out how.  I have 3.10 installed and put this line in my webui-user.bat file.
set PYTHON="C:\Users\19045\AppData\Local\Programs\Python\Python310\python.exe"
but it doesn't seem to do anything because it's clearly running 3.8

**Comment by krakensurf** [comment]
I updated to 3.10, then decided to install SD on a new drive, but for some reason it doesn't see the new path.  I'm installing Python 3.11.  If it doesn't work then I'll delete everything in the drive and start from scratch "After" 3.11 is running perfectly.  I'll let you know what happened.

**Comment by krakensurf** [comment]
I have it working now.  Apparently you can only use SD with Py3.9 at the moment.  All newer versions break it one way or another.  
I have installed Py3.8 - 3.11.  I reinstalled everything and it seems to be very happy.  Thanks for you help.

**Comment by adieyal** [comment]
Awesome - glad that you've got it working. I'm running 3.10.6 without any issues.

**Comment by floorcat** [comment]
Could you @adieyal make this work on 3.8? I cannot upgrade python due to relying on pytorch built for rx580 from here: https://github.com/xuhuisheng/rocm-gfx803

**Comment by adieyal** [comment]
@floorcat could you please test this version and let me know if it works? https://github.com/adieyal/sd-dynamic-prompts/tree/python3.8-compatibility

**Comment by adieyal** [comment]
0.13.7 on the main branch should now work

**Comment by floorcat** [comment]
Seems to work now. Thanks!
