### ISSUE TITLE
Can't use "|" inside of a dynamic prompt

### ISSUE THREAD

**Issue by unoriginalscreenname** [adieyal/sd-dynamic-prompts#211]
If I try to follow the template and separate wildcard prompts with a pipe "|" it doesn't appear to work.  Using and or any other word does.

`{2$$ AND $$__animals/animals_categories__}` = Fish AND Dog
`{2$$|$$__animals/animals_categories__}` = IndexError: list index out of range

The pipe is actually really useful when switching between tokens.  Especially if you're creating characters.  It would be great to be able to have this.

**Comment by akx** [comment]
Could you put the examples here in triple-backquote (```) blocks? Github's markup is making them hard to read since it's parsing the underscores, etc. itself.
