### ISSUE TITLE
Where are magic prompt models saved?

### ISSUE THREAD

**Issue by rethink-studios** [adieyal/sd-dynamic-prompts#220]
For the sake of keeping models on the same drive, I'm wondering where magic models are saved once downloaded automatically when once uses a new prompt model for the first time.

Would be nice to store models in: stable-diffusion-webui/models/Magic_Prompt. or Dynamic_Prompt

Thanks!

**Comment by akx** [comment]
The magic models are [pre-trained Huggingface `transformers` models](
https://github.com/adieyal/dynamicprompts/blob/f63a429244b252d025a20d5ee0c08ab7054fbde0/src/dynamicprompts/generators/magicprompt.py#L79-L91).

It [looks like](https://github.com/huggingface/transformers/blob/73a2ff69740123ef85343580cbfa9ee8ce5e6fd5/src/transformers/utils/hub.py#L77-L80) you can set the `HF_HOME` environment variable to something else (e.g. `c:/wherever/your/a1111/is/models/huggingface`), or more specifically `TRANSFORMERS_CACHE` too. However, unless you move your current huggingface cache directory (likely `$HOME/.cache/huggingface`) there too, some other things will get re-downloaded.

**Comment by akx** [comment]
This was answered above, and also in https://github.com/adieyal/sd-dynamic-prompts/discussions/206.
