### ISSUE TITLE
2.52 update breaks parsing 0-length selections

### ISSUE THREAD

**Issue by j1xwnbsr** [adieyal/sd-dynamic-prompts#223]
What was working prior to this:
{0-1$$a|b|c|d}
would return nothing or one item. 0-1 could also be 0-3 etc.
Since 2.52, if the random number picker lands on 0, instead of returning an empty set, the parser just stops and kicks out whatever it has, which results in a broken prompt.

**Comment by akx** [comment]
By the looks of it, this has been broken before 2.5.2 (and is a bug in the https://github.com/adieyal/dynamicprompts library anyway).

**Comment by j1xwnbsr** [comment]
This is  not fixed as of the current origin/main rev 49eaa7997e80ae479e17e63752110e7ec72b1204.

Test:
prefix,
({0$$a|b} {1$$c|d|e}),
suffix

Should yield:
prefix,
(c),
suffix

Instead, it yields:
prefix
(),
suffix

Changing the prompt to include a space between the cde items:
prefix,
({0$$a|b} {1$$ $$c|d|e}),
suffix

Yields:
prefix,
(

Note that the computed prompt terminates.

**Comment by akx** [comment]
@j1xwnbsr Did you make sure to also update the `dynamicprompts` library? It doesn't unfortunately necessarily get auto-updated if you update this extension via the UI.

**Comment by akx** [comment]
Okay, yeah, I think I can repro this in the current `dynamicprompts` `main` too 👍

 Will take a look, but I think it'll be better to land https://github.com/adieyal/dynamicprompts/pull/14 first :)

**Comment by j1xwnbsr** [comment]
Just for reference, @akx I pulled directly via Git without using the A111 ui - allows me to go back to a prior commit before the issue appeared.

**Comment by akx** [comment]
This should now be fixed for good if you pull the current `master` and update to dynamicprompts 0.6.0.
