### ISSUE TITLE
Prompt Magic - Not Showing Prompts

### ISSUE THREAD

**Issue by bitshifter52** [adieyal/sd-dynamic-prompts#228]
Based on the documentation, I would expect the Prompt Magic to show the prompts it generated in addition so generating an image. I used the prompt, "sexy girl space alien" and tried different settings within Prompt Magic and no prompts were shown nor were prompts added to the name of the png file. I tried the, "Don't generate images" switch and images were still generated - I don't know if this is a separate issue.

The images that are generated look good and interesting, but I cannot figure out what the prompt was that generated the image. The Dynamic prompts portion works well - thank you for this.

I am using AUTOMATIC1111 on an ubuntu 22.04 box with a nvidia graphics card.

**Comment by adieyal** [comment]
Have a look at the Settings tab.  Under Dynamic Prompts there is a checkbox to `Save template to metadata`. Make sure that's checked. You can also check the `Write prompts to file:` option if you want a csv file will all the generated prompts.

**Comment by akx** [comment]
The extension does edit the actual prompt before generation, so the regular A1111 machinery will take care of saving it to the PNG, a TXT sidecar file, or even the filename (where it can be truncated, though, but still).

**Comment by akx** [comment]
Closing as stale.
