### ISSUE TITLE
[Feature Request] Grouping for sets of random keywords

### ISSUE THREAD

**Issue by space-nuko** [adieyal/sd-dynamic-prompts#230]
The first half of #188 is a way for DP to modify SD settings. The other half is a way to update those keywords in lockstep

So I propose a way to group two sets of random keywords. The keywords picked will have the exact same index, and don't count for combinatorial generation. So I can do something like (hypothetical syntax)

```
{group1&&red|blue|yellow} hair, {group1&&red|blue|yellow} eyes
```

and always expect to get hair and eyes of the same color. Functionally this is like taking a single random choice and duplicating the same randomly picked value across the prompt

And if you use combinatorial generation with that prompt, you will only get 3 outputs instead of 3*3=9

Maybe groups can have different numbers of keywords, where the index is picked from the maximum of both groups and the rest receives a modulo, like

```
{group1&&orange|yellow} background, {group1&&blue|teal|purple|pink} hair
```

and `orange` background will only ever be paired with `blue` or `purple` hair, and `yellow` background will only be paired with `teal` or `pink` hair. This is optional of course, you could require that all groups have the same number of choices

Also related: #125

**Comment by adieyal** [comment]
I've been wanting to implement groups for a while. What do you think of this syntax?

{% define mygroup={red|blue|yellow} %}

$mygroup hair, $mygroup eyes

or something similar to that?  Defining groups inline might make templates more difficult to read. The other benefit is that if we also implement https://github.com/adieyal/sd-dynamic-prompts/issues/229, we can use similar syntax for settings.

**Comment by akx** [comment]
Hmm, I think you could do this today with vanilla Jinja `with` and the `choice` function we expose:
```jinja
{% with g=choice("red", "blue", "yellow") %}{{ g }} hair, {{ g }} eyes{% endwith %}
```

**Comment by adieyal** [comment]
but then you need to use the jinja syntax and I think many non-coders find it intimidating. I thought that which should transition to always-on Jinja, but to allow regular syntax without the `{% prompt %}...{% endprompt %}` tags

**Comment by akx** [comment]
Sure, agreed. I just thought I'd toss it out there that it is possible (for random generation only, combinatorial wouldn't work OOTB) right now (though now that I think of it, by the way, the random functions in the Jinja environment aren't deterministic).

**Comment by space-nuko** [comment]
But there's also the lockstep part to consider, like a model file that has an activation keyword. The original proposal was to be able to do this

```
{group1&&<model:ligne-claire-diffusion.ckpt>|<model:impressionist-diffusion.ckpt>},
{group1&&ligne claire|impressionism}
```

and have the models and keywords match up. It sounds like the syntax you're proposing is about copying a single group to multiple places. I think that's better served by wildcards already

This is more like defining multiple arrays of random choices where the index selected is the same for all arrays in the group

**Comment by adieyal** [comment]
I'm currently looking into a cycling mechansim which is similar to combinatorial, but rather cycles through all available options, e.g.

```
{red|green|blue} {square|circle|triangle}
```

it will generate
```
red square
green circle
blue triangle
```


If your groups have a different length, then it will cycle accordingly, e.g.

```
{red|green} {square|circle|triangle}
```
will generate

```
red square
green circle
red triangle
green square
red circle

```

I think that should address your proposal.

**Comment by space-nuko** [comment]
Should the user still have the option to have separate combinatorial groups though? So they can have those three cycled combinations, but a separate group like `{impressionism|abstract}` that's still combinatorial, so it would give 6 or 10 results instead of 3 or 5 results in the examples

**Comment by adieyal** [comment]
Yes, the new syntax that I'm working on looks like this:

```
{~A|B|C}  # Random
{!A|B|C}  # Combinatorial
{@A|B|C}  # Cyclical
{A|B|C}   # Default, either random in random mode or combinatorial in combinatorial mode.
```

So, in random mode this prompt:

`{@X|Y|Z}{A|B|C}`

will produce
```
XB
YA
ZB
XB
YC
ZA
XC
...
```

This example:
> {group1&&red|blue|yellow} hair, {group1&&red|blue|yellow} eyes

will be implemented as

`{@red|blue|yellow} hair, {@red|blue|yellow} eyes.`

You will probably need to run it in random mode if you want 3 prompts, since combinatorial mode will see it as a single literal.

> {group1&&orange|yellow} background, {group1&&blue|teal|purple|pink} hair

This will be `{@orange|yellow} background {@blue|teal|purple|pink} hair`

and will generate:

```
orange background, blue hair
yellow background, teal hair
orange background, purple hair
yellow background, pink hair.
```

You can still use combinatorial, for example:

`{@red|green} {doors|cars|aliens} {@daytime|night time}`

Will generate:
```
red doors daytime
green cars nighttime
red aliens daytime
```

**Comment by space-nuko** [comment]
Thanks for the details, also could you add a syntax that forces each group to cycle per-batch instead of per-image? I want to combine this with LoRAs that require specific keywords (closed eyes) but LoRAs can only be applied per-batch, so it doesn't make sense to use the other keywords in that case

**Comment by adieyal** [comment]
You can check it out here: https://github.com/adieyal/dynamicprompts/pull/27

The syntax doesn't support directly specifying the cycle time, but you can be creative with it.
e.g.

If you want to repeat the same element three times in a row before moving to the next element:

```python
from pathlib import Path

from dynamicprompts.wildcardmanager import WildcardManager
from dynamicprompts.generators import RandomPromptGenerator

wm = WildcardManager(Path("/tmp"))
gen = RandomPromptGenerator(wildcard_manager=wm)
print(gen.generate("""
{@
    {A|B|C}
    |{A|B|C}
    |{A|B|C}
}
""", 12))

# ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'A', 'A', 'A']
```

So if your batch size is 3, then you will have the same value for each image in a batch
