### ISSUE TITLE
Won't stop breaking metadata/PNG Info

### ISSUE THREAD

**Issue by Adil3tr** [adieyal/sd-dynamic-prompts#233]
When I have the "Save template to metadata: Write prompt template into the PNG metadata" checkbox enabled, it breaks the function where I send an image to txt2img. So I turned it off but it's still adding the template to the metadata and breaking my images, and they didn't even have any wildcards in them, I just left DP on.

**Comment by adieyal** [comment]
Strange - will take a look

**Comment by Adil3tr** [comment]
It's even doing this when I have DP turned off with the checkbox.

**Comment by Bwin4L** [comment]
I have the same issue, the template breaking sending to other tabs as well as DP still adding templates to the metadata even when it's turned off via the "Dynamic Prompts enabled" checkbox and the "Save template to metadata: Write prompt template into the PNG metadata" checkbox disabled.

**Comment by akx** [comment]
I think https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6685 will be of interest here.

**Comment by adieyal** [comment]
@Adil3tr @Bwin4L Could you please test the latest release? The code works but on my end, it seems like auto1111 might be overriding the fix for some images. I'd like to know if it is only my installation or whether I should continuing trying to debug it.

**Comment by Adil3tr** [comment]
I updated everything but it still seems to be doing it with both the setting and the Dynamic Prompt Enabled toggle off.

`Blowfish, (made of Gel), functional high fantasy, art by Olafur Eliasson, pop Soviet Realism, detailed
Steps: 25, Sampler: Euler a, CFG scale: 7, Seed: 2196309222, Size: 512x512, Model hash: b15a0e35c2, Model: plushies
Template: Blowfish, (made of Gel), functional high fantasy, art by Olafur Eliasson, pop realism, detailed
`

**Comment by adieyal** [comment]
It makes sense that disabling the extension doesn't fix it, since the metadata is already in the image. Could you please try three scenarios.

1. Only positive prompt
2. Only negative prompt
3. Both prompts

**Comment by Adil3tr** [comment]
> It makes sense that disabling the extension doesn't fix it, since the metadata is already in the image. Could you please try three scenarios.
> 
>     1. Only positive prompt
> 
>     2. Only negative prompt
> 
>     3. Both prompts

Oh no, it still won't import correctly, but it's even adding the metadata to new generations with the extension enabled but the toggle within the extension's UI turned off. I'll try this

**Comment by Adil3tr** [comment]
Okay, with everything updated, it's no longer adding the metadata to new images. I hope it doesn't come back, I think it sometimes worked and sometimes didn't before.

**Comment by adieyal** [comment]
What happens if you disable writing to templates in the settings?

**Comment by Adil3tr** [comment]
> What happens if you disable writing to templates in the settings?

That has never been on and I clicked "save settings" just in case. It was off.
