### ISSUE TITLE
Can you clarify how to refresh and fully reload a wildcards file after changing it?

### ISSUE THREAD

**Issue by alexbfree** [adieyal/sd-dynamic-prompts#234]
**Describe the bug**

Not a bug exactly, more of a question. Sometimes when I make changes to a file in the wildcards directory, the extension doesn't seem to pick up the changes. e.g. I still see it sometimes inserting a tag that I have already removed from the `adjectives.txt` file when I use `__adjectives___` in my prompt (even after a restart of a1111). Please can you clarify:

(a) is there some caching going on, and if so, how can it be cleared? 
(b) When are the wildcards files reloaded from disk and when aren't they?
(c) Is there a preferred workflow when updating wildcards files to ensure updates are picked up?

Thanks

**To Reproduce**

Steps to reproduce:
1. Create an `adjectives.txt` file in the `wildcards` folder with a small number of adjectives.
2. Use `__adjectives__` in a prompt. 
3. Start generating a batch of images with that prompt.
4. Remove an adjective from the file and save it.
5. (optionally) restart a1111 (or try other things to clear cache)
6. Repeat steps 2 and 3, generate a large number of images.
7. Inspect the PNG info or generated prompt files - Notice that sometimes the deleted adjective will still be used in some image generations/prompts.

Settings: extension enabled, standard wildcard settings selected, not using combinatorial batches, no magic prompt stuff.

**Are you using a local install or a colab?**

local

**Expected behaviour**

1. the removal of a wildcard should be picked up by the extension at a definable moment/event, and that removed entry should never show up any more in prompts after that moment.
2. the user should be able to know with certainty when an updated wildcards file will be picked up and when it won't.

**Additional context**

N/A

**Comment by akx** [comment]
@adieyal By the way, something I've been thinking about that it could be neat to store wildcards in an SQLite database. I think it would be pretty cool to be able to quickly search for a wildcard "file" based on words contained within...

**Comment by adieyal** [comment]
I've been thinking the same thing, a search box in the Wildcards Manager tab to quickly find a wildcard would be helpful.

**Comment by alexbfree** [comment]
thanks for the quick response. Incidentally I found the problem was partly because I had accidentally got a word in more than one file, so it was still picking it up from the other file even after cache clearing! sorry about that, it's probably working better than I thought!
