### ISSUE TITLE
Occasional repetition of insertion value when picking multiple from same wildcards file

### ISSUE THREAD

**Issue by alexbfree** [adieyal/sd-dynamic-prompts#235]
**Describe the bug**

When using the `{{2-3$$ and $$__nationality__}}` wildcard format, sometimes I see the same insertion value used twice. I would expect it to always pick distinct values within each prompt if there is more than one.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a wildcards file `nationality.txt`. e.g.
```
Irish
Dutch
Mexican
Thai
Canadian
Estonian
Greek
```
2. Enter `A {{3$$ and $$__nationality__}} man` as prompt and generate a large number of images (keep steps + image width + height low as image quality doesn't matter)
3. Examine the generated images' prompts using PNG Info or the accompanying generated prompt text files.
4. Notice that sometimes you see a repeated tag, e.g. `A Greek and Greek and Irish man` which should not be a valid selection of 3 nationalities as `Greek` is repeated. 

Standard settings: extension enabled, no magic prompt stuff, no combinatorial generation.

**Are you using a local install or a colab?**

local

**Expected behaviour**

When picking `n` values from a wildcards file, the tags should never be repeated within the same prompt (each pick should be made at random from the remaining unused-in-this-prompt tags). 

Exception case: If `n` exceeds the number of wildcard values in the file, repetition is expected (unless you set a rule of cutting short the number of insertions once the file is exhausted).

**Additional context**
N/A

**Comment by adieyal** [comment]
I think this is a duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/166

**Comment by alexbfree** [comment]
Yes I agree, can close this as duplicate. Some of the details in this ticket might be useful to whoever tackles #166.
