### ISSUE TITLE
How do I generate a different prompt for each batch?

### ISSUE THREAD

**Issue by skeddles** [adieyal/sd-dynamic-prompts#239]
I'm using this for the wildcards feature, I used to use the wildcards script but it wasnt working so i found this.

It is properly generating prompts from my wildcards file. The problem is it only generates the prompt once, so if I do a batch of 10 images, all 10 will have the same prompt. 

What I want is for every image to have a unique prompt. I think this is how wildcards used to work.

Is there a way to get dynamic prompts to do this?

**Comment by reynol1** [comment]
you can use "prompts from file or textbox" script

**Comment by adieyal** [comment]
Dynamic Prompts already generates a new prompt for every image. Could you share your prompt so that I can better understand your question.

**Comment by akx** [comment]
@skeddles Um... Just to be sure, which extension are you running in particular and which version..? I don't think this extension adds "Wildcard prompt:" to the PNG info (and a `git log -S` doesn't show that in history either).

**Comment by skeddles** [comment]
Ah I think you were right, I went in and deleted the wildcards script from the scripts folder and extensions folder. It seemed like both had failed to load, but they must have been working in the background.

**Comment by akx** [comment]
Glad you got it sorted out!
