### ISSUE TITLE
Interface is unusable in white mode

### ISSUE THREAD

**Issue by Yaiol** [adieyal/sd-dynamic-prompts#24]
White mode
![image](https://user-images.githubusercontent.com/38218161/198876333-23d7cd7e-b1a9-4a1b-aa45-15772cbd391a.png)

Dark mode
![image](https://user-images.githubusercontent.com/38218161/198876645-4ebeb4e8-3584-4c20-9686-13c1678dfe41.png)

**Comment by adieyal** [comment]
Thanks - I just pushed 0.13.1 - could you please test it and let me know what you think?

**Comment by Yaiol** [comment]
Thanks, is better although it breaks a bit the overall white style

Your style in white now
![image](https://user-images.githubusercontent.com/38218161/198926240-e664eaf1-1cc3-4c9e-b0c5-d19d10f22dc4.png)

I tried to make a css style that is a bit more respectful of both the white theme and your orginal idea with dark theme
My style in white
http://localhost:7860/?__theme=white
![image](https://user-images.githubusercontent.com/38218161/198926378-9468145f-d751-4fd8-a796-5c320bb949ac.png)

My style in dark
http://localhost:7860/?__theme=dark
![image](https://user-images.githubusercontent.com/38218161/198926431-25a6fcef-2fcd-4eaf-8481-bda7d1b4ce09.png)

Hope it helps
css file as attachment
[style.css.txt](https://github.com/adieyal/sd-dynamic-prompts/files/9897850/style.css.txt)

**Comment by adieyal** [comment]
Looks much better - thank you. You can see the update on v0.13.5

**Comment by Yaiol** [comment]
> Looks much better - thank you. You can see the update on v0.13.5

You are welcome :)
