### ISSUE TITLE
LoRA models in dynamic prompts not handled correctly

### ISSUE THREAD

**Issue by sialivi** [adieyal/sd-dynamic-prompts#241]
**Describe the bug**
I don't know if this is a limitation in Auto1111 or something that's not handled properly in the extension but prompts with LoRA tags behave in unexpected ways:

1) If the LoRA tag is added to the generated prompt through a wildcards file, it has no effect
2) If a LoRA tag is defined anywhere in the prompt window in Auto1111, including inside dynamic selectors, the LoRA model will be active no matter if it's selected for the generated prompt or not. So a selector like `{<lora:model1:1>|<lora:model2:1>}` will result in both models being active, not just the one selected, and with a prompt like `{|<lora:model:1>}` the model will be active even if the blank entry is picked.

**To Reproduce**
![image](https://user-images.githubusercontent.com/364734/216800389-4bf2f896-784b-4f64-938d-130bd633a2ba.png)

**Are you using a local install or a colab?**
Local install, both Auto1111 and the extension is up to date.

**Comment by olion500** [comment]
Expected to be fixed!

**Comment by mabcat** [comment]
It's the same situation for `hypernet:`, yes?

**Comment by space-nuko** [comment]
Fixed here, wait for auto to merge: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7789

**Comment by olion500** [comment]
It works for me :)

**Comment by Bonedragon1300** [comment]
doesn't work for me still

**Comment by gruppler** [comment]
Same, I'm using the latest version of the webui and dynamic prompts, but I still have LoRa models taking effect whether they're randomly chosen or not.

**Comment by adieyal** [comment]
I can't reproduce this. This is what I tried

1.  Set seed to 1 (to ensure the output is reproducible)
2.  Set prompt to ` {<lora:tokiameStyleThick_1:1>|{<lora:tokiameStyleThick_1:1>|test}` 
3.  Check `Unlink seed from prompt`  in advanced settings (to make sure that the prompt is still randomly generated, even though the seed is fixed)
4.  Continually press Generate

I get different images depending on what prompt was randomly chosen

**Comment by gruppler** [comment]
Do you get the same results when using jinja templates to randomize?

**Comment by xelmirage** [comment]
I encountered the same issue
![00000-1224859882-20230228](https://user-images.githubusercontent.com/2993178/223665633-a6c4c6b7-706c-4de1-87fe-1211a0076aa5.png)
this is the result of such info and template:
`(8k, RAW photo, best quality, masterpiece:1.2), (realistic, photo-realistic:1.37),<lora:liuyifei_10:0.3>, omertosa,1lady,city, ,professional lighting, photon mapping, radiosity, physically-based rendering, backlight bokeh, smile, mature, full body,night, thin leg, thin thigh, slim leg, slim thigh, long leg, shorts, jeans,dress, office lady ,laced long boots,t-shirt,short hair, floating hair, canon 85mm,outdoors`


`Negative prompt: EasyNegative, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, glans,extra fingers,fewer fingers,strange fingers, bad hand, fat ass, hole,kid,naked, Ripped jeans, hole jeans, fat thigh,6 fingers, bikini, underwear, nsfw, nude, briefs, knickers, underpants, panties, swim suit,leg open,hands,lingerie,bra,sit on the ground,umbrella, cellphone photography`


`Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1224859882, Size: 512x768, Model hash: 95afa0d9ea, Model: chilloutmix_NiPrunedFp32, Denoising strength: 0.5, Hires upscale: 2, Hires upscaler: Latent`


`Template: (8k, RAW photo, best quality, masterpiece:1.2), (realistic, photo-realistic:1.37),{<lora:goutouLora_v20:0.3>,|<lora:anotherpureface_v10:0.5>,|<lora:iu_V1:0.5>,iu1,|<lora:LORAJapaneseActressYui_gakki10:0.7>,|<lora:koreanDollLikeness_v15:0.7>, (aegyo sal:1),|<lora:dilrabaDilmurat_v1:0.3>,|<lora:liuyifei_10:0.3>,|} omertosa,1lady,{|}{city|lake}, {rain,wet|},professional lighting, photon mapping, radiosity, physically-based rendering, backlight bokeh, {smile,|} mature, {choker,|} {{{full body|half-length portrait},{sunlight|night}, thin leg, thin thigh, slim leg, slim thigh, long leg, {{{short skirt|shorts}, {jeans|stocking|pantyhose|}},dress}, {student|office lady} ,{long boots|dr.martens laced long boots|jimmy choo high heel|high heel|dr.martens boots|laced long boots|1stuart weitzman 5050 boots}}|head portrait,sunlight},{bare shoulders|t-shirt|short jacket,school uniform,hoodie},{long hair|short hair}, floating hair, canon 85mm,{0.1::gold-rimmed glasses,|}outdoors`

`Negative Template: EasyNegative, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, glans,extra fingers,fewer fingers,strange fingers, bad hand, fat ass, hole,kid,naked, Ripped jeans, hole jeans, fat thigh,6 fingers, bikini, underwear, nsfw, nude, briefs, knickers, underpants, panties, swim suit,leg open,hands,lingerie,bra,sit on the ground,umbrella, cellphone photography`

but when using the generated prompt directly like this:

`(8k, RAW photo, best quality, masterpiece:1.2), (realistic, photo-realistic:1.37),<lora:liuyifei_10:0.3>, omertosa,1lady,city, ,professional lighting, photon mapping, radiosity, physically-based rendering, backlight bokeh, smile, mature, full body,night, thin leg, thin thigh, slim leg, slim thigh, long leg, shorts, jeans,dress, office lady ,laced long boots,t-shirt,short hair, floating hair, canon 85mm,outdoors`


the result changed to this:
![00007-1224859882-20230228](https://user-images.githubusercontent.com/2993178/223666221-766a3919-0d33-436d-8b3d-d6fa79b1771b.png)

and I tried replacing the lora part from genarated result to template:

`(8k, RAW photo, best quality, masterpiece:1.2), (realistic, photo-realistic:1.37),{<lora:goutouLora_v20:0.3>,|<lora:anotherpureface_v10:0.5>,|<lora:iu_V1:0.5>,iu1,|<lora:LORAJapaneseActressYui_gakki10:0.7>,|<lora:koreanDollLikeness_v15:0.7>, (aegyo sal:1),|<lora:dilrabaDilmurat_v1:0.3>,|<lora:liuyifei_10:0.3>,|}, omertosa,1lady,city, ,professional lighting, photon mapping, radiosity, physically-based rendering, backlight bokeh, smile, mature,  full body,night, thin leg, thin thigh, slim leg, slim thigh, long leg, shorts, jeans,dress, office lady ,laced long boots,t-shirt,short hair, floating hair, canon 85mm,outdoors`

the result changed back to:
![00000-1224859882-20230228](https://user-images.githubusercontent.com/2993178/223666630-518f0dc9-5638-45fd-a86e-f1e1872a47e4.png)


it seems that the actual prompt sent to the sd model will randomise lora part, although the text displayed on the ui is randomised.

**Comment by adieyal** [comment]
Do you have a recent version of auto1111? I think https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7789 should have fixed this.

**Comment by xelmirage** [comment]
> Do you have a recent version of auto1111? I think [AUTOMATIC1111/stable-diffusion-webui#7789](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7789) should have fixed this.

It fixed! Thank you!

**Comment by adieyal** [comment]
How did you fix it? Update auto1111?

**Comment by xelmirage** [comment]
> How did you fix it? Update auto1111?

It means update the sd-webui, in my case, it fixed the problem:)

**Comment by xelmirage** [comment]
> How did you fix it? Update auto1111?

Sure, I updated sd.webui and sd-dynamic-prompts, it fixed this problem. But I don't know is updating sd-dynamic-prompts is necessary.
