### ISSUE TITLE
AttributeError: 'Script' object has no attribute '_pnginfo_saver'

### ISSUE THREAD

**Issue by WASasquatch** [adieyal/sd-dynamic-prompts#244]
**Describe the bug**
When I run a prompt I always get the same wildcards for the batch every run. I tried to use '**Unlink seed from prompt**' to see if that would help, and I got the following error.

```
Traceback (most recent call last):
  File "E:\python\automatic\webui2\stable-diffusion-webui\modules\scripts.py", line 357, in process
    script.process(p, *script_args)
  File "E:\python\automatic\webui2\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 353, in process
    self._pnginfo_saver.enabled = opts.dp_write_raw_template
AttributeError: 'Script' object has no attribute '_pnginfo_saver'
```

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to **Advanced Options**
2. Click on **Unlink seed from prompt**

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**

Local install

**Expected behaviour**

I'm not sure regarding the settings I have clicked beyond it's own description, but I'm almost certain there shouldn't be an error. 

**Additional context**
I do not diffusion into the PNG info as I find it abusive for that intended purpose of the format, and potentially dangerous for commercial usages and unaware users that don't know this stuff carries over to TIFF/PNG saves (in post processing from the file).

**Comment by akx** [comment]
That's kind of weird, since there isn't (shouldn't be) a code path where `_pnginfo_saver` isn't set (since it's set in `Script`'s `__init__`)... unless, of course, A1111 does something arcane with e.g. `reload()`. If you recently updated the extension via the UI, can you try turning it off and on again, i.e. restart the webui?

**Comment by akx** [comment]
Closing since there's been no reply and this would've cropped up for others, I think :) 

Feel free to reply and we'll reopen if this is still an issue.
