### ISSUE TITLE
Option Tweaking

### ISSUE THREAD

**Issue by Skalinos** [adieyal/sd-dynamic-prompts#25]
**Thank You** for updating the script into an extension - great improvements and possibilities! 

Noticed (in one of the closed issues) that it might be tricky to make it work with other scripts / integrate it into SD. I'm interested in X/Y plot in particular (to allow option tweaking, like changing hypernets, steps, CFG, etc.). 

Is it possible with the current iteration of Dynamic Prompting / possible at all?

**Comment by adieyal** [comment]
I'll investigate it. I like the idea, but I see the scope of the project to focus on prompt generation rather than tweaking all settings. I understand that it's unfortunate that you can only use one script at a time which means you either have to choose X/Y plot or dynamic prompts, but not both. Ideally I would leverage XY prompt's functionality rather than re-implementing it myself.

I'll give it some thought.

**Comment by adieyal** [comment]
Adding a link to this issue which I think is asking for the same functionality: https://github.com/adieyal/sd-dynamic-prompting/issues/14

**Comment by stysmmaker** [comment]
You might want to take a look at https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards which functions without having to select a script from the scripts dropdown. I believe it's due to the `AlwaysVisible` flag, which then triggers the `process` function to run.

**Comment by Skalinos** [comment]
Unfortunately, the Wildcards extension doesn't cover Dynamic Prompts' useful features like Combinations and Nesting. If it did - I wouldn't ask ;D

**Comment by stysmmaker** [comment]
Yeah, just moreso pointing out I don't think anything needs to be re-implemented in order to get what you want from this. I would make a PR but I'm not sure what we'd want to do about the current script interface, since using the `AlwaysVisible` flag removes it from that dropdown entirely afaik.

**Comment by adieyal** [comment]
From what I can see, `AlwaysVisible` is just a way of saying that it should be available in both txt2Img and img2img views - see this line: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/scripts.py#L46

**Comment by stysmmaker** [comment]
That confused me at first too, but the other two functions implemented, `process` and `postprocess`, are hooks that are ran only for those `AlwaysVisible` scripts. Really a better name for it might be something like `AlwaysEnabled` or `AlwaysOn`, the latter of which is actually an attribute that gets set if it returns the `AlwaysVisible` object. See this line: 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/17a2076f72562b428052ee3fc8c43d19c03ecd1e/modules/scripts.py#L209-L212

That then causes those `AlwaysVisible` scripts to be invoked for the `process` and `postprocess` functions, like here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/17a2076f72562b428052ee3fc8c43d19c03ecd1e/modules/scripts.py#L301-L317
And then they're ran in the general image processing loop, which applies to both txt2img and img2img here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/17a2076f72562b428052ee3fc8c43d19c03ecd1e/modules/processing.py#L481-L482

This is distinct from how scripts are usually ran, where it only runs in the specific txt2img or img2img loop, like here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/17a2076f72562b428052ee3fc8c43d19c03ecd1e/modules/txt2img.py#L45

**Comment by adieyal** [comment]
That's a great find. I just tried it out. Process and PostProcess get run before and after a run, regardless of which script is selected. That makes it possible to use dynamic prompts in conjunction with other scripts like X/Y Plot. If a downstream script respects the fact that the prompt could actually be a list, we could use preprocess to generate new prompts from the original prompt.
