### ISSUE TITLE
Custom keywords added by other extensions

### ISSUE THREAD

**Issue by space-nuko** [adieyal/sd-dynamic-prompts#254]
Related to #229, I think it would be easy if there could be a custom keyword syntax. By that I mean, a script could for example add a keyword like `addnet_model_1`, and then if that keyword is found in the prompt, it would set some kind of property. Similar to how XYZ Grid can support other extensions. This would elegantly resolve #229 and allow other extensions to have custom behavior.

Of course the syntax is up in the air, it could be something like `<addnet_model_1:pastelmix-lora>`. The point is that extensions can watch for these tokens and run custom code for them.

**Comment by adieyal** [comment]
Could you elaborate on this a little more? I had a similar idea for #229. The library that drives the extension is [dynamicprompts](https://github.com/adieyal/dynamicprompts). It has no idea of the context in which it runs. In this case settings used by auto1111 to configure stable diffusion. An extension syntax would allows it to parse the prompt, extract the information in the extension tag, and then pass it back to the caller, i.e. the sd-dynamicprompts extension, which would try to handle it.

How would this work with other extensions though? How is this different to simply choosing syntax that doesn't conflict with dynamicprompts and then simply reading the prompt from another extension?

**Comment by space-nuko** [comment]
I actually managed to implement this via my own extension here just now: https://github.com/space-nuko/stable-diffusion-webui-randomizer-keywords.

It taps into webui's extra networks syntax so it's supported without any changes to dynamic prompts. I did need to make this change to webui first though, otherwise the keywords are ignored for subsequent batches: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7789

**Comment by adieyal** [comment]
Fantastic - I'll look through the code later but it's great to see what it can do.
