### ISSUE TITLE
"Reload UI" breaks the extension

### ISSUE THREAD

**Issue by nabileisa** [adieyal/sd-dynamic-prompts#256]
**Describe the bug**

When the extension is enabled and I click `Reload UI` in the settings or `Apply and restart UI` in the extensions
the `Wildcards Manager` tab would disappear and the extension would stops storing the wild card template in generated images. 

Please note that the dynamic prompts accordion remains after the restart and it's features like `magic prompt` still work.

If I close the CLI or exit using `ctrl+z` completely and start from scratch the tab would be restored and everything goes back to working fine .

**To Reproduce**

1. Go to 'Extensions'
2. Click on 'Apply and restart UI'
3. After the UI reloads 'Wildcards Manager' tab  is no longer there

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**
No
If a colab, which one?
None
**Expected behaviour**
The UI reload and the extension would remain the same
**Additional context**

**Comment by adieyal** [comment]
Do you know if this is new - I only noticed it now.

**Comment by nabileisa** [comment]
> Do you know if this is new - I only noticed it now.

I only noticed it recently , but I don't install extensions or change settings often , so it might have been there for a while.

Previously  I only used the extension's other features that are in the accordion but recently I began experimenting with wild cards and that was when I noticed that the wild cards manager tab was not present , after some debugging I figured out  it disappeared when I reloaded the UI.

**Comment by adieyal** [comment]
Could you please test the latest release and let me know how it goes?

**Comment by nabileisa** [comment]
> Could you please test the latest release and let me know how it goes?

After updating the extension and restarting the WebUI , every thing seem to be in order, after trying both `Apply and restart UI` and `Reload UI` , the `Wildcards Manager` tab is present and functional and the template is getting stored correctly.
Thanks for the quick reply and fix and the awesome extension.
