### ISSUE TITLE
Updated, wildcards now linked to seed? (breaks previous usage)

### ISSUE THREAD

**Issue by SwiftIllusion** [adieyal/sd-dynamic-prompts#26]
This is absolutely beyond amazing, thank you so much for its development,
however updating to try and take advantage of the new features has broken my previous usage of the script.

With the wildcards locked to seeds? pressing 'generate' with wildcards now always returns the same result. This is a problem because I took advantage of wildcards primarily because they meant I could find a good seed with the surrounding prompt, but vary it.
For example I could press generate and randomize the characters features with wildcards but hold the rest of their construction.

If this was meant as a 'fix' for it not being locked to the seed before, could this please be returned with a toggle, e.g. 'separate wildcard randomization from seed'.

**Comment by adieyal** [comment]
Thanks - I'm glad you're enjoying it - some of the new features are quite fun. I'm trying to understand the issue that you're experiencing. There are two changes that I made that are relevant to seeds:

1. I have added a checkbox to lock the seed in place. This means you can use **combinatorial** with exactly one seed. It's helpful to explore what various modifiers do without changing the seed. If you're not interested in that, then not checking the box means that it works as before.

2. For random prompt generation, I ensured that if you used the same seed, the same prompt would be generated. Previously, even if the seed was the same, the prompt could be different. It sounds like this might be the issue. 

Is your intent to find new prompts while keeping the seed constant? Why not just use -1 for the seed?

**Comment by SwiftIllusion** [comment]
#1 Yes, the checkbox to lock the seed in is great, because otherwise it would overlap with my issue that has happened as a result of #2, which definitely sounds like the change that broke my previous usage.
How I have been able to take advantage of it, has been getting a seed with regular prompts that are valuable, and then using wildcards to influence the outcome of that seed with randomized elements, for example character appearance wildcards for hair/clothing/traits/colors of all of that.
[This is an example](https://i.imgur.com/biymkoK.png), where I could get one seed that had the nice splash background with prompts, and then the wildcards allowed all the different character appearances. The output of that specific seed is simply impossible to get consistently. I also got another nice background/setup with the same prompts but different seed, that I could then generate with wildcards again-because they were separated from the seed.
But now with them tied to it, I can't do this anymore, so I've had to return to the previous version.
If there was an option to be able to unlink wildcard randomization from the seed, then I could use the new version the same way I did the old one, but take advantage of its new developments.

**Comment by adieyal** [comment]
Can you try 0.13.3. I haven't added a mechanism to change it in the ui yet, but in prompts/constants.py, you can change

    UNLINK_SEED_FROM_PROMPT = False

to

    UNLINK_SEED_FROM_PROMPT = True


You will need to restart the webui for it to work.

I'd like find a way to create a settings section in the settings tab and put the checkbox in there rather than cluttering up the main interface.

**Comment by SwiftIllusion** [comment]
This would be the perfect solution thank you.
However regrettably it doesn't seem to work at the moment. With multiple restarts in-between in-case, I tried with True, and then also just in-case I tried with False, but it was always stuck to the same output.

**Comment by adieyal** [comment]
Apologies - I think it should be fixed now in v0.13.4
