### ISSUE TITLE
Errors on startup, failure to recognize WILDCARD_DIR

### ISSUE THREAD

**Issue by CommanderKinoach** [adieyal/sd-dynamic-prompts#263]
Have updated to most recent build today on A1111's WebUI. I have used both the UI's installation method which created sd-dynamic-prompts and the git pull method which creates dynamic-prompts. Errors on boot:

Error executing callback ui_tabs_callback for StableDiffusion\extensions\sd-dynamic-prompts\sd_dynamic_prompts\ui\wildcards_tab.py
Traceback (most recent call last):
  File "StableDiffusion\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "StableDiffusion\extensions\sd-dynamic-prompts\sd_dynamic_prompts\ui\wildcards_tab.py", line 67, in on_ui_tabs
    available_collections = [str(c) for c in wildcard_manager.get_collections()]
  File "StableDiffusion\venv\lib\site-packages\dynamicprompts\wildcardmanager.py", line 122, in get_collections
    return list(self.get_collection_dirs().keys())
  File "StableDiffusion\venv\lib\site-packages\dynamicprompts\wildcardmanager.py", line 126, in get_collection_dirs
    collection_dirs = [x for x in collection_path.iterdir() if x.is_dir()]
  File "StableDiffusion\venv\lib\site-packages\dynamicprompts\wildcardmanager.py", line 126, in <listcomp>
    collection_dirs = [x for x in collection_path.iterdir() if x.is_dir()]
  File "Python\Python310\lib\pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):

The dynamic prompting area is visible beneath seed selection, but there is no additional tab beyond this.

Upon prompting, "No values found for wildcard 'xxx'" occurs.

My wildcards have always worked stored in the WILDCARD_DIR at the top level of installation. When looking in StableDiffusion\extensions\sd-dynamic-prompts, there is no "wildcards" directory there by default either.

**Comment by adieyal** [comment]
I've updated to the latest version of auto1111 and it works fine on my end. To help with debugging, could you confirm the version of the extension and dynamicprompts? You can find them on the help page of the Dynamic Prompts concertina. Also, can you check the full path of the WILDCARD_DIR, you can find it both on the help page, as well as bullet point #4 on the wildcards tab.

Check that you have the expected wildcard files in that full path.

**Comment by CommanderKinoach** [comment]
"You are using version 2.7.2 of the WebUI extension, and the underlying dynamicprompts library is version 0.7.1."

The WILDCARD_DIR has not moved from the top level location that it has previously worked on: StableDiffusion > WILDCARD_DIR.

**Comment by adieyal** [comment]
Did you change the location of the WILDCARD_DIR in config.json? By default it would be found in extensions/sd-dynamic-prompts/wildcards

**Comment by CommanderKinoach** [comment]
Yes. Removing:
    "wildcard_dir": "WILDCARD_DIR", 
from config.json fixed both the bootup error and the failure to retrieve values.

**Comment by adieyal** [comment]
Not sure what changed - you're not the first person to complain about it breaking, there must have been a change on auto1111 that effected it. 

Can I close this ticket?

**Comment by CommanderKinoach** [comment]
Thank you for the support, please do.
