### ISSUE TITLE
keyerror 'LIB_VERSION'

### ISSUE THREAD

**Issue by Zhalorous** [adieyal/sd-dynamic-prompts#265]
When I launch Stable Diffusion webui I am missing the option for dynamic prompting. Checking the log, here is what I see.
![key lib](https://user-images.githubusercontent.com/125931749/220212413-f38ef8c4-d0f5-4a63-b16e-5ad783109b28.png)

**Comment by adieyal** [comment]
I see you closed this, what was the error?
