### ISSUE TITLE
Problem with wildcards in folders

### ISSUE THREAD

**Issue by acorderob** [adieyal/sd-dynamic-prompts#267]
**Describe the bug**
There seems to be a problem when multiple wildcard files have the same name but are in different subfolders.

The plugin seems to look for the files that contain the specified name in their path, even if they are deeper in the folder structure. And it chooses one of them at random.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Have a file in the main folder (test.txt) with content "one" and another one with the same name in a subfolder (subfolder/test.txt) with content "two".
2. Use __test__ in the prompt and generate.
3. The resulting prompt contains either "one" or "two".

**Are you using a local install or a colab?**
local install

**Expected behaviour**
The filename in the wildcard should be relative to the wildcards folder, so it always uses the correct file.

**Additional context**

**Comment by adieyal** [comment]
That behaviour is expected, see this: https://github.com/adieyal/sd-dynamic-prompts/#fuzzy-globrecursive-wildcard-filedirectory-matching

Some users like to arrange their wildcard structures in a way that allows globbing. If you want to target a specific file then provide the full path to it. You might have trouble targeting a file in the root directory though, I'm not sure if that's possible.

**Comment by acorderob** [comment]
I guess i will have to use unique filenames, but it would be nice to have an option to avoid this problem. For example some kind of simple prefix (like "./") to indicate to look directly under the wildcards folder.
