### ISSUE TITLE
Artists should be restricted to artists recognized by SD

### ISSUE THREAD

**Issue by Yaiol** [adieyal/sd-dynamic-prompts#28]
You tried to be exhaustive with the artists, I understand very well your aim but you fell into the same trap I fall myself some weeks ago when I tried to create SD artits database. The fact is only a very small subset of all artists existing has been used the train Stable Diffusion. The list of artists should be reduced to the one SD has been trained with, otherwise you kinda just produce veru unprecise artist style.

I advice you to read this article
https://waxy.org/2022/08/exploring-12-million-of-the-images-used-to-train-stable-diffusions-image-generator/

Let me take an example I took your french_mannerist_painters list
Ambroise Dubois, Antoine Caron, Francesco Primaticcio, François Quesnel, Luca Penni, Marc Duval, Martin Fréminet, Master of Flora,
Toussaint Dubreuil

I render six images with each of them using that prompt
a deer in the forest by <artist> 
a close-up portrait of a woman by <artist>
an old king by <artist>
merchants in a city by <artist>
a bird on a tree branch by <artist>
the last judgement by <artist>

Here are the kind of result i got

**Duval Marc**
![Duval, Marc](https://user-images.githubusercontent.com/38218161/198934054-364be1e7-4483-4a2c-ae26-a7cb2349b6d2.jpg)
**Dubois, Ambroise**
![Dubois, Ambroise](https://user-images.githubusercontent.com/38218161/198934317-33aae0ef-3df1-44f8-881a-17ef6f1fe03e.jpg)
**Penni, Luca**
![Penni, Luca](https://user-images.githubusercontent.com/38218161/198934096-b7c2830b-698f-4099-b5cc-9c7425b15517.jpg)
**Quesnel, François**
![Quesnel, François](https://user-images.githubusercontent.com/38218161/198934235-d532106d-4b50-44a0-b236-55e13422f018.jpg)

I can tell you SD doesn't know any of those artists style, maybe he knows they are renaissance artists not even but that's all

Now I render the same prompt with renaissance artist I know SD is aware of

**Bellini, Giovanni**
![Bellini, Giovanni](https://user-images.githubusercontent.com/38218161/198934864-0d41253b-6445-4f71-a37c-859631ff1629.jpg)
** Masaccio**
![Masaccio](https://user-images.githubusercontent.com/38218161/198934971-0a4deba1-6a86-412d-be08-4844cdfdfeea.jpg)
**Parmigianino**
![Parmigianino](https://user-images.githubusercontent.com/38218161/198934546-791c399d-504e-4a6f-a91b-4be6dc4a0ba1.jpg)
**van Eyck, Jan**
![van Eyck, Jan](https://user-images.githubusercontent.com/38218161/198934588-83459aa7-e663-42cc-a40a-45204ecc8777.jpg)
**Veronese, Paolo**
![Veronese, Paolo](https://user-images.githubusercontent.com/38218161/198934513-f6fffaa3-b42f-48e4-8f80-72d1c5408a58.jpg)

For your artist lists to be really useful you will need to change your mind and reduce your lists dramatically. From my personal research, so far I have not found more than 50 renaissance artists known from SD and still for certain I have some doubts

Now the question is how .. i'm not aware of any "certified artists" list of SD. Probably the first step is to reduce to the artist list that others found out like the 1800 artists described into the article mentionned above.

Hope this won't kill your day.

**Comment by adieyal** [comment]
Thanks for posting this

Out of the gate I was aware that being overzealous with the tagging would result in the sorts of issues that you mention. In fact, have a look at the pretty exhaustive list of cameras or the various shades of blue, green, etc. Almost certainly they won't all be recognised by SD.

My rationale for proceeding anyway was:
1. Actually figuring out what is and isn't in the database is a non-trivial task, not just artists, but all sorts of other modifiers
2. The tags database is meant to start you off but should by no means restrict users from creating their own custom, and probably much smaller lists
3. We may in future so new models trained with more artists and modifiers in the database so putting in the effort now may be problematic in the long-term.

Also, thanks for the link, I'll give it a read and see if there is anything I can extract from it.

**Comment by jmpaz** [comment]
It's not comprehensive, but [this project](https://proximacentaurib.notion.site/e28a4f8d97724f14a784a538b8589e7d) and [its spreadsheet](https://docs.google.com/spreadsheets/u/0/d/14xTqtuV3BuKDNhLotB_d1aFlBGnDJOY0BRXJ8-86GpA/htmlview#) would be great sources for artists confirmed to have an impact on prompts in SD. I've been meaning to produce some sets of wildcards using this spreadsheet.

The [modifier studies database](https://proximacentaurib.notion.site/2b07d3195d5948c6a7e5836f9d535592) and [csv](https://drive.google.com/drive/folders/1nui_k72U5dDa5EkyUeVrjBCXkx_eTe-Q?usp=sharing) are also well worth a look.

**Comment by Yaiol** [comment]
> 1. Actually figuring out what is and isn't in the database is a non-trivial task, not just artists, but all sorts of other modifiers
Fully agree is the hard work

> 2. The tags database is meant to start you off but should by no means restrict users from creating their own custom, and probably much smaller lists
Yes but I still think would be a great help if we succeed to get an accurate database, maybe i'm dreaming :)

> 3. We may in future so new models trained with more artists and modifiers in the database so putting in the effort now may be problematic in the long-term.
Not sure of this, many artists simply don't have any pictures available to train for any neural network. Try to look for pictures of those artists Ambroise Dubois, Antoine Caron, Francesco Primaticcio, François Quesnel, Luca Penni, Marc Duval, Martin Fréminet, Master of Flora, Toussaint Dubreuil on internet

**Comment by Yaiol** [comment]
> It's not comprehensive, but [this project](https://proximacentaurib.notion.site/e28a4f8d97724f14a784a538b8589e7d) and [its spreadsheet](https://docs.google.com/spreadsheets/u/0/d/14xTqtuV3BuKDNhLotB_d1aFlBGnDJOY0BRXJ8-86GpA/htmlview#) would be great sources for artists confirmed to have an impact on prompts in SD. I've been meaning to produce some sets of wildcards using this spreadsheet.
> 
> The [modifier studies database](https://proximacentaurib.notion.site/2b07d3195d5948c6a7e5836f9d535592) and [csv](https://drive.google.com/drive/folders/1nui_k72U5dDa5EkyUeVrjBCXkx_eTe-Q?usp=sharing) are also well worth a look.

i'm aware of this database they did a great job for evaluating artists (though they are some false positive as well), but the tag is really messy and very inacurate. many artists tagged as renaissance are modern artists, mixing renaissance, baroque, classic ...

**Comment by adieyal** [comment]
Will check it out.

I'm going to leave this issue open. It's a helpful discussion and would be interesting to get inputs from others

**Comment by jmpaz** [comment]
> ... 
> I've been meaning to produce some sets of wildcards using this spreadsheet.

Hi, I've extracted the wildcards from the modifiers study and stored them under subdirectories for modifier strength and tags. Submitted a PR, the Python script is also available here: https://github.com/jmpaz/custom-wildcards/tree/main/modifier-studies

Happy to work on the artist studies later as well.

**Comment by jmpaz** [comment]
Yes nice, seems like a good solution to the issue. I was a bit overwhelmed by the very large new set of mixed, unfamiliar wildcards that I had after merging the currently included set with my existing ones, and wasn't sure how best to tidy them up. This approach seems a nice way to handle that
