### ISSUE TITLE
Error DivideByZero ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by cjps-br** [adieyal/sd-dynamic-prompts#287]
**Describe the bug**
today, after updating the extension, the Divide by Zero error started to appear. I noticed that if I put a space in the negative prompt field, the error doesn't occur, but if I leave the field blank, the error occurs.

![Captura de tela 2023-03-03 163056](https://user-images.githubusercontent.com/75840971/222810002-2bd1aff7-ac29-47f6-a720-ea3e682e8133.jpg)

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to 'text2img'
2. write a positive prompt: "man, walking in new york city"
3. leave negative prompr empty
4. Click on 'Generate'
5. the error occurs
6. go to negative prompt field and press space
7. click on generate
8. the error does not occur

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**
local

**Additional context**
python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [0cc0ee1b] •

**Comment by adieyal** [comment]
Could you please update again to v2.8.1?

**Comment by cjps-br** [comment]
I updated to version 2.8.1 and did a new test. Now it works without the error. Thanks!

**Comment by adieyal** [comment]
I'll leave this issue open for a while in case anyone else encounters the exception
