### ISSUE TITLE
Iterations don't consider batch size

### ISSUE THREAD

**Issue by gruppler** [adieyal/sd-dynamic-prompts#289]
**Describe the bug**
When using a loop with jinja templates, such as `{% for i in range(0, parameters.batch_size) %}`, with batch size 8 and batch count 1, clicking Generate acts as if batch count is 8.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Create a loop with jinja templates
2. Set batch size to something > 1
3. Set batch count to 1
4. Click Generate

Also mention which checkboxes have been set.
- Dynamic Prompts enabled
- Enable Jinja2 templates

**Are you using a local install or a colab?**
Local

**Expected behaviour**
If I'm looping for 8 iterations with batch size 8, I should get one batch.
If I'm looping for 8 iterations with batch size 4, I should get two batches.
If I'm looping for 4 iterations with batch size 8, I should get one batch with two different sets of prompts

**Additional context**
I'm setting some variables before the loop and making some random choices within the loop.

**Comment by adieyal** [comment]
Batch sizes work correct on my end. What is confusing is if I set batch count  to 1, batch size to 4 and prompt to:
```jinja
{% for colour in ['red', 'blue', 'green', 'yellow'] %}
    {% prompt %}I love {{ colour }} roses{% endprompt %}
{% endfor %}
```

I get 16 images produced in 4 batches. Whether it should produce one batch of four or four batches of four is up for debate. Both `batch_count`( called `p.n_iter` in the code) and jinja make decisions about how many images to produce. The code works as follows:

```python
num_images = p.n_iter * p.batch_size
prompts = generate_prompts(num_images)
updated_count = len(prompts)
p.n_iter = math.ceil(updated_count / p.batch_size)

```

Batch size is never changed - DP uses whatever batch size is provided.

The confusing part is how many prompts should be created by `generate_prompts(num_images)`. There are three options:
1. Generate exactly `num_images`  prompts. Depending on your jinja template, you could be generating many more. DP would then pick the first `num_images` and divided by the number of batches.
2. Ignore `num_images` and return as many prompts as are created by jinja, then divide by number of batches
3. The approach currently implemented is produce `num_images * len(num_jinja_prompts)`

I'm not sure which of the three is the least surprising.

**Comment by gruppler** [comment]
In my opinion, #1 is the least surprising.

**Comment by adieyal** [comment]
I think I agree

**Comment by gruppler** [comment]
The downside to this behavior is if your template generates more iterations than `batch_count * batch_size` allows. Maybe the "Generate forever" feature of the webui can serve as a workaround for this use case, if the template loops can persist?

Otherwise, maybe there should just be an option to generate all iterations or limit to `batch_count * batch_size`?

**Comment by adieyal** [comment]
I think having a checkbox to ignore `batch_count * batch_size` makes sense

**Comment by adieyal** [comment]
In v2.8.3 you will find a setting in the settings tab that limits the number of prompts generated to `batch_count * batch_size`. I've decided to leave the default as it was before, in case other users rely on the current behaviour.
