### ISSUE TITLE
[Feature Request] Api support

### ISSUE THREAD

**Issue by richadlee** [adieyal/sd-dynamic-prompts#291]
I think this plugin is great for automating the generation of some random prompt images, so API support is necessary. I hope this feature can be added.

**Comment by adieyal** [comment]
Have you had a look at the [dynamicprompts](https://github.com/adieyal/dynamicprompts) library?

**Comment by richadlee** [comment]
> Have you had a look at the [dynamicprompts](https://github.com/adieyal/dynamicprompts) library?

good library, thx!
