### ISSUE TITLE
camenduru's colab still broken even add this line of code

### ISSUE THREAD

**Issue by jimys** [adieyal/sd-dynamic-prompts#293]
in troubleshot saids add

!python -m pip install -U dynamicprompts[attentiongrabber,magicprompt]

I add this before

!python launch.py --share --xformers --enable-insecure-extension-access --theme dark --gradio-queue --cloudflared

still getting error

Error loading script: dynamic_prompting.py

ModuleNotFoundError: No module named 'sd_dynamic_prompts'

**Comment by adieyal** [comment]
how did you install the extension? From the extensions tab?

**Comment by akx** [comment]
Closing 🧹
