### ISSUE TITLE
Combinations not working when Jinja2 Templates is enabled

### ISSUE THREAD

**Issue by GreenLandisaLie** [adieyal/sd-dynamic-prompts#295]
_(using the latest version as of 07-Mar-23 19:00 GMT, v:1596f556)_

Given this prompt:

`{blue|red}`

By merely enabling Jinja2, the result prompt becomes: `{blue|red}` - as opposed to either 'blue' or 'red'.
(I've not tested yet with wildcard files as I'm not using them yet.)

**Comment by adieyal** [comment]
Jinja works differently, if you want prompts for each of the values, you would use something like:

```jinja
{% for colour in ['blue', 'red'] %}
    {% prompt %} {{ colour }} {% endprompt %}
{% endfor %}
```

if you want to choose one of them randomly then, here is the short version:

```jinja
{{ choice('blue', 'red') }}
```

and the long version:
```jinja
{% for i in range(5) %}
    {% prompt %} {{ choice('blue', 'red') }} {% endprompt %}
{% endfor %}
```

**Comment by GreenLandisaLie** [comment]
You are right. 
I was just being lazy and trying to use regular combinations for simple randomizations (since their format is much simpler) in conjuction with some Jinja2 Templates that can further take in conditions based on the model name, etc.

I once ran my own amateurish snippet code for diffusers SD pipelines which contained a function that would accept combinations, wildcards from files and even extremely simple 'if x in prompt' statements. It ran inside a loop that would check for each of these in a specific order and only when no more were found it would jump to the next one until only a regular, working prompt was left.
I was the impression your code would do something somewhat similar - in which case - Jinja2 priority should be at the lowest.

Anyways, its true you don't really need to use regular combinations with Jinja2 since it can do all that on its own, so I'll be closing this issue now.
Thank you and sorry for your time.
