### ISSUE TITLE
Jinja2 Templates should run when combinations/wildcards are no longer in the prompt

### ISSUE THREAD

**Issue by GreenLandisaLie** [adieyal/sd-dynamic-prompts#297]
_(using the latest version as of 07-Mar-23 19:00 GMT, v:1596f556)_

Given this prompt:

```
{blue|red}

{% if "red" in prompt.prompt %}
    flower
{% else %}
    rose
{% endif %}
```

With Jinja2 activated (edit: and 'ignore whitespace'), the resulting prompt should be either `blue rose` or `red flower`.

Current behaviour: `if "red" in prompt.prompt` always returns true and so the prompt will always have 'flower' and never 'rose'.

Please dismiss this issue if this is actually intentional - it doesn't make sense to me but that's just my personal opinion.

**Comment by adieyal** [comment]
That's expected behaviour. Why not rather use something like this instead

```jinja
{% if choice('red', 'blue') == 'red' %}
    flower
{% else %}
    rose
{% endif %}
```
