### ISSUE TITLE
Error with wildcard_wrap

### ISSUE THREAD

**Issue by bport98** [adieyal/sd-dynamic-prompts#299]
I got this error in A1111 in Colab using this in my prompt: [Nata Lee|Michelle Monaghan]

Error running process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 357, in process
    parser_config = ParserConfig(
TypeError: __init__() got an unexpected keyword argument 'wildcard_wrap'

**Comment by adieyal** [comment]
Could you make sure you have a latest version installed? In the help section, you will see two versions, one for the extension and one for the library. They should be 2.8.4 and 0.10.2 respectively

**Comment by Griever158** [comment]
Hi. I'm running 2.8.4 and getting the same error yesterday. Did a complete re-install and it worked fine yesterday, this morning the error popped up again.

**Comment by adieyal** [comment]
can you verify that the dynamicprompts library installed is v0.10.2?

**Comment by Griever158** [comment]
I'm so sorry, I looked around for the 'help' section you mentioned earlier but couldn't find where the version number for the dynamic prompts library is. Where could I verify that for you? The Changelog.md file only lists the extension version.

**Comment by adieyal** [comment]
It's under the Need Help? section - see the highlighted section in this screenshot:

![Screenshot from 2023-03-08 12-30-42](https://user-images.githubusercontent.com/420786/223689477-aef1f095-7dc1-4821-9e09-6d0c83f1f46f.png)

**Comment by Griever158** [comment]
I see my version is out of date. How can I update the library?
![image](https://user-images.githubusercontent.com/45467804/223700061-0e8cbff0-c8c6-4eb4-969c-f5e945baaea2.png)

**Comment by adieyal** [comment]
It should update automatically when you restart the webui - if it doesn't for some reason (please let me know), then you can manually update it with `python -m pip install --upgrade dynamicprompts` - depending on your installation, you may need to run something like `venv/bin/python -m pip install --upgrade dynamicprompts`

**Comment by Griever158** [comment]
I'm running Automatic 1111 via Google Colab ([TheFastBen's](https://github.com/TheLastBen/fast-stable-diffusion)), same as OP. I think this might be an issue with the Colab not updating properly. I deleted the entire extension and re-installed it again as we don't have access to the terminal to run python commands. It seems to have updated to the current build. 
![image](https://user-images.githubusercontent.com/45467804/223704964-db92608d-12f0-449f-ab3b-2ee56bc3bc66.png)

**Comment by adieyal** [comment]
Good to hear. 

btw, in colab, you should be able to run terminal commands by adding `!` as a prefix, e.g. `!python -m pip install --upgrade dynamicprompts`
