### ISSUE TITLE
GRadio error on launch due to extension: UserWarning: You have unused kwarg parameters in Button, please remove them: {'full_width': True}

### ISSUE THREAD

**Issue by CCpt5** [adieyal/sd-dynamic-prompts#300]
On A1111 launch I'm getting the following error. I went one by one moving out extensions from my extension folder and I had 3 different extensions that cause this, but SD-Dynamic-Prompts is one (pops up when it's the only extension in the extension folder / doesn't when i remove it). I have had some issues w/ SD failing to get to running on local URL (aka start) before crashing the past week. I think this error could be related. Please review if possible.

And thanks so much for all of your work - excellent extension - really appreciate it!

Here's what happens when I launch A1111 when the only extension I have in the folder is SD-Dynamic-Prompts (sometimes it doesn't get to the running part and I have to reopen it and try again - eventually it goes):

**To Reproduce**
1. Make sure "Show warnings in console." is toggled in the A1111 settings (System tab)
2. Launch webui-user.bat
3. Look for "you have unused kwarg parameters in tab" etc

Also mention which checkboxes have been set.

Local install

If a colab, which one?

**Expected behaviour**
No errors on launch. Once in the application (after I run the BAT a few times and it eventually runs on the local URL) I haven't notcied any issues w/ the extension. 

**Additional context**
I am getting this error with Control Net and GIF2GIF also. Here is a copy/paste of my console when SD-Dynamic-Prompts is the only extension in my A1111 extension folder:

----

venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Installing sd-dynamic-prompts requirements.txt

Launching Web UI with arguments: --xformers --api --ckpt-dir e:\Stable Diffusion Checkpoints
Loading weights [396c3fd2fa] from e:\Stable Diffusion Checkpoints\2022-12-29 - Topnotch 8 - (Topnotch Artstyle) - 36img contd of 7 - 7000 steps - (50img to 4000steps + 36img to 3000).ckpt
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 2.3s (load weights from disk: 0.4s, create model: 0.2s, apply weights to model: 0.2s, apply half(): 0.3s, load VAE: 0.1s, move model to device: 0.3s, load textual inversion embeddings: 0.6s).
C:\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Button, please remove them: {'full_width': True}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

My versions:

python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)  •  checkpoint: [396c3fd2fa](https://google.com/search?q=396c3fd2faa17b989bd28d73ecb461826199684383c922b38b867d4ab12d92e9)

**Comment by CCpt5** [comment]
Deleted my Venv folder and had everything resinstall. Not seeing this error now, so may have been a local issue. If I get it again and can confirm it's not something related to my setup I'll open a new issue.

Thanks again

**Comment by aibaby1991** [comment]
Suggest edit
wildcard_tab.py
line 97
#             full_width=True,
I try it, it may help!
Thank you
K Lam
