### ISSUE TITLE
Prompts do not randomise between batches

### ISSUE THREAD

**Issue by BunnyViking** [adieyal/sd-dynamic-prompts#31]
version 7cfd16eb26e789456e751f1078df139e4b624264

expected: using a `__filename__` should randomise per batch

actual: it does not

similarly `{prompt1|prompt2|prompt3}` will not randomise per batch

**Comment by adieyal** [comment]
Does this issue addresses this: https://github.com/adieyal/sd-dynamic-prompts/issues/26?

**Comment by BunnyViking** [comment]
That was rediculously quick :D I was about to resolve the issue... it isn't that it doesn't randomise, it's simple that for whatever reason Gradio displays the same prompts.. the filename and and PNG info are both correct.

**Comment by BunnyViking** [comment]
Is a visual Gradio issue, it's working as intended.
