### ISSUE TITLE
This extension seems to be hijacking CTRL+ENTER in the A1111 img2img tab.

### ISSUE THREAD

**Issue by Alchete** [adieyal/sd-dynamic-prompts#315]
With this extension enabled, CTRL+ENTER stops working in A1111 img2img.  Instead, SHIFT+ENTER works.

Disabling this extension results in CTRL+ENTER again working normally in img2img  Behavior confirmed by multiple people.  

Is this extension doing anything that could affect CTRL+ENTER?

**Comment by akx** [comment]
Closing because no further information - and this extension indeed does not touch keybinds.
