### ISSUE TITLE
How to use emuneration?

### ISSUE THREAD

**Issue by aniketgore** [adieyal/sd-dynamic-prompts#32]
I saw in the notes that i can use 
If a __wildcard__ is provided, then a new prompt will be produced for every value in the wildcard file. For example: My favourite season is __seasons__

will produce:

My favourite season is Summer
My favourite season is August
My favourite season is Winter
My favourite season is Sprint

But this doesn't work. I tried using combination number, batch number, as well as * but it justs picks the things randomly from the file.

I think it should work like below

file contains 3 colors
red
black
white

my favorite color is __MyColor__ (Some modifier) and it should give me 3 images with

my favorite color is red
my favorite color is black
my favorite color is white

**Comment by adieyal** [comment]
Have you checked the **Combinatorial Generation** checkbox? To help you understand what's happening in the back-end, there are two main prompt generators, a `RandomPromptGenerator` and `CombinatorialPromptGenerator`. The first is what you're probably familiar with, you give it a prompt template, tell it how many batches, and how many image per batch, and it generates that number of randomly generated prompts using the prompt template..

`CombinatorialPromptGenerator` isn't random it all. It produces every possible variation that it can, as in your examples above. To enable it, you check the combinatorial box. **Combinatorial batches** is a newly-requested feature. If you set it to 2, it will run as follows:

    my favourite color is __MyColor__

my favorite color is red (seed 1)
my favorite color is black (seed 2)
my favorite color is white (seed 3)

my favorite color is red (seed 4)
my favorite color is black (seed 5)
my favorite color is white (seed 6)

Does that help?

**Comment by aniketgore** [comment]
Prompt was :
__style\genre__

**Comment by aniketgore** [comment]
__ style\genre __

**Comment by adieyal** [comment]
I think I understand what you're seeing. I made a change recently to remove duplicates, i.e. you shouldn't get American frontier twice. The deduplication makes the order unpredictable, i.e. it will pick any two from your file. If you file has ten genres in it and you set your batch count to ten, it should use every one of the genres once.

Could you confirm that's the case?

**Comment by aniketgore** [comment]
Yes, that's working like that. Thanks for the clarification.
