### ISSUE TITLE
Combination variant's 'weights' are taken in as literals when new line separated with 'ignore whitespaces'

### ISSUE THREAD

**Issue by GreenLandisaLie** [adieyal/sd-dynamic-prompts#324]
With ignore whitespaces enabled this works:

```
{
# 50% A
A
|
# 50% B
B
}
```

This also works:
```
# 60% A 40% B
{0.6::A|0.4::B}
```

But this does not work:
```
{
# 60% A
0.6::A
|
# 40% B
0.4::B
}
```

In the last example I'm getting the combination variant's 'weights' as literals, ex: `0.6::A.`
This is a very minor issue that can be bypassed by simply removing new lines but doing that on very complex combinations hurts the eyes. 
(sorry if its a duplicate - its so obvious I can't be the first one to point it out but I couldn't find any issue on this)

**Comment by GreenLandisaLie** [comment]
I changed a line in requirements.txt to 'dynamicprompts[attentiongrabber,magicprompt]==0.10.6' to try out that commit and the problem has been solved.
However its still not working properly within wildcardfiles - I didn't want to open a new issue and since it's related I'll post here.

See this example wildcard file for danbooru hair styles:

```
{
# just size - 35%
0.35::{0.25::{0.75::long|0.25::very long}|0.25::medium|0.5::short} hair
|
# ponytail - 10%
0.1::{0.2::side|0.2::high|0.2::short|0.4::} ponytail
|
# twintails - 10%
0.1::{0.25::low|0.25::short|0.5::} twintails
|
# braids - 5%
0.05::{0.3::twin braids|0.3::side braids|0.2::single braid|0.2::braid}
|
# buns - 5%
0.05::{0.6::double bun|0.4::single hair bun}
|
# drill - 10%
0.1::{drill hair|twin drills}
|
# curly - 10%
0.1::curly hair
|
# misc - 15%
0.15::{0.1::messy|0.3::spiky|0.2::tentacle|0.1::asymmetrical|0.3::antenna} hair
}
```

It works if I add that straight to the prompt but calling it from a wildcard file it still gives me the weights as literals. However not all of the weights - just the first ones, ex result: `0.35::long hair`

**Comment by adieyal** [comment]
This was fix in one of the recent updates
