### ISSUE TITLE
Prevent Attention Grabber from grabbing attention in LoRA/other model references

### ISSUE THREAD

**Issue by adieyal** [adieyal/sd-dynamic-prompts#327]
### Discussed in https://github.com/adieyal/sd-dynamic-prompts/discussions/318

<div type='discussions-op-text'>

<sup>Originally posted by **gaharatek** March 20, 2023</sup>
Hello! I'm not sure if this is right place to ask for this, i wanted to make an issue first, but decided that it's not really a groundbreaking bug.

I would like to ask about adding a check mark in attention grabber to ignore Lora's syntax, because most of the time you want Lora weight at fixed value.

Current behavior of this feature trying to add attention to Lora in prompt in different variations.

Examples:

original prompt is `<lora:loraname:0.7>`

> when using attention grabber

`<(lora:1.42):loraname:0.7>`
`<lora:(loraname:0.7:1.1)>`

It would be great to have option for attention grabber to ignore Lora's.</div>

**Comment by gaharatek** [comment]
Hello! Seems like everything working fine.
Tested on commit c000db9
with WebUI commit https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
since it seems like it's a little bit risky to update right now.

Thank you very much for your work!
