### ISSUE TITLE
__textfile__ not working

### ISSUE THREAD

**Issue by visjble** [adieyal/sd-dynamic-prompts#33]
I tried to install by terminal and also via extensions in Gradio by it's not taking any `__textfile__` . I do have them in the wildcards folder downloaded by git.
Ubuntu 20

**Comment by visjble** [comment]
installing via extensions and via git creates two different directories

**Comment by adieyal** [comment]
Could you explain exactly what happened and how you fixed it so that I can add it to the README?

**Comment by visjble** [comment]
I removed all the folders and only used the extention option from Gradio to install
