### ISSUE TITLE
Adding items in wildcard manager adds extra blank line after each item

### ISSUE THREAD

**Issue by Jonseed** [adieyal/sd-dynamic-prompts#340]
**Describe the bug**
Just what the title says

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to Wildcard Manager
2. Click on a wildcard
3. Add an item to the file
4. Save wildcard
5. See the wildcard file has extra line in between each item.

**Are you using a local install or a colab?**
local

**Expected behaviour**
No extra lines to be added

**Additional context**
Each time new items are added, extra lines are added.

**Comment by crackfoo** [comment]
duplicate:

https://github.com/adieyal/sd-dynamic-prompts/issues/270

**Comment by Jonseed** [comment]
didn't see it was already an issue...
