### ISSUE TITLE
Dynamic Prompts does nothing more

### ISSUE THREAD

**Issue by XT-404** [adieyal/sd-dynamic-prompts#344]
The bug is the following, the extension and taken into consideration under stable release 1.5
no error in the log Webui.bat
the text files in Wildcards are well present and taken into account
on the other hand when one notifies something example: 1girl or __ or < 
nothing happens, it is still active and present in the webui interface

I install here a screenshot,

![dynamic 04](https://user-images.githubusercontent.com/128090530/227999666-9dbc6302-6657-4696-98c9-b629d49a4f7a.png)
![dynamic 01](https://user-images.githubusercontent.com/128090530/227999674-0f80b267-672a-4157-873a-7e794c3189dc.png)
![dynamic 02](https://user-images.githubusercontent.com/128090530/227999676-1291cbd2-c435-4010-9f67-68d5beb696a7.png)
![dynamic 03](https://user-images.githubusercontent.com/128090530/227999678-aaf7824a-4138-43c1-bb34-bdf527cf8a63.png)

**Comment by adieyal** [comment]
Could you confirm with version of auto1111 you're on? Recent changes have broken some functionality.

**Comment by XT-404** [comment]
hello I confirm that I am using the latest version 1.5 of auto1111

**Comment by adieyal** [comment]
in your terminal, run this command `git show -s`

you should see something like
```
commit 33b85391474098b021946a5f1d8e07f8a6d27aa2 (HEAD, tag)
```

what is the commit number that you're using

**Comment by XT-404** [comment]
how to do it ????

**Comment by XT-404** [comment]
commit 33b85391474098b021946a5f1d8e07f8a6d27aa2 (HEAD, tag)

**Comment by XT-404** [comment]
I don't know anything about computers so you're asking me something from the future lol

**Comment by adieyal** [comment]
no worries.
I'm making the assumption that you are using windows

Use your file explorer to find the directory where you installed auto1111. Then, according to this [stackoverflow question](https://stackoverflow.com/questions/60904/how-can-i-open-a-cmd-window-in-a-specific-location), you press shift + right click on the folder icon and click on the "Open command window here". That should open up a terminal. In it, type `git show -s` - hopefully it will output the commit hash which will look something like what I pasted above.

**Comment by XT-404** [comment]
Commit hash: 955df7751eef11bb7697e2d77f6b8a6226b21e13 here ?

**Comment by adieyal** [comment]
Let's test if it works with an older version auto1111, type this command in the terminal:

`git checkout 33b85391`

then restart the webui.  If it works, then it means that the recent changes to auto1111 have broken dynamic prompts. While we fix it, you can either use this older version of auto1111 ( 7 days old)  or use the most recent version of auto1111 and wait for DP to be fixed.

to get back to the latest version run this command

`git checkout master` 

then restart

**Comment by XT-404** [comment]
ok i go tested

**Comment by XT-404** [comment]
it does not work even with the ask action which worked well
![image](https://user-images.githubusercontent.com/128090530/228081935-41e16c3b-1163-4f86-a8f9-b348bb2e275b.png)

**Comment by XT-404** [comment]
![image](https://user-images.githubusercontent.com/128090530/228082125-91c33bba-00b3-4cdc-a629-98637a6820f9.png)

**Comment by XT-404** [comment]
it refuses to revert to the latest version :/

**Comment by XT-404** [comment]
I managed to return to the new version and indeed the text files are no longer taken into account on the new version, all and KO
![image](https://user-images.githubusercontent.com/128090530/228082562-71f9cc4b-1ff2-455a-9f86-b393e86e2725.png)
![image](https://user-images.githubusercontent.com/128090530/228082634-9045d646-38ed-4350-9b70-f0103545c572.png)

**Comment by XT-404** [comment]
![image](https://user-images.githubusercontent.com/128090530/228082753-b7283fad-aa95-4b2d-8099-996256e55a6a.png)
refresh > error

**Comment by adieyal** [comment]
> I managed to return to the new version and indeed the text files are no longer taken into account on the new version, all and KO ![image](https://user-images.githubusercontent.com/128090530/228082562-71f9cc4b-1ff2-455a-9f86-b393e86e2725.png) ![image](https://user-images.githubusercontent.com/128090530/228082634-9045d646-38ed-4350-9b70-f0103545c572.png)

It wasn't clear from your posts whether or not it worked with the older commit. The error you see above is not related to dynamic prompts as far as I can tell.

**Comment by XT-404** [comment]
Then it is simple that this silk on the old version or the new version of stable diffusion more nothing functions 
on the old version the texts in wildcards are well found
what is not the qu'a in the new version
and the auto prompts does not work absolutely any more in the new, or old version

**Comment by adieyal** [comment]
I'm sorry, I don't understand your comment. Could you please write it again
in another way?

**Comment by XT-404** [comment]
at worst I add you on discord I make you a live streaming
that there is nothing complicated 

new or old version
dynamic prompts and KO 
nothing works anymore 
it's simple, fast, clear and efficient 
the only thing that works on dynamic prompts on the old version
and the detection of TEXT files in the wildcards directory,
nothing else, on the new version it does not detect anything at all.

**Comment by FLi79Za** [comment]
I think what XT-404 is trying to say is that the Dynamic Prompts\Wildcards Manager tab doesn't do anything in the Auto1111 GUI. It doesn't enumerate the custom made wildcards, nor does it allow you to open, read or modify any of the included txt files in the folder. I see this on my Auto1111 as well which has the latest updates. I haven't tested on the older branch of Auto1111, but I believe just typing in the name of the file in the text field might actually work.

**Comment by adieyal** [comment]
I'm aware of the issue. Unfortunately the new version of auto1111 is
completely broken on my machine so I can't fix it until I get my webui up
and running again. Until it's fixed you'll need to choose between an older
version of auto1111 or a broken wildcards manager.

**Comment by XT-404** [comment]
thx :)

**Comment by adieyal** [comment]
Great, I'll merge it into the main branch
