### ISSUE TITLE
Store the wildcard option as a comment

### ISSUE THREAD

**Issue by JingJang** [adieyal/sd-dynamic-prompts#347]
Store the wildcard options in the image metadata after genetation. Currently it removes the wildcard from image metadata.

So it should appear in the prompt but gets extracted before generating image, but details are stored back in the image metadata after generation. The wildcard used for generating the image is also shown, so one can recreate the exact image. 

I do not know if that is possible, but I thought it is worth asking. Maybe allow a comment out like one does in programming i.e. // or ::: or rem at start of line.

**Comment by tusharbhutt** [comment]
Isn't it already there?

![image](https://user-images.githubusercontent.com/26264462/230208544-e0ac006e-b0f5-441d-a463-62217e850a73.png)

**Comment by adieyal** [comment]
@JingJang, does @tusharbhutt's response address your question?

**Comment by JingJang** [comment]
Sorry for late reply. No it does not. 

It stores parameters but not the wildcard for dynamic prompts. So for example:

`So young child with { blonde | blue | red } hair squatting infront of a cat`

May end up like this in the metadata

`So young child with blonde hair squatting infront of a cat`

So basically I want to store the actual prompt and the one used for output. Not sure if it is possible, but worth a shot asking.

**Comment by rjgoif** [comment]
@JingJang, I think the "template" text is what you're asking for. 
@tusharbhutt attached a screenshot with the template text stored with the image. Is that different from what you expect?

**Comment by JingJang** [comment]
Yeap. I am  not sure if it is new or was added but the issue is fixed.
