### ISSUE TITLE
Not showing up in the UI

### ISSUE THREAD

**Issue by Extraltodeus** [adieyal/sd-dynamic-prompts#35]
Hello!

While I do have it installed (used the git clone command into my extension directory) and it shows up in the extensions tab :
![image](https://user-images.githubusercontent.com/15731540/199382876-326cab08-b65e-47f5-a66d-02ad7ed69444.png)

It does not show anywhere else in my UI. No tab no extra option in the settings, nothing.

I am using a fresh colab so it is not due to residual files.

Best regards,

**Comment by adieyal** [comment]
Does it not appear in the scripts dropdown?
![Screenshot from 2022-11-02 13-12-15](https://user-images.githubusercontent.com/420786/199475535-dbe57ce0-27fb-4b10-821b-93b8d9aa8a89.png)

**Comment by Arhadrianman10** [comment]
i cannot see in the dropdown
![image](https://user-images.githubusercontent.com/86854034/199513325-9ae9a65e-1b9e-4b96-93a1-da216385be83.png)
![image](https://user-images.githubusercontent.com/86854034/199513394-3a30c3ea-34bc-408d-b9cb-06d3aae69e01.png)

**Comment by adieyal** [comment]
I don't get the extensions tab in my webui - how do you enable it?

**Comment by Extraltodeus** [comment]
Do you use the argument --allow-code? That might be what enables it.

Note that if you're using --share you can not install extensions from the tab since it would allow a potential session hijacker to install whatever they want on your session. No way to disable that safety feature for now.

**Comment by Extraltodeus** [comment]
Oh well when the UI loads up I get that message :
![image](https://user-images.githubusercontent.com/15731540/199587199-c7baeaec-bc6e-433b-81c2-c5d99b80ddbb.png)

So this must be the reason (fresh colab install as always)

**Comment by adieyal** [comment]
looks like you're using python <= 3.8 - could you test this branch and let me know if that fixes it: https://github.com/adieyal/sd-dynamic-prompts/tree/python3.8-compatibility

**Comment by Extraltodeus** [comment]
Trying right now

**Comment by adieyal** [comment]
Could you try this branch again? https://github.com/adieyal/sd-dynamic-prompts/tree/python3.8-compatibility

**Comment by Extraltodeus** [comment]
![image](https://user-images.githubusercontent.com/15731540/199741776-d2d9b8d4-f9aa-45d6-b726-4af5266427fc.png)

**Comment by Extraltodeus** [comment]
The exact python version is :
Python 3.8.13 (default, Oct 21 2022, 23:50:54)

**Comment by adieyal** [comment]
0.13.7 on the main branch should now work

**Comment by Arhadrianman10** [comment]
working from my site! Thanks

![image](https://user-images.githubusercontent.com/86854034/199930256-827b0413-56e8-4fe1-8610-0b12500a36d9.png)

**Comment by Extraltodeus** [comment]
It works for me now! Thank you.
