### ISSUE TITLE
ModuleNotFoundError: No module named 'dynamicprompts.wildcards'

### ISSUE THREAD

**Issue by aidemengxin** [adieyal/sd-dynamic-prompts#353]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to 'stable-diffusion-webui'
2. Click on 'webui.bat(Python 3.10.8)'
3. Scroll down to 'Running on local URL:  http://127.0.0.1:7860'

<img width="902" alt="屏幕截图 2023-03-29 220046" src="https://user-images.githubusercontent.com/129300273/228567170-18d2c607-65bf-417d-90ab-1e1ac69e92b7.png">

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**
- a local webui install 
- Installing sd-dynamic-prompts requirements.txt

If a colab, which one?

**Expected behaviour**
- Unable to use dynamic prompts due to an error
- Want to be able to use dynamic prompts

**Additional context**

**Comment by adieyal** [comment]
trying running `python -m pip install dynamicprompts==0.20.1` and let me know if that fixes it

**Comment by LozyLL** [comment]
same issue here.
Try installing 0.20.1, but it reports this 
![6~GBZ 88B03 AF~90K{37Q8](https://user-images.githubusercontent.com/126636908/228746678-d80c778a-456b-4259-a62b-a45d0eca033e.png)

**Comment by adieyal** [comment]
Try `python -m pip install dynamicprompts==0.20.1 ` instead

**Comment by aidemengxin** [comment]
any directory `python -m pip install dynamicprompts==0.21.0 `
Problems remain

**Comment by adieyal** [comment]
Have a look in the Need Help? accordion for the version of dynamicprompts you have installed. If it's lower than 0.21.0 then it is too old. Try completely restarting webui, i.e. stop the progam entirely and then start it again

**Comment by aidemengxin** [comment]
**Thank you** for your reply, I'm **sorry** to trouble you.

"I don't know how to program, so I don't understand the problem. It may be a problem with computer hardware compatibility, etc. I just hope that in the future I can use the" Dynamic Prompt "extension.

I just tried again and the problem remains:

1. c:\ 'python -m pip install dynamicprompts==0.21.0'

2. Install the "Dynamic Prompt" extension in the Web UI

3. Restart the Web UI result Error

<img width="563" alt="屏幕截图 2023-03-30 204314" src="https://user-images.githubusercontent.com/129300273/228842544-a43635e8-8dd9-4685-8a14-50f6bcbb6905.png">
<img width="1718" alt="屏幕截图 2023-03-30 201903" src="https://user-images.githubusercontent.com/129300273/228842690-83d85e35-80bf-49bd-8648-6ef7e754fe65.png">

**Comment by akx** [comment]
Your webui may be using a separate virtualenv than the base Python 3.10 you're using.

If it's the default configuration, you can try

```
cd f:\ai\stable-diffusion-webui-aki-v3
venv\scripts\activate
pip install -U dynamicprompts
```
to upgrade the copy of dynamicprompts within that venv.

**Comment by charliesxia** [comment]
> It has something to do with your **mirror**, you can
> 
> 1. download the whl file from [pypi](https://pypi.org/project/dynamicprompts/#files), then install it:
> 
> ```
> {python environment path}\python.exe -m pip install  {file directory}\dynamicprompts-0.21.2-py3-none-any.whl
> ```
> 
> 2. try other mirror
> 
> ```
> {python environment path}\python.exe -m pip install dynamicprompts==0.21.2 -i https://mirrors.aliyun.com/pypi/simple/
> ```

great ,it works thank you

**Comment by adieyal** [comment]
@charliesxia can we close this issue?

**Comment by akx** [comment]
Closing.

**Comment by Justlove-dk** [comment]
> Your webui may be using a separate virtualenv than the base Python 3.10 you're using.
> 
> If it's the default configuration, you can try
> 
> ```
> cd f:\ai\stable-diffusion-webui-aki-v3
> venv\scripts\activate
> pip install -U dynamicprompts
> ```
> 
> to upgrade the copy of dynamicprompts within that venv.

i do not fain this file,why?
thanks

**Comment by Justlove-dk** [comment]
> It has something to do with your **mirror**, you can
> 
> 1. download the whl file from [pypi](https://pypi.org/project/dynamicprompts/#files), then install it:
> 
> ```
> {python environment path}\python.exe -m pip install  {file directory}\dynamicprompts-0.21.2-py3-none-any.whl
> ```
> 
> 2. try other mirror
> 
> ```
> {python environment path}\python.exe -m pip install dynamicprompts==0.21.2 -i https://mirrors.aliyun.com/pypi/simple/
> ```

i have a question
how to install the whl file,input the whl to which file
please help

**Comment by adieyal** [comment]
I would guess that you download the file from this [link](https://pypi.org/project/dynamicprompts/#files)
then in  your terminal write `python -m pip install dynamicprompts-0.25.2-py3-none-any.whl`

if you still get an error message, you might  not be using the correct python.exe. You can find the path to the right one in the error message  you get in the webui terminal. It will look something like `C:\Users\(Your logged in User)\AppData\Local\Programs\Python\Python310` (but not that necessarily).

_[**Note** for anyone in future seeing this issue - the link to the current version 0.25.2 is current as of now, but will almost certainly be different in future]._
