### ISSUE TITLE
Nested wilcards with $$ syntax is broken

### ISSUE THREAD

**Issue by tpsjr7** [adieyal/sd-dynamic-prompts#358]
**Describe the bug**

Nested wildcards seems broken when combined with `{2$$__some-wildcard__}` syntax.

**To Reproduce**
animal.txt contains a list of animals
color.txt contains a list of colors
custom.txt contains
```
__animal__
__color__
```

If you try
`{2$$__custom__}` then it erroneously ends up resolving to `__animal__,__color__` for instance instead of fully recursively resolving to 
"cat,red" as it used to behave.

When I try `__custom__` by itself without `$$` syntax, it does fully recursively resolve to "cat" for example as expected.

Also mention which checkboxes have been set: None

**Are you using a local install or a colab?**

local install

**Expected behaviour**

`{2$$__custom__}` should fully resolve to "cat,pink" for instance instead of `__animal__,__color__`

**Additional context**
This worked while i was on the 10c9006c Jan 27 commit, and broke when I updated today to 59f44e935 commit.

**Comment by Bonedragon1300** [comment]
I am also getting this, really annoying with how much I use this for colors

**Comment by adieyal** [comment]
Could you please confirm your version of the dynamicprompts library? You can find it on the Need Help? Accordion.

**Comment by tpsjr7** [comment]
"You are using version 2.10.0 of the WebUI extension, and the underlying dynamicprompts library is version 0.21.0. "

**Comment by Bonedragon1300** [comment]
same

**Comment by adieyal** [comment]
I've submitted a pull request (https://github.com/adieyal/dynamicprompts/pull/69), once it's approved then it will be publish.

**Comment by tpsjr7** [comment]
sweet, thanks.

**Comment by Bonedragon1300** [comment]
still getting that problem on my end
