### ISSUE TITLE
wildcard_manager UI lost. Maybe I've found the cause. but...

### ISSUE THREAD

**Issue by vaclav-kyle** [adieyal/sd-dynamic-prompts#362]
Sorry first. I'm not good at English, so the writing can be a bit messy. I'll try to be a detailed explanation, but it can be difficult to understand, so please refer to it.

Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 14, in <module>
    from dynamicprompts.wildcards import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts.wildcards'

Yeah... Same error. I lost my UI too.
I checked and it seems that this is an error that only appears in the colab web UI.
ah! Not exactly that. To be precise, when this error pops up in the colab web UI, I can't fix it myself.
Because, I can't access the \venu\ folder hidden inside the web UI folder.

Ever since the problem started, I've been thinking about what could be the cause. I'm not an expert at reading scripts. But just in case, I perused the script.
Even though it said it couldn't find a module called wildcard manager. I think I went through all the folders to find this manager module. there was no
So, I finally installed it on my PC and looked for it.
stable-diffusion-webui\venv\Lib\site-packages\dynamicprompts\wildcards\ is in this path. as a Python file. Unfortunately, I can't access this folder from the Colab WebUI.
![화면 캡처 2023-03-30 211742](https://user-images.githubusercontent.com/128915381/228833543-348587e2-a818-4e9a-b514-1ce231950026.png)
If possible, could you set up a code that can separately apply only the Python files related to the wildcard manager UI?

-ps. This article was written by Teacher Goo (**Goo**gle Translate).  It was a pops style gag.

**Comment by akx** [comment]
This is the same problem as #353; we changed things in the `dynamicprompts` library this extension uses, and you haven't updated it.

You can try `!pip install -U dynamicprompts` in your Colab.

**Comment by vaclav-kyle** [comment]
> !pip install -U dynamicprompts

![화면 캡처 2023-03-31 015234](https://user-images.githubusercontent.com/128915381/228909197-ca648742-fdef-4a67-a40c-dc46febd61e9.png)
I tried, but it doesn't get any better.
![화면 캡처 2023-03-31 015255](https://user-images.githubusercontent.com/128915381/228909271-5f932c4f-2ef9-456d-902b-90ffbe67fada.png)
After completely shutting down colab, I installed it before pressing the "Start Stable-Diffusion" button while restarting, but it's still the same.

**Comment by adieyal** [comment]
could you share the colab so that I can take a closer look?

**Comment by akx** [comment]
I forgot to mention you need to restart things after the upgrade.

Glad you got it sorted out!
