### ISSUE TITLE
Nested Wildcards aren't triggering 

### ISSUE THREAD

**Issue by Bonedragon1300** [adieyal/sd-dynamic-prompts#368]
**Describe the bug**
Nested Wildcards aren't triggering. log says "No values found for wildcard "nested wildcard""

![Capture](https://user-images.githubusercontent.com/15267401/229236575-a1f73a20-fe36-469c-89f0-b38cfdef05af.PNG)

**To Reproduce**
link another wildcard in a wildcard 

![Capture](https://user-images.githubusercontent.com/15267401/229236021-b9f63ef4-af54-4169-b0f8-095bbc742620.PNG)

![Capture](https://user-images.githubusercontent.com/15267401/229236507-f9a4da3b-6d66-48ec-8c40-9922ae96f200.PNG)

**What version of the extension and dynamicprompts library do you have installed?**

You are using version 2.10.3 of the WebUI extension, and the underlying dynamicprompts library is version 0.21.2.

**Are you using a local install or a colab?**

Local install

**Expected behaviour**
that the nested wildcard would trigger an normally

**Additional context**

**Comment by adieyal** [comment]
I can re-create this only if I don't use the full path to the nested wildcard, for example from the jumbo collection, this wildcard doesn't work `__jumbo/creatures/adnd__` because the file looks like this:
```
__creatures/adnd/aberration__
__creatures/adnd/beast__
__creatures/adnd/celestial__
__creatures/adnd/construct__
__creatures/adnd/dragon__
...
```

if I change it to:
```
__jumbo/creatures/adnd/aberration__
__jumbo/creatures/adnd/beast__
__jumbo/creatures/adnd/celestial__
__jumbo/creatures/adnd/construct__
__jumbo/creatures/adnd/dragon__
__jumbo/creatures/adnd/elemental__
__jumbo/creatures/adnd/fey__
```

Then it works fine. Could you please test this with your wildcards?

**Comment by Bonedragon1300** [comment]
hm, I changed it to this and it didn't work, am I missing something?
![Capture](https://user-images.githubusercontent.com/15267401/229270662-f8b26e37-a8a8-4d45-9452-c4c7a1aee336.PNG)

**Comment by adieyal** [comment]
To be sure it's not cached, try restarting the webui

**Comment by Bonedragon1300** [comment]
yup reloading fixed it. thanks. didn't realize that the formatting was changed so didn't know to change it

**Comment by adieyal** [comment]
In future, you can simply refresh wildcards in the Wildcards Manager. I
asked you to restart the webui to make sure.

**Comment by akx** [comment]
Looks like this is solved 👍
