### ISSUE TITLE
[Bug] Spelling Mistake in web ui

### ISSUE THREAD

**Issue by Krynh** [adieyal/sd-dynamic-prompts#371]
Version: 1596f556 (Mon Mar 6 04:49:07 2023)

Head to settings > Dynamic prompts

batch_size is misspelled as barch_size 

"Limit Jinja prompts: Limit the number of prompts to batch_count * batch_size. The default is to generate batch_count * barch_size * number of prompts generated by Jinja"

**Comment by akx** [comment]
Thanks, fixed!
