### ISSUE TITLE
[Feature request] Make the wildcard caching optional

### ISSUE THREAD

**Issue by acorderob** [adieyal/sd-dynamic-prompts#373]
Please add an option to disable this cache. For those of us constantly changing the wildcards from outside the webui interface it is very annoying to test some change and realize you forgot to refresh them.

**Comment by akx** [comment]
Sorry for the inconvenience. For the time being, you can add

```python
self._wildcard_manager.clear_cache()
```

somewhere around

https://github.com/adieyal/sd-dynamic-prompts/blob/337aa692e465d810dc01bb0138aa85837303f0c9/sd_dynamic_prompts/dynamic_prompting.py#L400-L405

in your copy of the extension.

**Comment by acorderob** [comment]
Will do. Thanks.

**Comment by Jonseed** [comment]
I also ran into this issue. I changed my wildcard, but it kept pulling the same lines from the old wildcard. Thought I'd lost my mind.

**Comment by akx** [comment]
Fixed via https://github.com/adieyal/sd-dynamic-prompts/pull/386.
