### ISSUE TITLE
ModuleNotFoundError: No module named 'send2trash'

### ISSUE THREAD

**Issue by ycwangzhe** [adieyal/sd-dynamic-prompts#376]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
clean-fid 0.1.29 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.
Successfully installed requests-2.28.2

**Comment by adieyal** [comment]
I don't understand the error message you posted, since neither dynamicprompts nor send2trash use clean-fid, it may be used somewhere in some upstream dependency but that's not clear. What happens if you run `python -m pip install send2trash==1.8.0`

**Comment by akx** [comment]
Closing as stale.

The `clean-fid` warning is irrelevant.
