### ISSUE TITLE
[Feature Request] Custom Delimiter for multiple terms (replace ",")

### ISSUE THREAD

**Issue by muunkky** [adieyal/sd-dynamic-prompts#379]
I love using the multiple terms feature: {2$$term1|term2}

Today this creates "term1, term2" but I would like to be able to change this to "term1 and term2" or "term1 with term2" or "term1 term2"

I see the option to change the delimiter in this case to a word or nothing at all can help overcome limitations for certain types of prompts.

**Comment by adieyal** [comment]
Have you tried this syntax: `{2$$ and $$red|green|blue}`? You can read about it here: https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md#custom-separator

**Comment by muunkky** [comment]
oh wow. That's great, thanks for pointing that out.
