### ISSUE TITLE
Request: A problem with Combinatorial generation

### ISSUE THREAD

**Issue by JohnWJarrett** [adieyal/sd-dynamic-prompts#38]
So, I get it, you don't want the user to accidentally generate thousands of prompts and all, but, really, that's on the user. 

The way you have it set now, I can have, at max, 32 combinations, unless I am missing something here... I could be, but, due to my processing limitations, I can't have the batch size very high. 

So if I am doing everything right, I can only do a batch size of 2 and the max for batch count (Unless there is someway to change that) is 16. Now my problem is I have 20 objects and 30 situations, objects in one file, situations in the other, and I want to combine them and that's like 600 combinations.

Can we please get a better way to limit how many we can generate at a time. 
Or, if there is a way I can do it with the current system, can we get an explanation as to how.

Thanks -J

**Comment by adieyal** [comment]
The way to fix that is to update ui-config.json in your webui directory. Find this line:

"txt2img/Batch count/maximum": 16

change the 16 to something bigger. I have it at 4000. Let me know if that works for you and I'll add it to the documentation.

**Comment by JohnWJarrett** [comment]
Yep, that works, thanks!
