### ISSUE TITLE
Combinatorial generation doesn't work as expected?

### ISSUE THREAD

**Issue by MicZet** [adieyal/sd-dynamic-prompts#39]
Nice extension but i think it doesnt work as documented

I installed it (as extension)
chose Dynamic prompting v0.13.7 (in Script section)
checked box Combinatorial generation
set Combinatorial batches to 4 
prompt: test {dog|cat|rabbit}

according to docs i should have 3 images with combination of 3 different animals
but i get 4 images with one of animals every time (same animal for all 4 images)

am i doing something wrong?

**Comment by tylerdurrett** [comment]
@MicZet You need to increase your batch count (not to be confused with combinatorial batches). In your example, if you set the batch count to anything >= 3 you will get the result you expected.

**Comment by adieyal** [comment]
@MicZet did @tylerdurrett's suggestion work for you? Combinatorial batches isn't a great term but I'm not sure what to call it. The batch sliders in combinatorial mode mean the following:

**batch size** * **batch count** = Maximum number of outputs, regardless of the number of variations

**combinatorial batches** = re-run your combinatorial batch that many times with a different seed. 
The maximum number of outputs is **combinatorial batches** * **batch size** * **batch count**

**Comment by MicZet** [comment]
Yes - thanks

**Comment by Eugenii10** [comment]
It would be good to add tooltip descriptions for all options like the original UI do.
'combinatorial batches' have confused me too in first time.

**Comment by adieyal** [comment]
Good point - adding tooltips is not straightforward but I need to figure out how to do it. I agree about combinatorial batches, it was included on request from a user, I'm considering moving it to the advanced options tab - what do you think?

**Comment by Eugenii10** [comment]
Original code from the 'hints.js' will fit.
You can take a look at: https://github.com/Eugenii10/sd-dynamic-prompts/commit/cbfa8e6e4fffbadebd6ed66bdb569f1d83c6542b
I can try to add tooltips for the all elements later if you want.

> I'm considering moving it to the advanced options tab - what do you think?

Personally I don't think that the problem is in the slider itself, however it might be best placed next to the "Fixed seed" checkbox. I think the problem is the lack of information (help description) for the elements. We have no tooltips, and the "Help" section is super short.

**Comment by adieyal** [comment]
> I can try to add tooltips for the all elements later if you want.

If you're up to it that it would be much appreciated
