### ISSUE TITLE
Inquiry regarding immediate evaluation of variables and batch processing

### ISSUE THREAD

**Issue by tsukimiya** [adieyal/sd-dynamic-prompts#393]
I would like to express my sincere appreciation for providing such an excellent extension.
I have a question regarding the use of immediate evaluation of variables and batch processing.
I have noticed that when performing batch processing using immediate evaluation of variables, the evaluation results from the first batch processing are carried over to the second and subsequent batch processing. Is this behavior intended or is it a specification? Furthermore, is there any way to avoid this behavior?

For your reference, I am currently using the following environment:
sd-dynamic-prompt: v2.11.1
dynamicprompts: 0.23.0

Thank you for taking the time to read this post.

**Comment by adieyal** [comment]
I think this issue related to #395 - I'm closing this - if you think it's different then feel free to re-open this one.

**Comment by tsukimiya** [comment]
It was indeed the same!
My apologies for my lack of confirmation.

Thank you for your reply.
