### ISSUE TITLE
[BUG]: value error file cannot be fetched

### ISSUE THREAD

**Issue by Woisek** [adieyal/sd-dynamic-prompts#405]
Since two days now, I get this strange error:

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Startup time: 10.7s (models=0.3s scripts=1.1s vae=0.1s ui=4.7s start=4.5s scripts app_started_callback=0.1s)
API error: GET: http://localhost:7860/file=extensions/sd-dynamic-prompts/wildcards//women_fullnames.txt?1682420419100 {'error': 'ValueError', 'detail': '', 'body': '', 'errors': 'File cannot be fetched: extensions/sd-dynamic-prompts/wildcards//women_fullnames.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.'}
HTTP API: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\venv\lib\site-packages\anyio\streams\memory.py:94 in receive                              │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\venv\lib\site-packages\anyio\streams\memory.py:89 in receive_nowait                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
WouldBlock

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                       │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\venv\lib\site-packages\anyio\streams\memory.py:114 in receive                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
EndOfStream

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\middleware.py:68 in exception_handling                                            │
│                                                                                                                     │
│   67 │   │   try:                                                                                                   │
│ > 68 │   │   │   return await call_next(req)                                                                        │
│   69 │   │   except CancelledError:                                                                                 │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                       │
│                                                                                                                     │
│                                              ... 15 frames hidden ...                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\venv\lib\site-packages\fastapi\routing.py:163 in run_endpoint_function                    │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\routes.py:337 in file                                       │
│                                                                                                                     │
│   336 │   │   │   else:                                                                                             │
│ > 337 │   │   │   │   raise ValueError(                                                                             │
│   338 │   │   │   │   │   f"File cannot be fetched: {path_or_url}. All files must contained wi                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: File cannot be fetched: extensions/sd-dynamic-prompts/wildcards//women_fullnames.txt. All files must
contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
API error: GET: http://localhost:7860/file=extensions/sd-dynamic-prompts/wildcards//bodytype_female.txt?1682420507812 {'error': 'ValueError', 'detail': '', 'body': '', 'errors': 'File cannot be fetched: extensions/sd-dynamic-prompts/wildcards//bodytype_female.txt. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.'}
HTTP API: ValueError
┌─────────────────

But the generations itself are functioning. Through autocomplete I also get all the available wildcards (__wildcard__) but I don't get the content of them and that's when the error occurs.
The folder "wildcards" is a Junction (I'm on Windows), but that was never a problem before.

Any suggestions? 😐

**Comment by Woisek** [comment]
Hmm ... no one cares ... ?! 😐

**Comment by akx** [comment]
Let's continue in your other issue https://github.com/adieyal/sd-dynamic-prompts/issues/261.

**Comment by Woisek** [comment]
> Let's continue in your other issue #261.

Ah, OK. 🙂
