### ISSUE TITLE
Is it possible to use the same random seelction multiple times in a prompt?

### ISSUE THREAD

**Issue by tusharbhutt** [adieyal/sd-dynamic-prompts#41]
I have a file of random "careers" for characters.  I'm hoping to reuse the random choice  to indicated both the career and the uniform the character is wearing but I am not having much success.

I've tried:

A \_\_career\_\_ wearing a \_\_career\_\_ outfit but what I end up with is something like:

A **teacher** wearing a **fishmonger's** outfit  [NOTE: not that there's anything wrong with that in real life!] when I wanted a **teacher** in a **teacher's** outfit

I thought I'd be clever and see if using "$1" or "\1" as a regex group holder would work, but that failed miserably :)

**Comment by alexanderdutton** [comment]
I've also had this interest -- it would be nice to have some kind of operator which might 'lock' a particular wildcard to be consistent.

A __Career(1)__ wearing a __Career(1)__ outfit while at a __Career(2)__ worksite, speaking to a __Career__ person.

**Comment by adieyal** [comment]
I like that idea - I'll give it some thought. In your example, it would be:

A teacher wearing a teacher outfit 
and not A teacher wearing a teacher's outfit.

**Comment by tusharbhutt** [comment]
> I like that idea - I'll give it some thought. In your example, it would be:
> 
> A teacher wearing a teacher outfit and not A teacher wearing a teacher's outfit.

Well, if it was a \_\_career\_\_ wearing a \_\_career\_\_'s outfit then you'd get "a teacher wearing a teacher's outfit", which is fine.  As long as the string is constant (if the user wants it what way). so you do not get "a nurse wearing a welder's outfit" :)

**Comment by adieyal** [comment]
Can you test out the new Jinja2 templates feature? You can read about it here: [https://github.com/adieyal/sd-dynamic-prompts#jinja2-templates](https://github.com/adieyal/sd-dynamic-prompts#jinja2-templates)

In your example, you can do something like:

    {% for career in ['teacher', 'doctor', 'lawyer'] %}
        {% prompt %}A {{ career }} wearing a {{ career}}'s outfit{% endprompt %}
    {% endfor %}

**Comment by tusharbhutt** [comment]
> Can you test out the new Jinja2 templates feature? You can read about it here: https://github.com/adieyal/sd-dynamic-prompts#jinja2-templates
> 
> In your example, you can do something like:
> 
> ```
> {% for career in ['teacher', 'doctor', 'lawyer'] %}
>     {% prompt %}A {{ career }} wearing a {{ career}}'s outfit{% endprompt %}
> {% endfor %}
> ```

Hmmm... I usd the automatic update in AUTO1111 and it says my version was behind, did an update but still loaded 0.13.7

**Comment by adieyal** [comment]
Could you give me an example of a prompt that didn't work?

**Comment by tusharbhutt** [comment]
> Could you give me an example of a prompt that didn't work?

Sure, this is on the latest (couldn't download via AUTO update, downloaded manually and threw it in the extensions folder)

PROMPT: professional digital airbrush art of {% for career in ['teacher', 'doctor', 'lawyer'] %}     {% prompt %}A {{ career }} wearing a {{ career}}'s outfit{% endprompt %} {% endfor %}, masterpiece

OUTPUT:  A lawyer wearing a lawyer's outfit
Steps: 35, Sampler: DPM++ 2S a, CFG scale: 12, Seed: 1166881647, Size: 512x512, Model hash: 81761151, Model: Stable1.5, Eta: 0.77, aesthetic_score: 5.5

And the same for the other two careers.

**Comment by adieyal** [comment]
The entire prompt needs to be in the {% prompt %}...{% endprompt %} block, e.g.

    {% for career in ['teacher', 'doctor', 'lawyer'] %}
        {% prompt %}professional digital airbrush art of A {{ career }} wearing a {{ career}}'s outfit, masterpiece{% endprompt %}
    {% endfor %}

**Comment by adieyal** [comment]
Also, why couldn't you update via auto update? Did you get an error message?

**Comment by tusharbhutt** [comment]
> The entire prompt needs to be in the {% prompt %}...{% endprompt %} block, e.g.
> 
> ```
> {% for career in ['teacher', 'doctor', 'lawyer'] %}
>     {% prompt %}professional digital airbrush art of A {{ career }} wearing a {{ career}}'s outfit, masterpiece{% endprompt %}
> {% endfor %}
> ```

OH!  OK, that worked!

**Comment by tusharbhutt** [comment]
> Also, why couldn't you update via auto update? Did you get an error message?

I did get an error message, can't grab it now because the update tab is now telling me Dynamic Prompts are up to date.  But before that, it was something like this message for the prompt travel script (same messagr for your script):

Error pulling updates for stable-diffusion-webui-prompt-travel:
Traceback (most recent call last):
  File "E:\StableDiffusion\modules\ui_extensions.py", line 39, in apply_and_restart
    ext.pull()
  File "E:\StableDiffusion\modules\extensions.py", line 70, in pull
    repo.remotes.origin.pull()
  File "E:\StableDiffusion\venv\lib\site-packages\git\remote.py", line 910, in pull
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "E:\StableDiffusion\venv\lib\site-packages\git\remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "E:\StableDiffusion\venv\lib\site-packages\git\cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v origin
  stderr: 'fatal: unable to auto-detect email address (got '**[usernameredacted]**@**[computernameredacted]**.(none)')'

Also, when it restarts the Detection Detaile script throw some errors and I am told PIP is out of date.  Since the erors started after installing a few scripts, i figure they are not playing nice with each other, so it must be a config issue on my side, or witin AUTO.  I'm going to update PIP to see if that helps

**Comment by adieyal** [comment]
If you come across another installation issue that you think might be related to this extension, please create a new issue.
