### ISSUE TITLE
Feature Request: Resumable Combinatorial Generation

### ISSUE THREAD

**Issue by curtwagner1984** [adieyal/sd-dynamic-prompts#423]
Let's say you have a fairly large prompt like " {X | Y | Z | W } with {A | B| C |D}" and you want to render all possible combinations however due to whatever limitation you can only render 4 images per session. 

Currently, (As far as I know) there is no option to resume generation from the last combination you previously rendered. And if you choose combinatorial generation, you'll just start from scratch.

It would be great if such a thing was possible, where you generate X images today, and can resume generating the remaining images in the next day.

**Comment by adieyal** [comment]
Why can you only render 4 images at a time? What happens if you increase your batch count?

**Comment by Kadah** [comment]
I've done really large runs. Massive batch counts require an insane amount of RAM, and more so time. I think time is more the issue for OP.

They could simulate a workaround by fixing some of the variables to one single value and manually iterating it for successive batches.

**Comment by curtwagner1984** [comment]
@adieyal The batch count isn't really the issue, the point I was trying to make is that dynamic prompt can result in a lot of combinations, let's say 1000 and if you want to render all combinations, currently you must do it in one session. There is no way to pause and resume, so if you start rendering and you rendered 200 images, and you want to turn off your computer and continue tomorrow, you can't, because current it will just continue from the start.

**Comment by akx** [comment]
Well, "combinatorial skip" could well be implemented as a special power-user option :)
