### ISSUE TITLE
(BUG?) Wildcards manager tab / issue in Automatic 1111

### ISSUE THREAD

**Issue by Rojinski** [adieyal/sd-dynamic-prompts#429]
Hello :)

I wanted to use, today, my Wildcards Manager tab and select one of my personal wildcards. Until, it was working perfectly. But, in a first time, my Automatic 1111 web ui was showing 2 tabs of WCM! None of them was showing my files and the "native" files (artists, jumbo, etc) didn't show the usual text files in the "Wildcards file" field or in the "file editor" box So i've uninstalled the extension and reinstall it again. Hooray, just one tab again. But still the same problem: nothing is working.  My files are not showing in the drop down menu and the native files are showing but not working.  The files are in the right directory "Wildcards" of the extension in the Stable-diffusion-webui. My version of the extension is up-to-date and the library too (verified as recommanded in the "troubleshooting" section --> You are using version 2.11.2 of the WebUI extension, and the underlying dynamicprompts library is version 0.23.0. 

I've tried to install the old extension of wildcards (https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards) but no tab is showing even after a complete reboot.

On Vlad Diffusion, it works perfectly and i have also the same version of the extension and of the library.

Could you help me, please :) Thanks on advance.

 #Rojinski.

![Screenshot 2023-05-14 at 01-29-29 Stable Diffusion](https://github.com/adieyal/sd-dynamic-prompts/assets/122015375/61614f78-e329-4eb2-9aa5-21997b54e2aa)

![Screenshot 2023-05-14 at 01-47-59 Stable Diffusion](https://github.com/adieyal/sd-dynamic-prompts/assets/122015375/dde5f040-df68-4ec2-ba13-a4e05acac4b7)

IN VLAD DIFFUSION (screenshot)

![Screenshot 2023-05-14 at 01-59-08 SD Next](https://github.com/adieyal/sd-dynamic-prompts/assets/122015375/cb6ce675-189b-47b1-a03b-b66e248c14a1)

**Comment by CeterPushing** [comment]
I was having the same issue, went through the arduous process of disabling all extensions to find the conflict, in my case it was the following extension:

stable-diffusion-webui-two-shot
https://github.com/ashen-sensored/stable-diffusion-webui-two-shot

Disabling this extension allowed the wildcards to be accessible via the tab "Wildcard Manager"

As both of these repos don't have any current changes, I can only speculate that since Automatic1111 was recently updated that is where the change occurred.

**Comment by Rojinski** [comment]
> I was having the same issue, went through the arduous process of disabling all extensions to find the conflict, in my case it was the following extension:
> 
> stable-diffusion-webui-two-shot https://github.com/ashen-sensored/stable-diffusion-webui-two-shot
> 
> Disabling this extension allowed the wildcards to be accessible via the tab "Wildcard Manager"
> 
> As both of these repos don't have any current changes, I can only speculate that since Automatic1111 was recently updated that is where the change occurred.

Thank you so much for your answer! Indeed, it's a problem with the extension "stable-diffusion-webui-two-shot" !!  I don't have that pronlem on Vlad, even if i have that extension installed in it. :)  Thanks again, CeterPushing !

**Comment by GalaxyTimeMachine** [comment]
I was having the same problem in the Vlad fork, but disabling two-shot resolved it for me too. Is this a problem with the GUI or is it caused by one of the two extensions?

**Comment by akx** [comment]
This should no longer be an issue. It was (is) a bug in the webui with nested tabs.
