### ISSUE TITLE
"File <full path> not found for the __<wildcard>__ wildcard."

### ISSUE THREAD

**Issue by DrCyanide** [adieyal/sd-dynamic-prompts#43]
I can't tell if I've done the setup wrong, or if I'm running into a bug. Installed from the Extension's page, and it's saying I'm up-to-date.

I've got my files in the default WILDCARD_DIR, like such:
`scripts\wildcards\clothing\outfits.txt`
`scripts\wildcards\clothing\shoes.txt`
`scripts\wildcards\clothing\tops.txt`
`scripts\wildcards\clothing\bottoms.txt`
`scripts\wildcards\test.txt`

test.txt contents (all on new lines, edited with Notepad so it probably has the Windows formatting)
```
Summer
Autumn
Winter
Spring
```

When I type in the prompt `a lake in __test__` I get the auto complete suggestions showing up as soon as I type `__`, which is a good sign everything is in the right directory. If I select one of the files, it lists out all the options in it so I can manually pick one, which again makes me think I'm set up correctly.

However, when I go to run it, I get this error in the command prompt:
`File E:\Documents\AI\ImgGen\stable-diffusion-webui\extensions\stable-diffusion-webui-wildcards\wildcards\test.txt not found for the __test__ wildcard.`

It gets even worse when I try to use the clothing ones:
`File E:\Documents\AI\ImgGen\stable-diffusion-webui\extensions\stable-diffusion-webui-wildcards\wildcards\clothing/outfits.txt not found for the __clothing/outfits__ wildcard.`
Notice the full path there. It's swapping between `\` and `/` for the directory. Not good!

The lake never generates with anything other than a vibrant green trees and grass around it (take your pick on Summer or Spring), and the text under the image generation is always this (minus the seed changing)
```
a lake in test
Steps: 28, Sampler: Euler a, CFG scale: 11, Seed: 945332860, Size: 512x768, Clip skip: 2, Wildcard prompt: a lake in __test__
```
I _assume_ if the wildcards were working one of the prompts would replace `test` with one of the seasons?

**Comment by adieyal** [comment]
When you open the Dynamic Prompting extension in the dropdown, you should see help text. At the bottom, the full path to WILDCARD_DIR is shown. It should be something like: WILDCARD_DIR: /path/to/stable-diffusion-webui/extensions/sd-dynamic-prompts/wildcards

What does yours say? scripts/wildcards/.... is the old location. Is there some old documentation that still refers to it somewhere?

**Comment by DrCyanide** [comment]
> What does yours say? scripts/wildcards/.... is the old location. Is there some old documentation that still refers to it somewhere?

Ah, that did it! The Dynamic Prompting script says `WILDCARD_DIR: E:\Documents\AI\ImgGen\stable-diffusion-webui\extensions\sd-dynamic-prompts\wildcards`

The README.md, under the WILDCARD_DIR header, says `scripts/wildcards/` is the default

**Comment by adieyal** [comment]
That's great. I've updated the documentation.
