### ISSUE TITLE
functionality while in --api mode?

### ISSUE THREAD

**Issue by jmpress** [adieyal/sd-dynamic-prompts#430]
Is there any way to get this extension to work with the server in --api mode?

It works fine when I run a prompt through the gradio webui, but when I send a prompt to the api endpoint (/sdapi/v1/txt2img), it doesn't seem to parse the __syntax__.

Thanks a ton, I love this extension.

**Comment by brianjz** [comment]
I don't know if there is a difference, but I use it in API mode in the Vlad fork and it works fine.

**Comment by jmpress** [comment]
Recent update to A1111 webui itself seems to have fixed the issue I was having!
