### ISSUE TITLE
Feature Request: Randomize lora weights

### ISSUE THREAD

**Issue by nialv7** [adieyal/sd-dynamic-prompts#434]
like attention grabber that randomizes weights of certain words, it could also be useful to randomize weights for Loras

**Comment by Appolonius001** [comment]
to randomize weights i use something like this <lora:ArtNouveauAI:{1|.9|.8|.7}> and so on. also i made a wild card with number ranges so i can use __weight__ and it places a random weight anywhere i want

**Comment by akx** [comment]
Duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/236 for all practical purposes, keep an eye on that one :)
