### ISSUE TITLE
[Bug]: Dynamic prompts/wildcards highly change the results vs firstpass, on the hi-res pass on new hi-res fix.

### ISSUE THREAD

**Issue by Panchvzluck** [adieyal/sd-dynamic-prompts#435]
Hi there, really thanks for all your work! There's a new issue, after an update on the dev branch of the webui.

Since https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ff0e17174f8d93a71fdd5a4a80a4629bbf97f822 dev commit, if you use it at the same time with wildcards/dynamic prompts, it can use more than one value inside the {|} brackets.

The result is noticeable altered after the hi-res fix pass.

For example, if you use "{green|red|blue|black} eyes", and the choosen token was "green", the result can be a mix of all those eye colours, or a mix of green/red, green/blue, etc

This is more pronounced when using loras/tis with this syntax (for example, "{lora:a1:1|lora:a2:1|lora:a3:1|...}"

The issue get worse when using more than one dyanmic prompt at the same time (aka, random eyes, random hair colours, random hair style, etc)

The issue doesn't happen if the commit is reverted to https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3885f8a63e0954ac96e6681aa8b33281f10337a2

And the issue doesn't happen when not using dynamic prompts/wildcards.

No visible error in the console

To reproduce the problem,
1. Generate any prompt with an extense wildcard/dynamic prompt (example if you want to test):
`{blue-gray eyes|orange eyes|light blue eyes|dark red eyes|blind eyes|silver eyes|light brown eyes|light green eyes|dark brown eyes|retro eyes|heart eyes|dark purple eyes|amber eyes|light pink eyes|hazel eyes|yellow eyes|blue eyes|dark green eyes|light red eyes|red eyes|diamond eyes|brown eyes|closed eyes|cat eyes|dark blue eyes|green-hazel eyes|dark pink eyes|purple eyes|white eyes|demon eyes|squinted eyes|gray eyes|pink eyes|light purple eyes|magenta eyes|sparkling eyes|gold eyes|black eyes|green eyes|heterochromia}`
2. Enable/select hires fix.
3. Generate the image and see if the eye colour result is the desired one, and not a mix of the others colours.

The result should be only the selected by the wildcard/dynamic prompt, and not a mix of the possible values inside the {} brackets.

**Comment by Panchvzluck** [comment]
I think I have kinda found the issue, not sure how to fix it.

When on processing.py, changing the lines

```
        if self.hr_prompt == '':
            self.hr_prompt = self.prompt

        if self.hr_negative_prompt == '':
            self.hr_negative_prompt = self.negative_prompt
```

to

```
        if self.hr_prompt == '':
            self.hr_prompt = self.all_prompts

        if self.hr_negative_prompt == '':
            self.hr_negative_prompt = self.all_negative_prompts
```

on lines 1077-1081, you can see a print of the hi-res fix prompt on the webui.

And it seems to be doing a pass of the __values__ or {value1|values2} directly on the hires pass, instead of using the value that should be selected on the firstpass.

Without changing those lines, you can add a print and it will have the same issue on the console.

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/19153797/d980a546-a4b1-4470-94c2-58b85fc454da)

Firstpass:
`best quality,sfw,1girl,solo,grey hair, multiple braids, very long hair, cat eyes,hair ornament, necklace, tiara, hair between eyes, leggings, shawl, looking down, space elevator, closed mouth, portrait,`

Hi-res fix pass:
`["best quality,sfw,1girl,solo,__haircolor__, __hairstyles__, __hairlength__, __eyecolour__, __attire_jewelry_and_accessories_head_and_face__, __accessories__, __attire_headwear__, __bangs__, __legwear__, __neckwear__, __lookingdirections__, {__locations_outdoors_natural__|__locations_buildings__}, {__face_emotions__|__face__}, portrait,"]`

Sorry for the ping @adieyal , but I'm not sure if this is on your side (the extension) or on the auto111 side.

**Comment by Panchvzluck** [comment]
Okay, found the total culprit and not sure why it happens.

On modules/processing.py, line 1126 to 1135

```
    def parse_extra_network_prompts(self):
        res = super().parse_extra_network_prompts()

        if self.enable_hr:
            self.hr_prompts = self.all_hr_prompts[self.iteration * self.batch_size:(self.iteration + 1) * self.batch_size]
            self.hr_negative_prompts = self.all_hr_negative_prompts[self.iteration * self.batch_size:(self.iteration + 1) * self.batch_size]

            self.hr_prompts, self.hr_extra_network_data = extra_networks.parse_prompts(self.hr_prompts)

        return res
```

Seems that the first 2 lines after if self.enable_hr, or, specially the `self.hr_prompts = self.all_hr_prompts[self.iteration * self.batch_size:(self.iteration + 1) * self.batch_size]` lines makes the issue surface.

If you comment this line, or well all the function, it works as it was before https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ff0e17174f8d93a71fdd5a4a80a4629bbf97f822 commit, but then hi-res negative prompt doesn't work by itself. It needs to have any prompt on the positive hires prompt. Now, doing that, makes the issue come back (getting tokens outside the {} or __wildcard__ values), but it is that code that's doing the issue.

**Comment by horsepowermini** [comment]
Same issue on my pc after last update of automatic1111. Hires prompt in generated image somehow look like {@var1|var2|var3} and generation look bad

**Comment by brimston3** [comment]
This should be fixed now by pr #483, which sets the hr_all_prompts/hr_all_negative_prompts parameters for upscaling. At least it fixed my problems with it.

**Comment by Panchvzluck** [comment]
@brimston3 just tested and it works TON better than before. It seems to be fixed.

But highres positive/negative prompt don't work. BUT it seems to be an auto111 issue and not a dynamic prompt issue. (Tested without dynamic prompts and they don't work for me). Do hr prompt work for you? Maybe after tinkering so much in my branch I broke something.

**Comment by brimston3** [comment]
hr prompt/hr negative work in auto1111 on main branch. #483 wrecks them both. I made a pr #495 to address hr_prompt/hr_negative a little, but it's not perfect and they are not processed using the dynamic prompt engine. I think this extension's maintainers are going to need to talk about what it *should* do about combinatorial generation and other extensions modifying all_prompts/negative/hr before a clear way forward on how to handle hr_prompt/hr_negative appears.

tbh, I think the language should be simplified for hr_prompt/negative and only allow cached results by keyword, though I haven't a clue how that should be handled.

**Comment by Panchvzluck** [comment]
closing @akx and @brimston3 , since it's fixed by PR https://github.com/adieyal/sd-dynamic-prompts/pull/495 and PR https://github.com/adieyal/sd-dynamic-prompts/pull/498.
