### ISSUE TITLE
Make version compatibility checking stricter

### ISSUE THREAD

**Issue by akx** [adieyal/sd-dynamic-prompts#437]
We've had a bunch of issues now and in the past where people haven't upgraded `dynamicprompts` along with sddp.

I think the UI should make it very clear if you're using an incompatible/old version of DP, e.g. by making the Dynamic Prompts accordion a screaming orange or something.

We could even (try to) offer a button to upgrade DP too (though it will probably require a restart of the WebUI to properly take).

**Comment by adieyal** [comment]
Did you see my commit from earlier today?
https://github.com/adieyal/sd-dynamic-prompts/commit/72f21dea4d1a31b0cd496a472a30c3d2ce96501d

It only writes to the terminal - a visual indication would be helpful. 

Do you know why it isn't updating automatically for some people? install.py should run unless there is some way to disable it via a flag.

**Comment by akx** [comment]
Ah, no, I didn't see that :)

`install.py`s definitely are run by `launch.py` but then there are folks who don't use `launch.py` (such as, ahem, yours truly)...

**Comment by adieyal** [comment]
How are you disabling it? Do you think others are doing the same?

**Comment by akx** [comment]
I just use `webui.py` instead, and only run `launch.py` when I've pulled a new version of the webui.

I don't know how common that might be.
