### ISSUE TITLE
[BUG] Extension Broken on Latest Update

### ISSUE THREAD

**Issue by Neverdusk** [adieyal/sd-dynamic-prompts#438]
After updating the extension, I receive this error whenever I open my WebUI:

> *** WARNING: Something went wrong when updating to the latest dynamicprompts version. Please install it manually by running the following command:
    C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\venv\Scripts\python.exe -m pip install dynamicprompts==0.25.2

Whenever I generate an image with wildcards, the wildcards don't do anything, and I receive this error (I think it was called a second time for hires fix):

> Error running process: C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\dynamic-prompts\scripts\dynamic_prompting.py
> Traceback (most recent call last):
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\modules\scripts.py", line 418, in process
>     script.process(p, *script_args)
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
>     all_prompts, all_negative_prompts = generate_prompts(
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
>     all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
> TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'
> 
> Error running process: C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
> Traceback (most recent call last):
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\modules\scripts.py", line 418, in process
>     script.process(p, *script_args)
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
>     all_prompts, all_negative_prompts = generate_prompts(
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
>     all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
> TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'

I've already tried updating / reinstalling the extension inside of the UI and also manually via git clone. As for the command provided in the initial error, I'm not actually familiar enough to know where to open the cmd terminal to type it (UI root, extension folder, or venv/scripts folder). So I could also use any help there, if possible.

**Comment by adieyal** [comment]
You need to open a terminal a type the command that the error message gives you. I'm not familiar with Windows but this might help - https://www.wikihow.com/Open-Terminal-in-Windows

Once the terminal is open, run this command
`C:\Users\silve\Documents\AI Art__Auto1111_UX\stable-diffusion-webui-ux\venv\Scripts\python.exe -m pip install dynamicprompts==0.25.2`
`

**Comment by Neverdusk** [comment]
Thank you for the help. 

I tried opening a plain cmd terminal and typing that exact command, but I ended up receiving a few errors that the path wasn't a recognized command or couldn't be found. But once I navigated to C:\Users\silve\Documents\AI Art__Auto1111_UX\stable-diffusion-webui-ux\venv\Scripts and opened a cmd there, this command worked: 

> python.exe -m pip install dynamicprompts==0.25.2

It then seemed to duplicate the extension - with a new one called dynamic-prompts and the old one called sd-dynamic-prompts. So I copied my wildcards over, disabled the old copy, and now things seem to work.

This might've been a roundabout solution, but the extension works again now.

**Comment by khanghuynhmba** [comment]
Thank you, I had the same problem as well and running the command line seems to fix it!

**Comment by Neverdusk** [comment]
So I refreshed my wildcards, and suddenly I have more errors and the extension isn't working anymore, again. I don't really know what's happening anymore, but I'll paste my error log to see if anyone else knows better:

> Error running process: C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
> Traceback (most recent call last):
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\modules\scripts.py", line 418, in process
>     script.process(p, *script_args)
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
>     all_prompts, all_negative_prompts = generate_prompts(
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
>     all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 70, in generate
>     gen = self._context.sample_prompts(template, 1)
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
>     command = parse(prompt, parser_config=self.parser_config)
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
>     tokens = get_cached_parser(parser_config).parse_string(
>   File "C:\Users\silve\Documents\AI Art\__Auto1111_UX\stable-diffusion-webui-ux\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
>     raise exc.with_traceback(None)
> pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 459), (line:11, col:3)

**Comment by Neverdusk** [comment]
Nevermind, I think it was a typo. One of my wildcards didn't put "__" at the end. Sorry for the false alarm.

**Comment by SteMoeller** [comment]
> You need to open a terminal a type the command that the error message gives you. I'm not familiar with Windows but this might help - https://www.wikihow.com/Open-Terminal-in-Windows
> 
> Once the terminal is open, run this command `C:\Users\silve\Documents\AI Art__Auto1111_UX\stable-diffusion-webui-ux\venv\Scripts\python.exe -m pip install dynamicprompts==0.25.2` `

Sorry to say that but this won't work in most cases.
The "normal" automatic installation uses a virtual python environment with a completely different directory structure than the normal python installation.... I suppose that a lot of problems and bugs from windows users come from this topic...
In the automatic1111 directory we find a "venv" directory  with a lib and a site-packages sub directory where are the extensions are installed... And I think that a lot of problems come from incompatibilty issues between the sd-plugin and the "main" dynamicPrompts library. 
I did not find a way to run the normal "python" and "pip" things to that virutal environment but that cannot be too hard... 
Just took a look at the webui.bat file and it seems that you can pass the virtual environment directory to python using "-m venv [directory]" which should do the trick...

**Comment by akx** [comment]
@SteMoeller Please look at the command line quoted again – it is referring to the webui venv: **`stable-diffusion-webui-ux\venv\Scripts\python.exe`**
