### ISSUE TITLE
Python 3.10 only syntax breaks extension in older Python versions

### ISSUE THREAD

**Issue by lbeltrame** [adieyal/sd-dynamic-prompts#440]
I'm referring in particular to `install.py`:

https://github.com/adieyal/sd-dynamic-prompts/blob/72f21dea4d1a31b0cd496a472a30c3d2ce96501d/install.py#L23

This syntax is Python 3.10 only, which means the extension won't work on platforms that don't have Python 3.10 (for example Google Colab or Paperspace).

**Comment by Ineman** [comment]
Saving ngrok auth token to ~/.ngrok_token
/home/studio-lab-user/SageMaker/stable-diffusion-webui
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing requirements
Error running install.py for extension /home/studio-lab-user/SageMaker/stable-diffusion-webui/extensions/sd-dynamic-prompts.
Command: "/home/studio-lab-user/.conda/envs/default/bin/python" "/home/studio-lab-user/SageMaker/stable-diffusion-webui/extensions/sd-dynamic-prompts/install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "/home/studio-lab-user/SageMaker/stable-diffusion-webui/extensions/sd-dynamic-prompts/install.py", line 23, in <module>
    def split_package(requirement) -> tuple[str, str | None, str | None, str | None]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by adieyal** [comment]
Thanks for raising the issue - that's probably the reason many of the collab installations are not updating the dependency. Fixed in [2.11.4](https://github.com/adieyal/sd-dynamic-prompts/commit/d30639722fb812eca3b54bfcb24f19d7783c3bdf)
