### ISSUE TITLE
Hire.fix no longer works

### ISSUE THREAD

**Issue by medledan** [adieyal/sd-dynamic-prompts#444]
My issue with this extension is that Hires.fix no longer works when the extension is enabled. I click the X to toggle the feature, and no additional hire.fix options appear. I turn the extension off again and Hires. fix works again and the options for Hire.fix configuration appears again.

**Comment by adieyal** [comment]
do you get any error messages? It works for me

**Comment by medledan** [comment]
This was caused by an extension called stable-diffusion-webui-state. You need to UNCHECK the extensions hires.fix enable checkbox, and select it manually. You can still save all the hires.fix states and it will still work but DO NOT SELECT the hires.fix enable state memorization.

**Comment by akx** [comment]
Glad you solved it!
