### ISSUE TITLE
Wildcards are no longer random

### ISSUE THREAD

**Issue by unoriginalscreenname** [adieyal/sd-dynamic-prompts#451]
Just updated and started getting back into SD.  I noticed that when I use the wildcards now they are no longer random?  I'm getting the same ones each time.  I have a list of celebrity names and if I use anything like __celebs__ or {3$$__celebs__} I always get the same names being pulled.

**Comment by GeneralAwareness** [comment]
Just updated a few minutes ago and now the previous update's errors are gone, BUT the new one is that these don't do anything now.

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/124339252/6c311b9f-4087-47f1-bce9-2235490d7d70)

I ran 4 then 4 more and nothing changed but in the previous version, before the last one, it worked without fail by have a fixed seed and checking those two boxes.  If I go to random (the dice) seed it works.

**Comment by adieyal** [comment]
Thanks for raising this - i'll test it, there is a good chance that the recent update to the way we handle seeds may have affected this

**Comment by monoinyo** [comment]
Interesting, I notice when I used a fixed seed but leave a wildcard in the prompt the wildcard sticks to the first iteration

**Comment by shanehyde** [comment]
Roll back to before 3aeda4682b724ebf074692101e205282bc22529c and it works fine.
```python
            all_seeds = None
            if num_images:
                p.all_seeds, p.all_subseeds = get_seeds(
                    p,
                    num_images,
                    use_fixed_seed,
                    is_combinatorial,
                    combinatorial_batches,
                )
                all_seeds = p.all_seeds
```
If `num_images` is 0 we seem to get no seeds

**Comment by adieyal** [comment]
Is this still an issue with the latest version?

**Comment by monoinyo** [comment]
> Is this still an issue with the latest version?

it seems to be working again, thank you!
