### ISSUE TITLE
Dynamic prompts stopped working

### ISSUE THREAD

**Issue by mdlieber99** [adieyal/sd-dynamic-prompts#455]
I temporarily installed the 'latent couple' extension on automatic1111 colab and this seems to have broken a number of things including wildcards, dynamic prompts, and controlnet.  I uninstalled it and controlnet came back, but wildcards and dynamic prompts no longer work.  I uninstalled and reinstalled the dynamic prompts extension.  It says I'm using the May 24 version so I think I have the latest version.  Do you have any suggestions for how to get wildcards and dynamic prompts working again?  I'd appreciate any help you can offer.  Dynamic prompts are really critical to my workflow.

**Comment by Panchvzluck** [comment]
Are you on master or dev branch of the automatic111 webui?

**Comment by mdlieber99** [comment]
I'm not sure.  I'm a basic user following lastben's colab for getting on automatic1111

**Comment by Panchvzluck** [comment]
Then you're probably on the master branch, in the console doesn't show an issue when loading dyanmic prompts?

**Comment by mdlieber99** [comment]
ok - when I just ran "pip install 'dynamicprompts[attentiongrabber,magicprompt]==0.25.2'" that seemed to solve the problem. thanks for your help!

**Comment by PuDood** [comment]
C:\Windows\system32>pip install dynamicprompts[attentiongrabber,magicprompt]==0.25.2
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement dynamicprompts[attentiongrabber,magicprompt]==0.25.2 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.3.2, 0.4.0, 0.4.1, 0.4.3, 0.6.0, 0.7.0, 0.7.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.20.0, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.22.0, 0.23.0)
ERROR: No matching distribution found for dynamicprompts[attentiongrabber,magicprompt]==0.25.2

C:\Windows\system32>

> ok - when I just ran "pip install 'dynamicprompts[attentiongrabber,magicprompt]==0.25.2'" that seemed to solve the problem. thanks for your help!ok -当我运行“pip install 'dynamicprompts[attentiongrabber，magicprompt]== 0.25.2'”时，似乎解决了这个问题。谢谢你的帮助！
