### ISSUE TITLE
Click “refresh wildcards” but nothing happens！！！

### ISSUE THREAD

**Issue by zhaochi12** [adieyal/sd-dynamic-prompts#459]
After I put the file into the wildcards folder, I clicked refresh wildcards on the SD page, but there was no response, nothing happened! Is this what is the reason...
<img width="1145" alt="1" src="https://github.com/adieyal/sd-dynamic-prompts/assets/5520626/e0a661ae-7a53-4eb2-994a-a8f6a8503459">
<img width="603" alt="2" src="https://github.com/adieyal/sd-dynamic-prompts/assets/5520626/f146ca73-7c53-47bd-ba84-0efa09a6a114">

**Comment by SevorLu** [comment]
Me too，Have you found a solution yet?

**Comment by akx** [comment]
This is likely a conflict with some other extension. Please see #429 and #360; try disabling other extensions until SDDP starts to work, and let us know if/when you find the culprit.

**Comment by zhaochi12** [comment]
> Me too，Have you found a solution yet?

not yet..

**Comment by zhaochi12** [comment]
> This is likely a conflict with some other extension. Please see #429 and #360; try disabling other extensions until SDDP starts to work, and let us know if/when you find the culprit.

OK sure...

**Comment by Neverdusk** [comment]
For me it was https://github.com/bbc-mc/sdweb-merge-block-weighted-gui.

Would there be any way to request compatibility between these extensions? In the meantime, I suppose I could disable it when trying to run Dynamic Prompts.
