### ISSUE TITLE
Behind HEAD error?

### ISSUE THREAD

**Issue by Appolonius001** [adieyal/sd-dynamic-prompts#460]
For the last week or so every time i try to update Dynamic Prompts when i search for a new update from Automatic1111 it says

**sd-dynamic-prompts | https:// github.com/adieyal/sd-dynamic-prompts.git | d 3063972 (Tue May 23 05:25:23 2023) | Behind HEAD**

and refuses to update

UpDate- ok im just going to move my install folder to another shorter length install place. Thanks akx

**Comment by adieyal** [comment]
in the sd-dynamic-prompts directory, type `git branch` and paste the result. Also, try `git pull --all` and `git checkout main`

**Comment by akx** [comment]
The error you edited out of the original post is the relevant bit:

> error: unable to create file collections/devilkkw/body-2/shoulders_attire_clothing_desgined_to_leave_shoulders_bare_low_and_wide_cut_necklines.txt: **Filename too long**

Trying to update SDDP is attempting to create a file with the path `"C:\Users\Appolonius\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\Text To Image\stable-diffusion-webui\extensions\sd-dynamic-prompts\collections\devilkkw\body-2\shoulders_attire_clothing_desgined_to_leave_shoulders_bare_low_and_wide_cut_necklines.txt"` which is more than [the default length limit](https://stackoverflow.com/a/1880453/51685) of 260 characters.

You should probably move your installation to a shorter path to avoid future problems.

**Comment by akx** [comment]
@adieyal WDYT, btw, should we convert the premade collections to YAML pantries so the pathnames would be shorter? (That'd probably just be `collections/devilkkw.yaml`.) I'd be glad to do the work.

**Comment by adieyal** [comment]
👍

**Comment by akx** [comment]
Closing because this is an issue with OP's installation being in a deeply nested folder.
