### ISSUE TITLE
Wildcard tab not showing

### ISSUE THREAD

**Issue by nskn1031** [adieyal/sd-dynamic-prompts#461]
Nice to meet you, I always use it.

The wildcard tab is not displayed and the wildcard functionality is not enabled.

I tried troubleshooting item 3, but although there was an update, there was no particular change.

If you enter __aaa__ at the prompt, it will list the text written inside aaa.txt, so it seems that it is not completely read.
However, even if it is generated in this state, only aaa is displayed in the INFO of the output illustration.

There was no error notation on the console when outputting.

I was able to use it until the other day, so please let me consult.
Thank you.

**Comment by akx** [comment]
Are there any errors in the webui's console output?

Do you have other extensions enabled - and if you do, can you try and disable them to see if one of them is conflicting with this extension?

**Comment by nskn1031** [comment]
thank you.
There were no errors on the console.

I disabled everything except dynamicprompt like this and rebooted, but it didn't show up.
![image](https://github.com/adieyal/sd-dynamic-prompts/assets/122227985/7b931b9e-8180-4b30-a6a2-223483e60340)

**Comment by akx** [comment]
Okay, can you then check your WebUI -> Preferences -> User Interface, to make sure the Wildcard Manager tab hasn't been hidden by Hidden UI Tabs?

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/58669/ad7d7add-1050-4679-9011-56776c1cd986)

**Comment by tenabraex** [comment]
Mine's just dissapeared today on restarting my client too

`Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "E:\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 12, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
  File "E:\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\__init__.py", line 7, in <module>
    from dynamicprompts.generators.jinjagenerator import JinjaGenerator
  File "E:\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\jinjagenerator.py", line 14, in <module>
    from dynamicprompts.jinja_extensions import DYNAMICPROMPTS_FUNCTIONS, PromptExtension
  File "E:\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\jinja_extensions.py", line 8, in <module>
    from jinja2 import Environment, pass_environment
ImportError: cannot import name 'pass_environment' from 'jinja2' (E:\stable-diffusion-webui\venv\lib\site-packages\jinja2\__init__.py)`

**Comment by akx** [comment]
@tenabraex That's a slightly different error, and it means your environment has an incompatible version of Jinja2 installed. Try `pip install -U jinja2` (though that may break some other extension that expects Jinja2 older than 3.0).

**Comment by BunnyViking** [comment]
> @tenabraex That's a slightly different error, and it means your environment has an incompatible version of Jinja2 installed. Try `pip install -U jinja2` (though that may break some other extension that expects Jinja2 older than 3.0).

Ah cheers that makes sense, something else I updated must have broken it.

**Comment by nskn1031** [comment]
> Okay, can you then check your WebUI -> Preferences -> User Interface, to make sure the Wildcard Manager tab hasn't been hidden by Hidden UI Tabs?
> 
> ![image](https://user-images.githubusercontent.com/58669/241535200-ad7d7add-1050-4679-9011-56776c1cd986.png)

Hidden UI Tabs were blank and there were no wildcard items in the dropdown that appeared when selected.

**Comment by perstale** [comment]
> @tenabraex That's a slightly different error, and it means your environment has an incompatible version of Jinja2 installed. Try `pip install -U jinja2` (though that may break some other extension that expects Jinja2 older than 3.0).

Had dynamic prompts not working myself with jinja errors. I did the pip install to no avail. I finally figured out the culprit is jinja 2.11-something was installed and that didnt work with dynamic prompts. replaced it with jinja 2-3.1.2 and it worked again

**Comment by trendland** [comment]
It looks like i also have the same error, it is not showing. First installing the extension. No jinja error, just cannot find the module 

`Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "C:\Users\cyril\Auto1111\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\cyril\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cyril\Auto1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "C:\Users\cyril\Auto1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 8, in <module>
    import dynamicprompts
ModuleNotFoundError: No module named 'dynamicprompts'`

let me know - thank you

**Comment by akx** [comment]
@trendland that means the requirements for the extension aren't installed. They should be automatically installed when the webui starts, but follow the instructions in https://github.com/adieyal/sd-dynamic-prompts/issues/441#issuecomment-1559051108 otherwise.

**Comment by bboyban** [comment]
I also have the same problem, how should I solve it?

**Comment by adieyal** [comment]
Have a look at @aks's comment.

**Comment by FLi79Za** [comment]
Well, it looks like the Inpaint Anything extension uses a different version of Jinja which breaks Dynamic Prompts.

**Comment by akx** [comment]
We now import Jinja things only when needed, which should unbreak things: https://github.com/adieyal/dynamicprompts/pull/92
