### ISSUE TITLE
expected token 'end of print statement', got 'fingers'

### ISSUE THREAD

**Issue by LeoYYG** [adieyal/sd-dynamic-prompts#462]
use this prompt:
A {house|apartment|lodge|cottage} in {summer|winter|autumn|spring}

**Comment by akx** [comment]
There is no "fingers" in that prompt, so I fail to see how an error message could have "fingers". (Maybe your negative prompt does?)

Either way, that's a Jinja2 error - you have enabled Jinja2 templates, but aren't using Jinja2 syntax. 

Refer to https://github.com/adieyal/sd-dynamic-prompts#jinja2-templates to turn it off.
