### ISSUE TITLE
”unlink seed from prompt checkboxes checked” failed to work! When Fixed seed is checked, the wildcard seems to always choose the same prompt, which means the prompt chosen is linked with the seed

### ISSUE THREAD

**Issue by explorerlxy** [adieyal/sd-dynamic-prompts#463]
”unlink seed from prompt checkboxes checked” failed to work! When Fixed seed is checked, the wildcard seems to always choose the same prompt, which means the prompt chosen is linked with the seed. Has anybody found the same problem?

**Comment by evanerichards** [comment]
I also run into this same problem. Can confirm.
