### ISSUE TITLE
Error running process: E:\ai\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py

### ISSUE THREAD

**Issue by because-bot-fed** [adieyal/sd-dynamic-prompts#464]
```
Error running process: E:\ai\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "E:\ai\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "E:\ai\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 449, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "E:\ai\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
  File "E:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 70, in generate
    gen = self._context.sample_prompts(template, 1)
  File "E:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
    command = parse(prompt, parser_config=self.parser_config)
  File "E:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
    tokens = get_cached_parser(parser_config).parse_string(
  File "E:\ai\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 357), (line:3, col:147)
```

On latest a1111 update.

Did the branch check / checkout main / etc - commands referenced in another post to make sure I was really up to date on the latest.

I've uninstalled/reinstalled DP like 10 times now.

For the latest attempt I deactivated it, deleted the folder, deleted venv, deleted python's cache, and archived my main config files for config.json and ui-config.json

Still the error/issue persists.

Also getting double wildcard tabs in the UI even after all that, which I don't know why that's happening or if it's related. 

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/20569547/06d2de80-f388-4d3d-85f2-329a1d69b9d8)

only one tab works, and it displays double the content:

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/20569547/0f4c550b-5f19-4b0e-a166-cedc4258ba58)

I have also re-tested with every single extension besides defaults and SD disabled and same exact error:

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/20569547/49c5d0f6-6a94-471a-aada-400f51b8216e)

**Comment by akx** [comment]
> pyparsing.exceptions.ParseException: Expected end of text, found '_'

Please show us your prompt – this is related to it.

**Comment by because-bot-fed** [comment]
Found the issue based on that clue.

It was the presence of a LORA with a double underscore in the front of it. 


I think I was using this exact prompt before the a1111 update, so I didn't even consider the prompt itself as an issue. 

Can confirm that running it without the lora worked, and editing the file name worked.


Thanks for the help getting this working again. :) 


Any idea what's causing the double wildcard manager tab? 

It's something in either my config.json or ui-config.json I just can't figure out what/why I'd be seeing double tabs. (After figuring out what was causing the error I reverted to the old config files and the double tabs returned lol)

**Comment by because-bot-fed** [comment]
Figured this one out too.

While troubleshooting I backed up "Wildcards" from the DP folder up a level into the extensions folder - this was then detected as an extension and for some reason made another tab appear 

(This one really made no sense because it's literally just a folder with a bunch of text files but mystery solved. Hope this helps someone else in the future XD)
