### ISSUE TITLE
errors while using Magic prompit 

### ISSUE THREAD

**Issue by razorJhon** [adieyal/sd-dynamic-prompts#47]
I am getting this error message while using Magic prompit :

`AttributeError: 'NoneType' object has no attribute 'keys'`

what i want to achieve for example if my prompit is like this` { cat | dog | chicken } in the garden and are { happy | sad }`

what i want to achieve is i get prompits like this

cat in the garden and are happy
cat in the garden and are sad
dog in the garden and are happy
dog in the garden and are sad
chicken in the garden and are happy
chicken in the garden and are sad

and the text file will be the same as the mentioned prompits and when it finish it stops , how can i achieve that ?

**Comment by adieyal** [comment]
I'm not able to re-produce your error. Are you using v0.15.1?

**Comment by razorJhon** [comment]
yes i am using the latest version , i even updated to 0.16.0 but still same error 

![image](https://user-images.githubusercontent.com/78262608/201337209-d3f8a1b5-683e-4121-9718-213aaffa0413.png)

![image](https://user-images.githubusercontent.com/78262608/201337292-1bf02386-1fd9-45d5-87ed-77fa7faa2254.png)

also there is another issue , what if i need to generate all possibilities but with batch size of 1 ? like getting this prompit and generate like mentioned above it would be awesome , because SD only allows 100 Batch size , what if i want to generate more than 100 ? that feature would replace the x/y plot scripts and would be even better than it .

**Comment by adieyal** [comment]
@razorJhon regarding your question about increasing the batch count, see this comment: https://github.com/adieyal/sd-dynamic-prompts/issues/38#issuecomment-1306653323

I'll add this to the README for future users.

**Comment by razorJhon** [comment]
@adieyal yea the batch count works but does the script choose randomly from the prompit when i use the { | } command ? what if i want to generate it one by one , does it work either or is it only randomly ?

**Comment by adieyal** [comment]
That's what Combinatorial generation is for, have a look here: [https://github.com/adieyal/sd-dynamic-prompts/#combinatorial-generation](https://github.com/adieyal/sd-dynamic-prompts/#combinatorial-generation)

**Comment by razorJhon** [comment]
sorry for late response , yea its working but i found an issue in the random prompit {1-3$$op1|op2|op3} doesn't work it just generate the 3 of them instead of using only 1

**Comment by adieyal** [comment]
Are you saying it doesn't work in random mode or combinatorial?
In random mode it would generate one of the following
- op1
- op2
- op3
- op1,op2
- op1,op3
- op2,op1
- op2,op3
- op3,op1
- op3,op2
- op1,op2,op3
- op1,op3,op2
- op2,op1,op3
- op2,op3,op1
- op3,op1,op2
- op3,op2,op1

Range is not supported in combinatorial mode (yet)
so it would probably return
1-3$$op1
op2
op3

Glad you're enjoying the script - I have a lot of fun with it, especially using collections

**Comment by razorJhon** [comment]
yes it looks like this and it doesn't choose random generation from the prompit that was the prompit and results

![image](https://user-images.githubusercontent.com/78262608/201478866-85bc02b3-6628-4f85-b3a5-322272cd5837.png)
![image](https://user-images.githubusercontent.com/78262608/201478907-8411deed-9bff-4885-93ce-8a36f84a4684.png)
![image](https://user-images.githubusercontent.com/78262608/201478971-474f157a-edf5-4a2b-ba78-b0175f46985c.png)

that was the results

**Comment by adieyal** [comment]
I'm closing this issue, but will open another one to enable ranges in combinatorial mode.
