### ISSUE TITLE
Error when using hires fix 

### ISSUE THREAD

**Issue by albertpb** [adieyal/sd-dynamic-prompts#474]
I'm having this error when using hires fix

Traceback (most recent call last):
  File "E:\Stable Difussion\repos\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "E:\Stable Difussion\repos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\Stable Difussion\repos\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "E:\Stable Difussion\repos\stable-diffusion-webui\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "E:\Stable Difussion\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "E:\Stable Difussion\repos\stable-diffusion-webui\modules\processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "E:\Stable Difussion\repos\stable-diffusion-webui\modules\processing.py", line 1055, in sample
    extra_networks.activate(self, self.hr_extra_network_data)
  File "E:\Stable Difussion\repos\stable-diffusion-webui\modules\extra_networks.py", line 82, in activate
    for extra_network_name, extra_network_args in extra_network_data.items():
AttributeError: 'NoneType' object has no attribute 'items'

Automatic1111 git hash 20ae71faa8ef035c31aa3a410b707d792c8203a3

**Comment by akx** [comment]
This is not related to this extension as far as I can see. Please update your `sd-webui-controlnet` extension, and if that doesn't work, we can continue here.

**Comment by albertpb** [comment]
I downloaded Automatic1111 again, only installed sd-dynamic-prompts extension. I applied update and restart ui

Used this settings:

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/8062599/8ce9e3fe-f2dd-492f-a5d8-15e4313e2b97)

and I have the same error 

Error completing request█▎                                                            | 59/880 [00:33<01:01, 13.34it/s]
Arguments: ('task(8unjoxo917eawoe)', 'girl with __hair_color__', '', [], 20, 0, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, True, True, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\alb\Documents\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\alb\Documents\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\alb\Documents\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "C:\Users\alb\Documents\stable-diffusion-webui\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "C:\Users\alb\Documents\stable-diffusion-webui\modules\processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\Users\alb\Documents\stable-diffusion-webui\modules\processing.py", line 1055, in sample
    extra_networks.activate(self, self.hr_extra_network_data)
  File "C:\Users\alb\Documents\stable-diffusion-webui\modules\extra_networks.py", line 82, in activate
    for extra_network_name, extra_network_args in extra_network_data.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by adieyal** [comment]
Does it happen with dynamic prompts disabled? - the error message doesn't reference dynamic prompts at all

**Comment by joaopedrosgs** [comment]
Same here. Does not happen when dynamic prompts is disabled.

**Comment by joaopedrosgs** [comment]
Try with Combinatorial Generation

**Comment by amurorei01** [comment]
The same problem here.

**Comment by akx** [comment]
Okay, I could repro it with Combinatorial Generation turned on, thanks for the tip @joaopedrosgs.

**Comment by akx** [comment]
@joaopedrosgs now that you mentioned it, yes – you can edit your local `dynamic_prompting.py` with the 3 lines in https://github.com/adieyal/sd-dynamic-prompts/pull/483/files and see if that helps. Please report back if you try that out!

**Comment by amurorei01** [comment]
> @joaopedrosgs now that you mentioned it, yes – you can edit your local `dynamic_prompting.py` with the 3 lines in https://github.com/adieyal/sd-dynamic-prompts/pull/483/files and see if that helps. Please report back if you try that out!

It works! Thank you so much!!

**Comment by joaopedrosgs** [comment]
thats weird. It really doesn't fix the issue for me (only the crash).  Are you guys using loras?

**Comment by asagi4** [comment]
@akx the fix from #483 completely breaks using a separate HR prompt; that workaround causes them to be completely ignored.

It also seems to happen when not actually using any features of the extension at all, so it's kind of annoying to have to disable dynamic prompting just to make things work.

**Comment by brimston3** [comment]
I tried to clean up 483 in pr #495. It does a little better and doesn't zorch your hr_prompt or hr_negative_prompt if provided. It does not properly no-op out if there are no dynamic-prompt syntax elements present. And if your extension stack has different prompts per image and one is processed before dynamic-prompts, it may still overwrite the all_hr_prompts/all_hr_negative_prompts.

**Comment by cool-bigdogs-tshirt** [comment]
i know it's not this repo's responsibility to remain compatible with other forks, but i had to do the following to make the latest change compatible with 'SD Next' / vlad's fork, since a lot of these values just weren't there. maybe i'm missing some other addon update or something though.

```diff
diff --git a/sd_dynamic_prompts/dynamic_prompting.py b/sd_dynamic_prompts/dynamic_prompting.py
index 0f04096..6e76f1c 100644
--- a/sd_dynamic_prompts/dynamic_prompting.py
+++ b/sd_dynamic_prompts/dynamic_prompting.py
@@ -68,11 +68,17 @@ def get_prompts(p):
 
 
 def get_hr_prompts(p) -> tuple[str, str]:
-    hr_prompt = p.all_hr_prompts[0] if len(p.all_hr_prompts) > 0 else p.hr_prompt
+    hr_prompt = getattr(p, 'hr_prompt', p.prompt)
+    all_hr_prompts = getattr(p, 'all_hr_prompts', [])
+
+    hr_negative_prompt = getattr(p, 'hr_negative_prompt', p.negative_prompt)
+    all_hr_negative_prompts = getattr(p, 'all_hr_negative_prompts', [])
+
+    hr_prompt = all_hr_prompts[0] if len(all_hr_prompts) > 0 else hr_prompt
     hr_negative = (
-        p.all_hr_negative_prompts[0]
-        if len(p.all_hr_negative_prompts) > 0
-        else p.hr_negative_prompt
+        all_hr_negative_prompts[0]
+        if len(all_hr_negative_prompts) > 0
+        else hr_negative_prompt
     )
 
     return hr_prompt, hr_negative
```

**Comment by akx** [comment]
This should now be fixed, so closing.
