### ISSUE TITLE
ImportError: cannot import name 'pass_environment' from 'jinja2' 

### ISSUE THREAD

**Issue by xfgexo** [adieyal/sd-dynamic-prompts#476]
Looks like after updating [Web-UI Automatic 1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui) to the latest new big release 1.3.0, Dynamic prompt is no longer loading/working for me. Was working perfectly prior to this.

`Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "D:\StableDifusion\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\StableDifusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\StableDifusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "D:\StableDifusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 12, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\__init__.py", line 7, in <module>
    from dynamicprompts.generators.jinjagenerator import JinjaGenerator
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\jinjagenerator.py", line 14, in <module>
    from dynamicprompts.jinja_extensions import DYNAMICPROMPTS_FUNCTIONS, PromptExtension
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\jinja_extensions.py", line 8, in <module>
    from jinja2 import Environment, pass_environment
ImportError: cannot import name 'pass_environment' from 'jinja2' (D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\jinja2\__init__.py)`

**Comment by chuckkay** [comment]
me too

**Comment by xfgexo** [comment]
I have decided to go back to my previous install of Web-UI Automatic 1111. The latest 1.3.0 version still has way to many bugs. My  previous version = Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8 version works just fine.

**Comment by adieyal** [comment]
Try `pip install -U jinja2==3.1`

**Comment by sild928** [comment]
Mine works, but I am getting the following errors and the prompt is only including wildcards in the metadata.  I've done the pip install you suggested but it did nothing.


Startup time: 16.3s (import torch: 5.1s, import gradio: 1.1s, import ldm: 0.5s, other imports: 1.3s, load scripts: 6.8s, create ui: 1.0s, gradio launch: 0.2s).
Error running process: D:\A1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\A1111\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "D:\A1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 449, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "D:\A1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 70, in generate
    gen = self._context.sample_prompts(template, 1)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
    command = parse(prompt, parser_config=self.parser_config)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
    tokens = get_cached_parser(parser_config).parse_string(
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 417), (line:1, col:418)

**Comment by adieyal** [comment]
that looks like an issue with your prompt - could you share it so that I can take a look?

**Comment by sild928** [comment]
> that looks like an issue with your prompt - could you share it so that I can take a look?

I've reinstalled all the extensions I had and it seems to have resolved itself.

**Comment by adieyal** [comment]
@chuckkay  does the suggested command fix your issue?

**Comment by mrink68** [comment]
Got the same problem and error from the original poster : "ImportError: cannot import name 'pass_environment' from 'jinja2'"

Suggested command did not fix the issue for me, still exactly the same error.

**Comment by OldManSimmer62** [comment]
> Try `pip install -U jinja2==3.1`

This helped.

**Comment by akx** [comment]
@chuckkay Um. "Server will restart" and "Libraries loaded" are _not_ status messages that are found in https://github.com/AUTOMATIC1111/stable-diffusion-webui. Are you maybe running a fork?

Either way, something is installing an older, incompatible Jinja2 version – hard to tell what exactly.

**Comment by chuckkay** [comment]
i have a separate question/possible feature request or fix, dont know which... but will post it shortly

**Comment by chuckkay** [comment]
haven't narrowed down the problem yet, very exhausting as it happened again and had to do a fresh install again.. but i thinks its one of these extensions causing the problem:   "sd-webui-neutral-prompt" or  "adetailer"

if anyone else experiencing the problem is using either of these extensions please post a message letting us know

**Comment by chuckkay** [comment]
> @chuckkay Um. "Server will restart" and "Libraries loaded" are _not_ status messages that are found in https://github.com/AUTOMATIC1111/stable-diffusion-webui. Are you maybe running a fork?
> 
> Either way, something is installing an older, incompatible Jinja2 version – hard to tell what exactly.

yes im running vlad fork, but i think it's a conflict with another extension not a problem with vlad's fork

**Comment by HyfyLap** [comment]
> haven't narrowed down the problem yet, very exhausting as it happened again and had to do a fresh install again.. but i thinks its one of these extensions causing the problem: "sd-webui-neutral-prompt" or "adetailer"
> 
> if anyone else experiencing the problem is using either of these extensions please post a message letting us know

I think the extension causing the problem is "sd-webui-inpaint-anything"

I tried to reinstall several versions of jinja (3.1 - 3.1.2 - 2.1 - 2) but the error still there

**Comment by chuckkay** [comment]
> > haven't narrowed down the problem yet, very exhausting as it happened again and had to do a fresh install again.. but i thinks its one of these extensions causing the problem: "sd-webui-neutral-prompt" or "adetailer"
> > if anyone else experiencing the problem is using either of these extensions please post a message letting us know
> 
> I think the extension causing the problem is "sd-webui-inpaint-anything"
> 
> I tried to reinstall several versions of jinja (3.1 - 3.1.2 - 2.1 - 2) but the error still there

Yes I installed that one too,  right before the first time i noticed the problem, but after my first fresh install and everything working, i don’t think i installed inpaint-anything again, I think the problem was "sd-webui-neutral-prompt" or "adetailer".  I could be wrong but i don’t believe i got around to installing inpaint anything again….  It could also be that more then one extension installs something that messes things up with the config.json our ui-config.json files, because the second time it happened, i just deleted those two files and let webui.bat and the installed extension recreate default config files, and then i tweaked the settings to my liking and all is good..

**Comment by voxefx** [comment]
> haven't narrowed down the problem yet, very exhausting as it happened again and had to do a fresh install again.. but i thinks its one of these extensions causing the problem: "sd-webui-neutral-prompt" or "adetailer"
> 
> if anyone else experiencing the problem is using either of these extensions please post a message letting us know

i am having similar issues and also have adetailer installed

**Comment by HyfyLap** [comment]
> > > haven't narrowed down the problem yet, very exhausting as it happened again and had to do a fresh install again.. but i thinks its one of these extensions causing the problem: "sd-webui-neutral-prompt" or "adetailer"
> > > if anyone else experiencing the problem is using either of these extensions please post a message letting us know
> > 
> > 
> > I think the extension causing the problem is "sd-webui-inpaint-anything"
> > I tried to reinstall several versions of jinja (3.1 - 3.1.2 - 2.1 - 2) but the error still there
> 
> Yes I installed that one too, right before the first time i noticed the problem, but after my first fresh install and everything working, i don’t think i installed inpaint-anything again, I think the problem was "sd-webui-neutral-prompt" or "adetailer". I could be wrong but i don’t believe i got around to installing inpaint anything again…. It could also be that more then one extension installs something that messes things up with the config.json our ui-config.json files, because the second time it happened to me, i didn’t actually try a fresh install again, i just deleted those two files and let webui.bat recreate default config files, and then i tweaked the settings for everthing inthe webui to my liking and all is good..

I deleted those 2 files and webui.bat uninstalled my current version of jinja2 that for some reason was -2.11.3- and reinstalled automatically jinja2 -3.1.2- and life is good again haha.

BTW I don't have installed "sd-webui-neutral-prompt" or "adetailer". My other extensions are "sd-webui-controlnet", "a1111-sd-webui-lycoris", "canvas-zoom" and "sd-webui-photopea-embed".

**Comment by akx** [comment]
* `sd-webui-neutral-prompt` doesn't use Jinja and has no dependencies that would, either. https://github.com/search?q=repo%3Aljleb%2Fsd-webui-neutral-prompt+jinja&type=code
* adetailer has a bunch of transitive dependencies, but none of them would force an install of an older jinja2 that I can see: https://gist.github.com/akx/3bb1a7b3731f354acf1e54db7a7bae93

**Comment by akx** [comment]
Closing as stale.
