### ISSUE TITLE
MagicPrompt is broken

### ISSUE THREAD

**Issue by Spaceginner** [adieyal/sd-dynamic-prompts#48]
I am not saying anything, but it is broken:
```
Traceback (most recent call last):
  File "D:\Emergency\Stable Diffusion WebUI\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "D:\Emergency\Stable Diffusion WebUI\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "D:\Emergency\Stable Diffusion WebUI\modules\txt2img.py", line 45, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\Emergency\Stable Diffusion WebUI\modules\scripts.py", line 296, in run
    processed = script.run(p, *script_args)
  File "D:\Emergency\Stable Diffusion WebUI\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 137, in run
    prompt_generator = MagicPromptGenerator(
TypeError: MagicPromptGenerator.__init__() takes 2 positional arguments but 4 were given
```
Steps to reproduce:
1. Turn MagicPrompt on
2. Write some initial text (not sure it is needed)
3. Start generation

Why do you send it more arguments than needed?

**Comment by adieyal** [comment]
Could you confirm which version you are using?

**Comment by Spaceginner** [comment]
0.16.0, latest. downloaded from extensions tab

**Comment by adieyal** [comment]
I'm not sure why you're seeing that error. From your stack trace, here is the line that generates the error
https://github.com/adieyal/sd-dynamic-prompts/blob/main/scripts/dynamic_prompting.py#L137

and here is the constructor of the MagicPrompt generator:
https://github.com/adieyal/sd-dynamic-prompts/blob/main/prompts/generators/magicprompt.py#L34

The constructor accepts two positional arguments and another two optional arguments. Your error message complains that that is not correct. Could you please double-check prompts/generators/magicprompt.py and compare it to https://github.com/adieyal/sd-dynamic-prompts/blob/main/prompts/generators/magicprompt.py - perhaps the extension wasn't completely updated?

**Comment by ClashSAN** [comment]
@Spaceginner recommends some code improvements for MagicPrompt from the script https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4526

**Comment by Spaceginner** [comment]
I actually completely reinstalled extension, I also thought it didn't completely updated. I just pulled some commit via vscode while was copypasting code.

**Comment by Spaceginner** [comment]
> @Spaceginner recommends some code improvements for MagicPrompt from the script [AUTOMATIC1111/stable-diffusion-webui#4526](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4526)

Actually I am not sure it will freeze pc yet, cuz I can't even launch MagicPrompt

**Comment by Spaceginner** [comment]
So, copypasting code or pulling commit helped and now it downloads model and all other staff.

**Comment by adieyal** [comment]
So, is it resolved?

**Comment by Spaceginner** [comment]
I guess so

**Comment by Spaceginner** [comment]
It did't freeze my pc, btw.
