### ISSUE TITLE
bug report : ModuleNotFoundError: No module named 'sd_dynamic_prompts'

### ISSUE THREAD

**Issue by ericcartmanfatass** [adieyal/sd-dynamic-prompts#486]
Dear developer, i've update the latest version and reinstall this plugin twice, the error still there:

```
Error running install.py for extension C:\Program Files\stable-diffusion-webui\extensions\sd-dynamic-prompts.
Command: "C:\Program Files\stable-diffusion-webui\py310\python.exe" "C:\Program Files\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py"
Error code: 1
stderr: Traceback (most recent call last):
  File "C:\Program Files\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py", line 7, in <module>
    from sd_dynamic_prompts.utils import get_logger
ModuleNotFoundError: No module named 'sd_dynamic_prompts'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
```

**Comment by ericcartmanfatass** [comment]
im sry the new version(v2.12.0) didnt fixed for my webui, the error was still occured and it was weird that the version i update from git is still the older version,so i download the code and put it in the extensions folder...

**Comment by HyperTwo** [comment]
same problem, edit the install.py in "novelai-webui\extensions\sd-dynamic-prompts"
Add the code as follow:

import sys
sys.path.append(r"**the absolute path of your own webui folder**\extensions\sd-dynamic-prompts")

save and restart webUI, it seems to be the problem about PYTHONPATH, although it can solve the problem without reporting an error, a lot of things will pop up when starting up, hope fix it

**Comment by akx** [comment]
Ah, darnit, I didn't realize the webui launcher doesn't fix up the path when running `install.py` like it does when loading a script proper. Will fix.

**Comment by HyperTwo** [comment]
actually, this error does not affect use

**Comment by adieyal** [comment]
@akx perhaps we should manually update the PYTHONPATH if the import fails
