### ISSUE TITLE
Errors when loading SD

### ISSUE THREAD

**Issue by ArtificialOtaku** [adieyal/sd-dynamic-prompts#49]
I'm getting these errors when loading StableDiffusion, not sure what they're affecting specifically, so i thought I'd share them with you to see if you know more about this. Thanks in advance for your assistance in this. 

![Untitled](https://user-images.githubusercontent.com/116858296/201416380-dfe73916-d562-4d24-8773-15b98c1d9154.jpg)

**Comment by adieyal** [comment]
You might be looking at an old version - could you try to update to 0.16.0 and let me know if you're still seeing the error?

**Comment by ArtificialOtaku** [comment]
Yeah, I was doing  a manual installation, and I hadn't copied the helptext.html file into the main SD folder. Everything is fine now, thanks for your attention.
