### ISSUE TITLE
No new prompts generated if using batch size/count or combinatorial generator

### ISSUE THREAD

**Issue by SteMoeller** [adieyal/sd-dynamic-prompts#491]
Not sure why a complete other error (requirements.txt missing) comes up in this (https://github.com/adieyal/sd-dynamic-prompts/issues/484) issue ... it has nothing to do with the problem that I cannot use the wildcards or even the change between different prompts without wildcards in dynamic prompts... so the dynamic part is mostly away... using {dog | cat} as prompt I either get only dogs or only cats, no matter what batch size, batch count or combinatorial things I use... 

So WHY EXACTLY has this been closed due to the requirements.txt missing? 

The error still exists on my system... I am waiting for some kind of possibility to add log messages to some python files to better be able to find the problem... 

Where exactly is the place when the current prompt is selected within all_prompts? It does not seem to happen in the sd-dynamic-prompts codebase but in dynamic-prompts as far as I saw...

Just installed the vlad version auf automatic1111: no bugs, dynamic prompts work as expected...

**Comment by adieyal** [comment]
Closing as stale
