### ISSUE TITLE
HR prompt stuff not compatible with webui forks

### ISSUE THREAD

**Issue by akx** [adieyal/sd-dynamic-prompts#497]
i know it's not this repo's responsibility to remain compatible with other forks, but i had to do the following to make the latest change compatible with 'SD Next' / vlad's fork, since a lot of these values just weren't there. maybe i'm missing some other addon update or something though.

```diff
diff --git a/sd_dynamic_prompts/dynamic_prompting.py b/sd_dynamic_prompts/dynamic_prompting.py
index 0f04096..6e76f1c 100644
--- a/sd_dynamic_prompts/dynamic_prompting.py
+++ b/sd_dynamic_prompts/dynamic_prompting.py
@@ -68,11 +68,17 @@ def get_prompts(p):
 
 
 def get_hr_prompts(p) -> tuple[str, str]:
-    hr_prompt = p.all_hr_prompts[0] if len(p.all_hr_prompts) > 0 else p.hr_prompt
+    hr_prompt = getattr(p, 'hr_prompt', p.prompt)
+    all_hr_prompts = getattr(p, 'all_hr_prompts', [])
+
+    hr_negative_prompt = getattr(p, 'hr_negative_prompt', p.negative_prompt)
+    all_hr_negative_prompts = getattr(p, 'all_hr_negative_prompts', [])
+
+    hr_prompt = all_hr_prompts[0] if len(all_hr_prompts) > 0 else hr_prompt
     hr_negative = (
-        p.all_hr_negative_prompts[0]
-        if len(p.all_hr_negative_prompts) > 0
-        else p.hr_negative_prompt
+        all_hr_negative_prompts[0]
+        if len(all_hr_negative_prompts) > 0
+        else hr_negative_prompt
     )
 
     return hr_prompt, hr_negative
```

_Originally posted by @cool-bigdogs-tshirt in https://github.com/adieyal/sd-dynamic-prompts/issues/474#issuecomment-1574256067_

**Comment by vladmandic** [comment]
@akx thanks!
btw, those new fields were introduced in a1111 v1.3 and actually still has some issues/regressions, that's why i haven't ported the code yet (for example, it breaks xyz scripts as cached values remain regardless of xyz values). once issues are resolved, i'll port it to my fork as well.
