### ISSUE TITLE
Strange lines in console

### ISSUE THREAD

**Issue by mikheys** [adieyal/sd-dynamic-prompts#499]
Good night! Please tell me, when starting the SD, these lines appear in the console every time.

Is this normal or can I fix it somehow? when the sd-dynamic-prompts extension is disabled, these lines disappear.

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/34010273/9c9dc829-4e3e-4b02-9842-6850a04a2a57)

**Comment by GitGod76** [comment]
Me too, these things look really annoying

**Comment by adieyal** [comment]
That isn't a bug but I agree that it is excessively noisy.

**Comment by akx** [comment]
Hmmh, that should only happen when there are out-of-date dependencies, not every time.

**Comment by mikheys** [comment]
It happens to me every time I start((

**Comment by jebarpg** [comment]
Same happens every time for me as well.
