### ISSUE TITLE
Wildcard files containing seeds?

### ISSUE THREAD

**Issue by cgessai** [adieyal/sd-dynamic-prompts#5]
Really loving this script- Is there any way we can have a wildcard file with seeds in it?  In IMG2IMG I tried with prompt "(blah blah), Seed: __seedlist__" and it used the seed listed in the "seed" field in the UI, instead.  I would really love a way to control the seed used via prompt and, of course, use a wildcard file for them....if any of that's at all possible.  Thanks!

**Comment by adieyal** [comment]
I'll look into it

**Comment by johneliot1978** [comment]
think this would be useful as well. Also just wanted to say a big thank you for your work on dynamic prompting script. It's amazing! and I use it constantly. much appreciate your efforts :)

**Comment by adieyal** [comment]
Can you give me an idea of your use case? Why would it help to set the seed in the prompt? If I can understand the requirement better, I might be able to develop something more generally useful. 

I think both of these issues are requesting something similar:

- https://github.com/adieyal/sd-dynamic-prompting/issues/14
- https://github.com/adieyal/sd-dynamic-prompting/issues/25

**Comment by stysmmaker** [comment]
Related to the comment I made in #14, I've added initial support for this in my randomization extension. Maybe this is what you're looking for? @cgessai @johneliot1978
https://github.com/stysmmaker/stable-diffusion-webui-randomize

**Comment by adieyal** [comment]
I'm closing this issue because the randomize script addresses it. Since both scripts are set as AlwaysVisible, they are compatible with each other.
