### ISSUE TITLE
[Feature Request] Add sequential order

### ISSUE THREAD

**Issue by Gh20221205** [adieyal/sd-dynamic-prompts#505]
Random order is great, but sometimes I just want to have some control over the order, for instance, I want to do a side by side comparison of several character loras. I have saved these loras in lora.txt, but since the row is randomly picked, sometimes I have trouble linking character to lora used. If there is an option of sequential order, it will be straightforward. Another scenario is that I want to have control over lora used for each face in a group picture.

So can you add an option to allow sequential order, something like,  `||lora||` will pick a row from the first to last in sequential order (feature requested) while `__lora__` will pick a random row from lora.txt (current feature)?

Thanks!

**Comment by akx** [comment]
Have you tried [combinatorial generation](https://github.com/adieyal/sd-dynamic-prompts#combinatorial-generation)?

**Comment by Gh20221205** [comment]
> Have you tried [combinatorial generation](https://github.com/adieyal/sd-dynamic-prompts#combinatorial-generation)?

It seems to me that combinatorial generation or simply X/Y/Z plot can be used in generating individual image with one character per image (and then merge into one bigger image as in X/Y/Z plot).

I just added another scenario in the request above where I want to generate group picture. Can combinatorial generation help me with that? Thanks.

**Comment by Gh20221205** [comment]
Great, it works! Thank you!
