### ISSUE TITLE
Where should I download the Magic prompt model myself?

### ISSUE THREAD

**Issue by qq164074954** [adieyal/sd-dynamic-prompts#507]
![1685937528983](https://github.com/adieyal/sd-dynamic-prompts/assets/16794221/3416a445-ac46-4416-bbd6-d90ed9eaef60)

The automatic download of Gustavosta/MagicPrompt-Stable-Diffusion failed. I want to try to download the model manually, but I don’t know where to put the model. Please tell me where to put it

**Comment by FMIKASAEREN** [comment]
where?
