### ISSUE TITLE
Is there a way of generating a number of images from a set of random prompt?

### ISSUE THREAD

**Issue by msqiqi10** [adieyal/sd-dynamic-prompts#508]
Say I have __Extremely beautiful clothes__, and if I want to generate 10 images instead of 1 image from each prompt randomly chosen from the wildcard?
Is there a way of doing that?

**Comment by akx** [comment]
Set the Batch count to 10 and ensure you _don't_ have "Combinatorial generation" on (and haven't set a specific seed).
