### ISSUE TITLE
Implement ranges in combinatorial mode

### ISSUE THREAD

**Issue by adieyal** [adieyal/sd-dynamic-prompts#51]
Combinatorial mode does not work with ranges.

Example: `{1-2$$red|blue}`
Expected:
- red
- blue
- red,blue

Actual
- 1-2$$red
- blue

**Comment by razorJhon** [comment]
thank you so much , it would be very helpful if this gets fixed , this script actually can replace alot of scripts in stable diffusion scripts , good job on doing this possible :)

**Comment by razorJhon** [comment]
its working now but is it possible to remove the 1-2$$ from the prompit because it generates random thing if the 1-2$$ presents

**Comment by razorJhon** [comment]
the Combinatorial doesn't work anymore in version 0.20 , it still generate as its a normal prompit when u use {1-3$$blue|red|green} also if it chooses the first array it adds 1-3$$blue inside the prompit

**Comment by adieyal** [comment]
Isn't that the same issue as before? Combinatorial doesn't yet support the $$ syntax. I'll fix it when I get the chance. In the meanwhile,  you might be interested in the jinja2 templates [https://github.com/adieyal/sd-dynamic-prompts#permutations](https://github.com/adieyal/sd-dynamic-prompts#permutations) - they have a more complicated syntax but give you a lot more flexibility.

**Comment by razorJhon** [comment]
its a bit complicated if i want to do more than 1 combination , if the combinatorial is fixed it will be alot easier for the prompit ^^

**Comment by adieyal** [comment]
I know this is an old issue, but you might be interested to know that ranges are now finally supported in combinatorial mode as of 1.5.0. Note, the prompt parser has been completely re-written and so there may be a few teething problems

**Comment by ghostsquad** [comment]
The README still says 

```
Combinations are not yet supported, i.e. {2$$a|b|c} will treat 2$$a as one of the options instead of selecting two of a, b and c.
```

**Comment by ghostsquad** [comment]
I came here looking for a way to do something like what X/Y/Z prompt matrix does, e.g.

```
4-7 (+1)
```
or
```
8-5 (-0.05)
```

I can open a new feature request, or are you recommending jinja2 instead?

**Comment by adieyal** [comment]
> I came here looking for a way to do something like what X/Y/Z prompt matrix does, e.g.

Do you mean X/Y/Z Plot?

Do you think it's a common use case do want a configurable increment?

**Comment by ghostsquad** [comment]
> > I came here looking for a way to do something like what X/Y/Z prompt matrix does, e.g.
> 
> Do you mean X/Y/Z Plot?
> 
> Do you think it's a common use case do want a configurable increment?

Yes, X/Y/Z Plot. I use the ranging often with that, and recently started writing `(foo:1.{1|2|3|4})` to generate combinations of weights and I thought it would be nice for some syntax for range+increment.
