### ISSUE TITLE
Installed but missing

### ISSUE THREAD

**Issue by Boymerkz** [adieyal/sd-dynamic-prompts#53]
The exstion is installed but is no longer showing in the drop down menu after 0.15<  just updated from 0.14 which did show in the menu

**Comment by Boymerkz** [comment]
Issue solved, i found it above, is there a way to manually move this back to the dropdown menu

**Comment by adieyal** [comment]
Why do you want it back in the drop down? The benefit of the change allows you to use the script in conjunction with others, e.g. X/Y plot and randomize

**Comment by chifeisoong** [comment]
Hi, 0.16.0 not working, the tab and dropdowns are visible , but it wouldn't register the __XXX__ prompt pattern to the wildcards, was ok in previous 0.15,0  before upgrade,

**Comment by chifeisoong** [comment]
> Hi, 0.16.0 not working, the tab and dropdowns are visible , but it wouldn't register the _ _XXX_ _ prompt pattern to the wildcards, was ok in previous 0.15,0 before upgrade,

seems like a conflict issue with Unprompted extension, dynamic prompting now works after i disabled unprompted

**Comment by adieyal** [comment]
Looks like there is a lot of overlap between Dynamic Prompts and Unprompted - I'm curious what you think the difference is and why you're using both instead of just one of them.

**Comment by chifeisoong** [comment]
> Prompts and Unprompted - I'm curious what you think the difference is and why you're using both instead of just one of them.

I was trying out both, I prefer dynamic-prompt now :D , unprompted is too complex
