### ISSUE TITLE
Wildcards dont work if you are using Batch images ( Not related to controlnet!)

### ISSUE THREAD

**Issue by StableInfo** [adieyal/sd-dynamic-prompts#532]
(this is NOT related to controlnet)
I regret updating the extension,
I have a prompt with wildcards, and I like to run them through a batch and check the various results at the end, 
except now, today, I noticed all my 500 images had the same positive prompt (where my wildcards were), it was supposed to be all 500 differents prompts thands to the wildcards, what happened? Any fix to this?

I really HATE THIS.

**Comment by akx** [comment]
> I regret updating the extension,

So downgrade the extension to a version that works for you.

Anyway, please tell us which version of the webui you're running, which version of the extension you're running, and your prompt and your settings (e.g. Fixed seed, etc.).

**Comment by StableInfo** [comment]
I am not familiar with downgrading, I just go to the extention tab in the webUI of automatic (vlad version which is the same anyway), and select "check for updates" then i confirm. How can I downgrade it?
As for version:
Dynamic prompt: 45b21373 (Sat Jun 3 10:48:47 2023)
WebUi: 
![image](https://github.com/adieyal/sd-dynamic-prompts/assets/136593585/ff36555b-0d66-4df8-a813-dad4343ba959)

I wonder if the problem was not introduced somehow by other extentions, I just installed 7 or so at once.
Did the text paramateres files contain the added part describing the template used (the text containing the wildcards before turning into a functional prompt)? Cuz that was new since I updated everything, today. Wonder if thats related to dynamic prompts or from another extension somehow (unlikely).

**Comment by akx** [comment]
You downgrade by opening the command prompt/terminal in the `extensions/sd-dynamic-wildcards` directory and running e.g. `git checkout 5349e0eb45af1ff69c31f71729b3e2777e1ed06e` (see https://github.com/adieyal/sd-dynamic-prompts/commits/main for the commit IDs).

It's entirely possible another extension is messing with things.

**Comment by StableInfo** [comment]
You dont have this behaviour yourself? I am the only one?

**Comment by akx** [comment]
With a prompt `__nsp/nsp/animals__`, and batch count 3, batch size 2, I get this result grid – so yeah, no, I can't reproduce this out of the box:

![grid-0000](https://github.com/adieyal/sd-dynamic-prompts/assets/58669/f458a57a-7959-49c3-9db9-3f7abe4ac8f3)

**Comment by StableInfo** [comment]
Removed there 3, and I no longer have this problem, I think it's most likely tokenizer, the 3 extensions:
1) Tokenizer
2) llul
3) ADetailer

**Comment by akx** [comment]
@StableInfo Glad you got it fixed. If you mean https://github.com/AUTOMATIC1111/stable-diffusion-webui-tokenizer/tree/master, I don't think it's that – it doesn't seem to be doing anything related to actual prompt generation.
