### ISSUE TITLE
Magic Prompt breaks automatic1111 built in Alternating Words

### ISSUE THREAD

**Issue by dhstsw** [adieyal/sd-dynamic-prompts#54]
If you write a prompt like:

a painting of [Eva Green|Scarlett Johanson|deborah ann woll|Emily Blunt]

and activate Magic Prompt, the resulting rendered prompt will be:

a painting of [Eva Green, Scarlett Johanson, deborah ann woll, Emily Blunt]

switching the "|" with a comma ",".

That will result in multiple subjects instead of an alternated one.

Version: should be a729de9 (it's *not* in the scripts dropdown)

**To Reproduce**
see above.

Only magic prompt checkbox has been set.

Cheers.

**Comment by adieyal** [comment]
Thanks - let me know if you encounter any more problems

**Comment by 0xspeedrunner** [comment]
Hi, not sure if this is the same issue, but this syntax breaks for me: `[{2-4$$|$$__photographers__}]`

I'm trying to use Alternating Words in the form of `[Foo|Bar|Baz]` and populate them with wildcards.

Is this possible or am i doing something wrong?

**Comment by adieyal** [comment]
> Hi, not sure if this is the same issue, but this syntax breaks for me: `[{2-4$$|$$__photographers__}]`
> 
> I'm trying to use Alternating Words in the form of `[Foo|Bar|Baz]` and populate them with wildcards.
> 
> Is this possible or am i doing something wrong?

Different bug - but should be fixed now - please let me know if it isn't
