### ISSUE TITLE
A way to enable globally

### ISSUE THREAD

**Issue by knoopx** [adieyal/sd-dynamic-prompts#55]
It would be nice if the extension could be globally enabled using a toggle in the settings instead of having to choose from plugins. Less cumbersome and also allows you to use dynamic prompts within other scripts.

**Comment by adieyal** [comment]
That is currently the case, are you using a recent version of the script, i.e. >= 0.17.0?

**Comment by keiex** [comment]
> That is currently the case, are you using a recent version of the script, i.e. >= 0.17.0?

i think he means the wildcards, when you have dynamic prompts enabled, UnivAICharGen breaks, also the wildcards extension breaks too

**Comment by adieyal** [comment]
Added a checkbox in 0.21.0
