### ISSUE TITLE
cant enable script. it does not work either

### ISSUE THREAD

**Issue by MimiVRC** [adieyal/sd-dynamic-prompts#56]
you used to use the script drop down but it is no longer found there. it also doesn't work either so it's not just globally enabled (plus even if it was, because it's not in the drop down it has no options or settings)

**Comment by MimiVRC** [comment]
for anyone coming looking for this in the future, it is a drop down right above the scripts drop down now

**Comment by adieyal** [comment]
The extension now works in AlwaysVisible mode [https://github.com/adieyal/sd-dynamic-prompts#alwaysvisible](https://github.com/adieyal/sd-dynamic-prompts#alwaysvisible) - the benefit of this is that it is compatible with another of other extensions - [https://github.com/adieyal/sd-dynamic-prompts#compatible-scripts](https://github.com/adieyal/sd-dynamic-prompts#compatible-scripts)
