### ISSUE TITLE
First load of MagicPrompt may take a while.

### ISSUE THREAD

**Issue by zdoek001** [adieyal/sd-dynamic-prompts#563]
Is there a general way to download, download their own folder, rather than automatic download, I have never been successful automatic download

**Comment by adieyal** [comment]
Have a look at these instructions - [https://huggingface.co/docs/hub/models-downloading](https://huggingface.co/docs/hub/models-downloading)

Here is the complete list of models being used - [https://github.com/adieyal/sd-dynamic-prompts/blob/main/config/magicprompt_models.txt](https://github.com/adieyal/sd-dynamic-prompts/blob/main/config/magicprompt_models.txt)
