### ISSUE TITLE
Immediate Evaluation variables don't work with batch size or batch count > 1

### ISSUE THREAD

**Issue by zymox** [adieyal/sd-dynamic-prompts#566]
When using variables with immediate evaluation (with "!"), using batch count or batch size > 1 results in every generated prompt being the same. 

It seems like the first evaluation sets it for the entire batch + all following batches, which must surely be a bug?

**Example:**

```
${nationality=!__nationality__}${name=!__girl_name__}
${nationality} woman named ${name} standing in a park
```
Run with batch count = 4 results in 4 times "american woman named Stephani standing in a park" for me.

**Comment by jdietzChina** [comment]
same

**Comment by Northguard3885** [comment]
I have the same issue. Using various options in the setting for shuffling or clearing the cache or unlinking from the seed has no effect, the variable is evaluated once and only once for each click of the Generate button.

**Comment by AIrtistry** [comment]
still no fix to this issue ?

**Comment by adieyal** [comment]
I think this is a duplication of #517 - closing this issue in favour of that one.
