### ISSUE TITLE
[request] weight to wild card lines

### ISSUE THREAD

**Issue by MimiVRC** [adieyal/sd-dynamic-prompts#57]
it would be nice if we had a way to add a weight to lines of a wild card instead of copying and pasting that same line multiple times
example: 

hot[9]
cold[9]
freezing[3]
burning[3]
on fire
frozen

this could make hot 3 times as likely as freezing and freezing 3 times as likely as frozen
in addition to this, something we can put on the line that is nothing, for the chance to get no selection and control that chance with a weight

**Comment by adieyal** [comment]
You can currently do this inline with [jinja2 templates](https://github.com/adieyal/sd-dynamic-prompts#jinja2-templates) (just be sure to check the enable Jinja2 templates checkbox)

If you want blue 30% of the time, red 60% of the time (0.9 - 0.3), and yellow 10% of the time (1 - 0.9)
e.g.

    {% with r = random() %}
        {% for val, weight in [('blue', 0.3), ('red', 0.9), ('yellow', 1)] %}
            {% if r < weight %}
                {% prompt %}{{ r }} I love {{ val }} roses{% endprompt %}
            {% endif %}
        {% endfor %}
    {% endwith %}

or

    {% set ns = namespace(r=random(), chosen=false, total=0) %}
    {% for val, weight in [('blue', 0.3), ('red', 0.6), ('yellow', 0.1)] %}
        {% set ns.total = ns.total + weight %}
        {% if ns.r < ns.total and ns.chosen==false %}
            {% prompt %}I love {{ val }} roses{% endprompt %}
            {% set ns.chosen = 1 %}
        {% endif %}
    {% endfor %}

Not sure if it makes sense to do it inside of wildcard files

**Comment by adieyal** [comment]
Does the above suggestion work for you? I know it's more complicated than the basic syntax, but it seems that the use case is quite niche so probably not worth adding more complexity to the regular syntax
