### ISSUE TITLE
"Dynamic Prompts enabled" at startup creates problems, why can't we choose?

### ISSUE THREAD

**Issue by StudioDUzes** [adieyal/sd-dynamic-prompts#575]
Thank's for your work...

**Comment by pmcculler** [comment]
Wait, you can't choose? What's the issue?

**Comment by StudioDUzes** [comment]
normally an extension is off and we choose to activate it, not the opposite ???

**Comment by adieyal** [comment]
I think it's auto's responsible for managing state. It should remember your settings. As a workaround, have a look in `ui-config.json`, search for '/txt2img/Dynamic Prompts enabled/value"' and change the setting to false. Then restart auto and DP should be disabled by default.
