### ISSUE TITLE
ImportError: cannot import name 'FeelingLuckyGenerator'

### ISSUE THREAD

**Issue by Jonseed** [adieyal/sd-dynamic-prompts#58]
**Describe the bug**
When I updated the extension, I got this error in the terminal.

```
ImportError: cannot import name 'FeelingLuckyGenerator' from 'prompts.generators' (F:\repos\auto111\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generators\__init__.py)
```

**Version used**
Dynamic Prompts doesn't show in the scripts dropdown. But I just updated.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Updated extension
2. Saw error in terminal

**Comment by adieyal** [comment]
Thanks for reporting this - I don't understand why it's happening. Is that the entire error message?

Regarding it not showing in the scripts dropdown, you should see it above the dropdown in its own section called Dynamic Prompts.

Do you by any change have an old version of the script in another folder? Perhaps under a different name in extensions or in the scripts folder?

**Comment by Jonseed** [comment]
I stopped and restarted the server, and I don't see the error anymore. So maybe it was because the server was running?

I do see the new scripts dropdown.

I don't have another version of the script or extension.

**Comment by Jonseed** [comment]
Since I don't see this error anymore, I'm closing this. Perhaps it was because the server was already running, and had to be restarted.

**Comment by adieyal** [comment]
thanks - re-open if you see it again.
