### ISSUE TITLE
Combinatorial Generation is ignored

### ISSUE THREAD

**Issue by Parayia** [adieyal/sd-dynamic-prompts#581]
Hey, i've downloaded the updated version of dynamic Prompts through A1111. 
Since then i recognized a weird behavior. I'm not sure if DP doesn't work at all or just ignores combinatorial batches.
Already reinstalled it and did some troubleshooting, but nothing helps :)
Getting an Errormessage in Console (the one you see on the screenshot) 

Help would be appreciated! :)

![Bild_2023-07-31_134958750](https://github.com/adieyal/sd-dynamic-prompts/assets/141032231/004ed538-6e8b-4cf1-9fb6-54ccc5bcf766)

**Comment by akx** [comment]
That means your prompt (which you're not showing us here) is somehow invalid, and didn't get processed.

**Comment by Parayia** [comment]
Well, thats my prompt. 
The funny thing is, it worked once but stopped after i restarted.
Maybe someone can tell meh what's invalid about it. Maybe i changed something i don't see :D .
Could that be the reason why, combinatorial generations don't work?

![Bild_2023-07-31_153512189](https://github.com/adieyal/sd-dynamic-prompts/assets/141032231/8e0a4dd5-939e-4f09-9b23-dfa0d11a7236)

**Comment by Parayia** [comment]
> That means your prompt (which you're not showing us here) is somehow invalid, and didn't get processed.

Well, thats my prompt. 
The funny thing is, it worked once but stopped after i restarted.
Maybe someone can tell meh what's invalid about it. Maybe i changed something i don't see :D .
Could that be the reason why, combinatorial generations don't work?

![Bild_2023-07-31_153512189](https://github.com/adieyal/sd-dynamic-prompts/assets/141032231/8e0a4dd5-939e-4f09-9b23-dfa0d11a7236)

**Comment by akx** [comment]
It looks like `Clothes/Female_Clothes_CM__` should probably be `__Clothes/Female_Clothes_CM__`.

The error message is pointing towards a mismatched `__`.

**Comment by Parayia** [comment]
> It looks like `Clothes/Female_Clothes_CM__` should probably be `__Clothes/Female_Clothes_CM__`.
> 
> The error message is pointing towards a mismatched `__`.

Jesus ... i'll try that at home later. I just wanna give myself a facepalm with a chair :D thanks ..

**Comment by Parayia** [comment]
Well...seems like you were right. Thank you.
