### ISSUE TITLE
What does "Automatically purge wildcard cache on every generation." do?

### ISSUE THREAD

**Issue by pmcculler** [adieyal/sd-dynamic-prompts#586]
I may have missed where this is documented, sorry.

**Comment by pmcculler** [comment]
if self._auto_purge_cache:
            self._wildcard_manager.clear_cache()

Is this like going and hitting "Refresh Wildcards" every generation?

**Comment by adieyal** [comment]
I've added an explanation in the documentation. https://github.com/adieyal/sd-dynamic-prompts#wildcard-settings

Essentially, the Wildcard Manager caches wildcard resolution for performance purposes. However, if you update your wildcard file, it won't reflect until you restart Auto1111. You can set this option to automatically purge the cache inbetween generations. You still get some performance benefits by doing this.

**Comment by pmcculler** [comment]
Thanks, I saw you added a PNG to the documentation, but I don't see how the purge functionality is documented, per se?
