### ISSUE TITLE
randomize sampler and upscaler

### ISSUE THREAD

**Issue by hellomynameisleo** [adieyal/sd-dynamic-prompts#587]
Is there a way to randomize the sampler and upscaler? For example if you wanted dynamic prompt to randomly choose between DPM++ 2M SDE or DPM++ SDE KARRAS and choose any upscaler randomly

**Comment by pmcculler** [comment]
If you want it random, try the randomizer plugin. https://github.com/innightwolfsleep/stable-diffusion-webui-randomize - or perhaps the XYZ script does what you need? That might be more deterministic than you're hoping for based on your question though.

**Comment by hellomynameisleo** [comment]
> If you want it random, try the randomizer plugin. https://github.com/innightwolfsleep/stable-diffusion-webui-randomize - or perhaps the XYZ script does what you need? That might be more deterministic than you're hoping for based on your question though.

the plugin seems to randomize everything though, maybe if it had a selection which it could select what I can randomize and add in which samplers to randomize would be good

**Comment by pmcculler** [comment]
It does not have to randomize everything, try it out. Lock down a dimension by giving it only one value to randomize against, for example. Or perhaps contact the author with your request.

**Comment by adieyal** [comment]
Randomizing settings is out of scope for dynamic prompts. I considered it early on but that functionality is best implemented elsewhere. The XYZ script is very good.
