### ISSUE TITLE
[Feature Request] Conditional variables (if statements)

### ISSUE THREAD

**Issue by Nrgte** [adieyal/sd-dynamic-prompts#589]
It would be nice to have an option to check for the value of a variable and set another variable based on that.

For example: 

If ${season} == "winter" {${dress_color=!blue}}

or even fancier:

${season_nr=!{1|2|3|4}}

if ${season_nr}==1 
{
${season=!winter};
${dress_color=!blue};
${background=!snow}
}

Thanks!

**Comment by akx** [comment]
You can do this with [Jinja2 templates](https://github.com/adieyal/sd-dynamic-prompts/blob/main/jinja2.md) now – coming up with a syntax for the default template language that wouldn't interfere with natural text would probably end up being a bit messy...

**Comment by Nrgte** [comment]
I always disregarded this because it's marked as an experimental feature. I'll give it a try. Thanks!

**Comment by adieyal** [comment]
Fixed - no longer experimental :)

You can do something like
```
{% with season = choice("winter", "summer") %}
    {% set dress_color = "blue" if season == "winter" else "red" %}
    A fashion model wearing a {{ dress_color }} dress
{% endwith %}
```
