### ISSUE TITLE
Write prompt to file error

### ISSUE THREAD

**Issue by izacca** [adieyal/sd-dynamic-prompts#59]
**Describe the bug**

INFO:dynamic_prompting.py:Prompt matrix will create 8 images in a total of 8 batches.
ERROR:dynamic_prompting.py:Failed to write prompts to file: 'charmap' codec can't encode character '\u0142' in position 1208: character maps to <undefined>

**Version used**
Dynamic-prompt extension 0.25.0

think is due to my artist.txt wildcard file that contain nord-european painter with Ä (142 in my charmap) in their name. 
some google search suggest it correspond to this polish char: ł

**Comment by izacca** [comment]
[photographers.txt](https://github.com/adieyal/sd-dynamic-prompts/files/10012212/photographers.txt)

in line 1201 u will find `ł`  in upper and lowercase

**Comment by adieyal** [comment]
Could you please test? I couldn't reproduce the error but my locale is probably different to yours.

**Comment by izacca** [comment]
> Could you please test? I couldn't reproduce the error but my locale is probably different to yours.

tested with an artists file filtered only on names with "strange" characters and works very well. Nice work again.
