### ISSUE TITLE
Batch count and size is multiplied by itself 

### ISSUE THREAD

**Issue by Olivmamman** [adieyal/sd-dynamic-prompts#594]
While Dynamic prompts is active the Batch count and size is multiplied by itself resulting in exponential more images.

Batch count: 1 / size: 2 = 4 images
Batch count: 2 / size: 1 = 4 images
Batch count: 2 / size: 2 = 16 images

I have 
- Turned off all extensions
- Run UI in safe mode
- Resetting to default
- Rebooted the computer
- Removed cookies
narrowed it down to Dynamic prompts

UI: SDnext (Vlad's fork)
Version: 83d1ee77 Sun Aug 13 00:32:03 2023 +0200

**Dynamic prompts inactive**
![Screenshot_814](https://github.com/adieyal/sd-dynamic-prompts/assets/142082309/1ce01e83-5f49-4998-ba71-dd66b6a68091)

**Dynamic prompts active Batch count: 1 / size: 2 = 4 images**
![Screenshot_812](https://github.com/adieyal/sd-dynamic-prompts/assets/142082309/a8785364-4206-4c5e-b246-d5aad3d9838a)

Best regards,
Olivmamman

**Comment by ArdrichFishman** [comment]
Just letting you know, I am having the same problem too. Thanks Dev.

**Comment by LucasJackrabbit** [comment]
I can confirm that I have same problem also. Having Dynamic Prompts enabled by itself does it.

**Comment by Kadah** [comment]
https://github.com/adieyal/sd-dynamic-prompts/commit/638d4b1784b95d19b69c54f93aeee987d2c5b0a2 is to blame.

Revert to 2.15.0 to workaround this.

**Comment by Xeltosh** [comment]
i have also the problem and the errors i got brought me into another extension first. There i found out through another user, that apparantly this: 
https://github.com/adieyal/sd-dynamic-prompts/commit/638d4b1784b95d19b69c54f93aeee987d2c5b0a2  
should be the cause of that multiplying

**Comment by Xeltosh** [comment]
> [638d4b1](https://github.com/adieyal/sd-dynamic-prompts/commit/638d4b1784b95d19b69c54f93aeee987d2c5b0a2) is to blame.
> 
> Revert to 2.15.0 to workaround this.

how to revert?

**Comment by adieyal** [comment]
are you using negative prompts? Re reverting, go into the sd-dynamic-prompts directory and type `git checkout 2.15.0` - you can return to the latest version with `git checkout main`

**Comment by Xeltosh** [comment]
i use A1111 local, so how do i have to do this exactly?

**Comment by Xeltosh** [comment]
ok, nevermind XD i downloaded the previous version directly through the commits-section and installed 2.15.0 manually. do you have an idea, when you can fix it?
