### ISSUE TITLE
If this pattern is possible {3$${and|,}$$__values__}

### ISSUE THREAD

**Issue by lilly1987** [adieyal/sd-dynamic-prompts#60]
**Describe the bug**
```
normalcy ex) {3$$__paser__$$__values__}
-> __values__ __paser__ __values__ __paser__ __values__
-> [ a and b , c ],[ b , c and c ],[ a and b and c ], ...

bug ex) {3$${and|,}$$__values__}
-> {3$$and$$a}
-> [ a and a and a] , [ b and b and ]
```
I think it needs to be upgraded
https://github.com/adieyal/sd-dynamic-prompts/blob/813dd39ad4f4ebd6f5788a5933d4aea8558e9ad9/prompts/generators/randomprompt.py#L42

**Version used**
What version of the extension are you using? You can see it next to **Dynamic Prompt v[VERSION]** in the scripts dropdown.

under 0.25.0

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:

Also mention which checkboxes have been set.

**Expected behaviour**

**Additional context**

**Comment by adieyal** [comment]
Trying to understand this. Correct me if I'm wrong

    {3$${and|,}$$red|green|blue}

should produce:

    red {and|,} green {and|,} blue

which will produce one of these:

```
red and green and blue
red and green,blue
red,green and blue
red,green,blue
```

is that correct?

**Comment by lilly1987** [comment]
yes!

**Comment by adieyal** [comment]
I know it's more complicated, but it can be achieved with jinja2 templates:
```
{% with perms = permutations(['red', 'green', 'blue'], 3) %}
    {% for colour in perms %}
        {% for sep in [' and ', ', '] %}
            {% prompt %}My favourite colours are {{ colour|join(sep) }}{% endprompt %}
        {% endfor %}
    {% endfor %}
{% endwith %}
```

Is this example a real use case?

**Comment by lilly1987** [comment]
In this case of jinja2, it's a bit difficult because you have to do coding rather than simple list management.
jinja2 is great for implementing complex grammars.
I'll refer to it at once.

This method is the easiest to manage
```
{3$$__paser__$$__values__}
```
