### ISSUE TITLE
[BUG]: Wildcards broken

### ISSUE THREAD

**Issue by Woisek** [adieyal/sd-dynamic-prompts#607]
It seems the last updates of SD:Next broke the auto completion of the wildcards again.
After entering keywords like __keyword__, I don't get a list of the content in the wildcard as usual but nothing is displayed.

Please fix again, thanks. 🙏

**Comment by akx** [comment]
To the best of my knowledge, this extension doesn't do any autocompletion in the input boxes (or am I mistaken, @adieyal?).

**Comment by adieyal** [comment]
Nope. What I've seen is pretty neat, but we don't touch the prompt box.

**Comment by Woisek** [comment]
Please remember this -> https://github.com/adieyal/sd-dynamic-prompts/issues/261
The only thing is now, there is no error in the log shown.

**Comment by Woisek** [comment]
So the wildcard extension does not show the contents of a wild card when using the double underscore before and after ... ?

**Comment by adieyal** [comment]
Not sure about the wildcard extension (which is different to dynamic prompts), but dynamic prompts doesn't. I think there might be another extension that adds that functionality.

**Comment by Woisek** [comment]
> Hello all I have the same problem Dynamic Prompt does NOT work any longer since 1 or 2 days

Look here -> https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/226#issuecomment-1696100324
