### ISSUE TITLE
[BUG]: Combinatorial batches are generating too many images

### ISSUE THREAD

**Issue by jcbordo** [adieyal/sd-dynamic-prompts#608]
When checking the combinatorial generation option and using batches, the batches are creating too many images, they are multiplying themselves creating NxN number of images.  Where N is the number of batches.

For example, if I have 9 options between a single pair of curly brackets and I select 2 batches, then it should create 18 images, but it is making 36 (9 x 2 x 2).   Same if I use a Wildcards file, if I have 20 lines and I set a batch of 5, it is creating 500 (20 x 5 x 5) instead of 100.

Thank you for making this BTW, awesome extension.

**Comment by adieyal** [comment]
I can't reproduce this issue - could you try the latest release - 2.16.3 in that fixes it. Also, do you have a variant `{...}` or wildcard `__X__` in your negative prompt?

**Comment by jcbordo** [comment]
Oh thanks! The update fixed it.  I thought I already had updated it on the date of the last commit, but I must have updated just before you posted it.

It's doing it correctly now.  Keep up the great work 😄
