### ISSUE TITLE
WARNING:dynamicprompts.samplers.utils:No values found for wildcard

### ISSUE THREAD

**Issue by Neytiri7** [adieyal/sd-dynamic-prompts#609]
The wildcard folder contains the file normally, and the content in the txt file exists normally.

After using it well, the issue is suddenly being identified.

The generated image appears to have been successfully applied with the corresponding wildcard.
If you get that many messages, cmd stops, and you have to restart.

Loading weights [ae73d059c8] from O:\AI\SynologyDrive\stable-diffusion-webui\models\Stable-diffusion\Dream-C3-v1.1.safetensors
Loading VAE weights specified in settings: O:\AI\SynologyDrive\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Weights loaded in 3.9s (send model to cpu: 0.3s, load weights from disk: 0.7s, apply weights to model: 2.4s, load VAE: 0.4s).
WARNING:dynamicprompts.samplers.utils:No values found for wildcard positive
WARNING:dynamicprompts.samplers.utils:No values found for wildcard 001/hair
WARNING:dynamicprompts.samplers.utils:No values found for wildcard 001/face_expression
WARNING:dynamicprompts.samplers.utils:No values found for wildcard 001/breast_size
WARNING:dynamicprompts.samplers.utils:No values found for wildcard 001/shoes
WARNING:dynamicprompts.samplers.utils:No values found for wildcard 001/lighting
WARNING:dynamicprompts.samplers.utils:No values found for wildcard 001/pose

*It was marked like this and suddenly stopped.

**Comment by adieyal** [comment]
is your wildcard folder in `extensions\sd-dynamic-prompts\wildcards`?

That error means that the wildcard manager couldn't find your wildcard folder or the wildcard file doesn't exist

**Comment by TheCyberQuake** [comment]
Replying to mention that I'm also consistently getting this error every time. text files are in the correct folder, and outside of that error in the console it seems to still be working fine and pulling wildcards, so I'm not sure why I'm getting the error when it seems to clearly be able to find values.

**Comment by nathan909b** [comment]
I get this error. It seems like the wildcards are being pulled? I don't know how to tell if it is. What I know is that when I recall the last prompt, it shows words in there that came from the wildcard file, instead of the __value__ itself. So, it _seems_ to be working regardless of the error?

**Comment by Neytiri7** [comment]
I'll close the issue after it's settled.

**Comment by CodeHatchling** [comment]
This is broken again.

My text file is placed here:

sd.webui\webui\extensions\sd-dynamic-prompts\wildcards\locations.txt

Yet in the console it says:

`WARNING:dynamicprompts.samplers.utils:No values found for wildcard location`

**Comment by akx** [comment]
@CodeHatchling If you have `locations.txt` and a wildcard `location`, that's not the same thing...

**Comment by CodeHatchling** [comment]
Yeah, I figured that out. I was thrown off by the generic term "location/s" that I used, and interpreted it as a vague IO error message. If I had a category for "food" or "vehicles" I prolly would have had 0 confusion. My bad, haha
