### ISSUE TITLE
How to use Wildcard JSON / YAML files in comfy UI

### ISSUE THREAD

**Issue by Euchale** [adieyal/sd-dynamic-prompts#615]
I can use txt files just fine, but I do not know the syntax for JSON/YAML and its not listed in the tutorial from what I can see.

**Comment by akx** [comment]
This extension is only for stable-diffusion-webui and does not support Comfy.

If there is an extension/node for Comfy that uses the underlying [dynamicprompts library](https://github.com/adieyal/dynamicprompts), then it could use JSON/YAML wildcard files, but I don't know if there is one.

**Comment by Euchale** [comment]
Interesting, as it works perfectly fine like this: 
![image](https://github.com/adieyal/sd-dynamic-prompts/assets/3716287/60af55f2-c434-4af8-9ee4-febf0a072eb8)
to load from text files. 

How do you load from json in A1111? Maybe its the same syntax? Or do you select it from a list through the wildcard manager?

**Comment by akx** [comment]
> How do you load from json in A1111? Maybe its the same syntax? Or do you select it from a list through the wildcard manager?

Via https://github.com/adieyal/dynamicprompts/pull/56 in the aforementioned `dynamicprompts` library...

**Comment by Euchale** [comment]
The random prompt node appears when you download the dynamic prompt plugin for comfyui, otherwise I would not be asking here :)

Its this one:
![image](https://github.com/adieyal/sd-dynamic-prompts/assets/3716287/a8ee6b5e-87cc-4357-a6b8-00acb81e5075)

And it adds the following nodes:
![image](https://github.com/adieyal/sd-dynamic-prompts/assets/3716287/05cb4292-93e8-4ffc-b12f-4b84bb66ee68)

**Comment by akx** [comment]
@Euchale Please ask in [that project's issues](https://github.com/adieyal/comfyui-dynamicprompts) then.

**Comment by akx** [comment]
Closing since this is related to the sibling project.
