### ISSUE TITLE
List could not be seen if adding 'on' as an item in YAML file

### ISSUE THREAD

**Issue by eric23** [adieyal/sd-dynamic-prompts#618]
If I added an item named 'on' to the list, the list would not be found in the navigation. Just like:

place-to:
    - on
    - in
    - standing on
    - lying on
    - balancing on
    - buried in
    - emerging from

If 'on' is removed, the list would be found in the navigation.

Is 'on' a reserved keyword of DP?

**Comment by akx** [comment]
No - this is a quirk of YAML, where `on` means `true`.

Quote the word, e.g.

```yaml
- "on"
```
(it'll still actually be the word `on` as far as DP can see).
