### ISSUE TITLE
[Bug]: Some console error

### ISSUE THREAD

**Issue by LLKoder** [adieyal/sd-dynamic-prompts#627]
On start up I see some console error:

```
...\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioUnusedKwargWarning: You have unused kwarg parameters in Button, please remove them: {'full_width': True}
  res = original_IOComponent_init(self, *args, **kwargs)
```

If add-on will turn off error will disappear either.

version: v1.6.0
python: 3.10.11
torch: 2.0.1+cu118
xformers: 0.0.20
gradio: 3.41.2
checkpoint: [171c237b86]

**Comment by akx** [comment]
That is a harmless warning, not an error. Thanks for noting it though :)

**Comment by chuckkay** [comment]
harmless yes but when we have to trial and error to figure out which extention is causing it...  pretty annoying..

FYI not ranting at you, same problem different errors with other extentions too,,, mkaes it dificult to know whne there is something not harmless going on or going wrong. took 20 minutes to fine the culprits
