### ISSUE TITLE
Newest A1111 version can not load "__" to prompt

### ISSUE THREAD

**Issue by bbggkk** [adieyal/sd-dynamic-prompts#639]
version: [v1.6.0]•  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.41.2  

Anyone met the same problem?

**Comment by Losquit** [comment]
Me too! Sad...

**Comment by bbggkk** [comment]
Guys,it works now,I've got tagger updated,then, it backs.
