### ISSUE TITLE
[BUG] Magic Prompt only adding commas

### ISSUE THREAD

**Issue by MysticDaedra** [adieyal/sd-dynamic-prompts#645]
Magic Prompt is only adding commas. It kind of seemed like it was working properly at first, but now I'm just getting multiple commas in a row in the middle of the prompt:

`cyberpunk, scifi, (futuristic:1.26),,,,`

I also have the adjust prompt weights function enabled, as you can see there with futuristic. So that seems to be working, but the adding of random prompts is not for some reason. Running on SD.next, using SDXL and diffusers.

**Comment by akx** [comment]
Which MP model are you using, and what temperature value?

**Comment by MysticDaedra** [comment]
I'm not sure what you mean by temperature value... Do you mean prompt creativity? That's on default, 0.7. Here, I'll screenshot my settings:

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/17184148/2d64a37c-5790-4455-a7ad-f5a892d3f348)

For models, I've tried both the default one and the FredZhang7/anime-anything-promptgen-v2 model. Both had the exact same issue.

**Comment by MysticDaedra** [comment]
Here's an example prompt from a generated image:

![image](https://github.com/adieyal/sd-dynamic-prompts/assets/17184148/76192cbf-cf1e-4df6-b3f7-55a5d118f16b)

As you can see, I've highlighted the... offending... bits where there are a bunch of commas added but no text.

**Comment by akx** [comment]
Yeah, creativity = temperature. I have the feeling this is an issue with how the model you're using is trained, not with the extension. We could, though, add post-filtering to deduplicate punctuation!
