### ISSUE TITLE
Don'y know how to use .json wildcard

### ISSUE THREAD

**Issue by Autantpourmoi** [adieyal/sd-dynamic-prompts#650]
hi, and thanks for this great extension . i'm able to use .txt wildcard quite easely , but i did download some .json wildcard , put them in the wildcard dir inside the extension but nothing happen , can't find them in wilcards manager
any help will be greatly appreciated 
thanks

**Comment by akx** [comment]
What files did you download in particular?

**Comment by ema7569** [comment]
yaml worked for me after I created a file .yaml in wildcards folder, the thing is very exigent with syntax. This is an example what the file must contain. You need to respect the spaces, tab are not authorized. Read the yaml specs.

xBasicColor:
  [
    "black", "brown", "pink", "red", "yellow", 
    "purple", "magenta", "cyan","gray","blue","orange","green"
  ]
xTwoTone:
  [
    "two tones, black and red",
    "two tones, black and yellow",
    "two tones, black and pink",
    "two tones, Black and White",
    "two tones, Black and Blue",
 ]
