### ISSUE TITLE
Dynamic Prompts is not installed correctly. You have dynamicprompts version 0.29.0 installed, but this extension requires version ~=0.30.1. Please run `install.py` from the sd-dynamic-prompts extension directory, or `pip install dynamicprompts[attentiongrabber,magicprompt]~=0.30.1`.

### ISSUE THREAD

**Issue by diqiuonline** [adieyal/sd-dynamic-prompts#664]
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
D:\Program Files\SD\sd-webui-aki-v4.3\python\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension D:\Program Files\SD\sd-webui-aki-v4.3\extensions\sd-dynamic-prompts.
*** Command: "D:\Program Files\SD\sd-webui-aki-v4.3\python\python.exe" "D:\Program Files\SD\sd-webui-aki-v4.3\extensions\sd-dynamic-prompts\install.py"
*** Error code: 1
*** stdout: sd-dynamic-prompts installer: running 'D:\Program Files\SD\sd-webui-aki-v4.3\python\python.exe' -m pip install 'dynamicprompts[attentiongrabber,magicprompt]~=0.30.1'
*** Looking in indexes: https://mirror.baidu.com/pypi/simple
*** Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
*** 
*** stderr: ERROR: Could not find a version that satisfies the requirement dynamicprompts[attentiongrabber,magicprompt]~=0.30.1 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.20.0, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.26.1, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0)
*** ERROR: No matching distribution found for dynamicprompts[attentiongrabber,magicprompt]~=0.30.1
*** Traceback (most recent call last):
***   File "D:\Program Files\SD\sd-webui-aki-v4.3\extensions\sd-dynamic-prompts\install.py", line 14, in <module>
***     install_requirements(force=("-f" in sys.argv))
***   File "D:\Program Files\SD\sd-webui-aki-v4.3\extensions\sd-dynamic-prompts\sd_dynamic_prompts\version_tools.py", line 144, in install_requirements
***     subprocess.check_call(command)
***   File "D:\Program Files\SD\sd-webui-aki-v4.3\python\lib\subprocess.py", line 369, in check_call
***     raise CalledProcessError(retcode, cmd)
*** subprocess.CalledProcessError: Command '['D:\\Program Files\\SD\\sd-webui-aki-v4.3\\python\\python.exe', '-m', 'pip', 'install', 'dynamicprompts[attentiongrabber,magicprompt]~=0.30.1']' returned non-zero exit status 1.
Launching Web UI with arguments: --theme dark --xformers --api --autolaunch
Civitai Helper: Get Custom Model Folder

**Comment by akx** [comment]
The PyPI mirrors you use don't yet have the new version of `dynamicprompts`. We can't help with that.
