### ISSUE TITLE
Description texts unavailable for translation

### ISSUE THREAD

**Issue by Harvester62** [adieyal/sd-dynamic-prompts#68]
**Describe the bug**
There are a few description texts that are not available when I download the localization.json template.

**Version used**
What version of the extension are you using? You can see it next to **Dynamic Prompt v[VERSION]** in the scripts drop down.
This information is no longer available because the script is now an Extension. Anyway, from the Git log the currently installed version is 0.29.0.

**To Reproduce**
The following descriptions texts are unavailable in the localization.json template when downloaded, therefore I am unable to translate them. I tried to add them manually in the Italian localization file but they don't seem to be taken in consideration, possibly this has to be resolved directly inside the python script.

**Expected behavior**
All the labels and description texts should be exported in the localization.json template file.

**Additional context**
Here follow all the above mentioned description texts that I cannot get inside the localization.json template file, but that I've translated anyway in Italian language inside the Italian localization file (my working file, not the one currently committed):

"Generate all possible prompts up to a maximum of Batch count * Batch size)": "Genera tutti i possibili prompt fino a un massimo di (Numero Lotti * Dimensione Lotti)",
"Automatically update your prompt with interesting modifiers. (Runs slowly the first time)": "Aggiorna automaticamente il tuo prompt con modificatori interessanti. (Funziona lentamente la prima volta)",
"Add emphasis to a randomly selected keyword in the prompt.": "Aggiungi enfasi a una parola chiave selezionata a caso nel prompt.",
"Write all generated prompts to a file": "Scrive tutti i prompt generati in un file",
"Disable image generation. Useful if you only want to generate text prompts.": "Disabilita la generazione di immagini. Utile se vuoi solo generare il testo dei prompt.",
"If this is set, then random prompts are generated, even if the seed is the same.": "Se è impostato, vengono generati prompt casuali, anche se il seme è lo stesso",
"Useful for I'm feeling lucky and Magic Prompt. If this is set, then negative prompts are not generated.": "Useful for I'm feeling lucky and Magic Prompt. If this is set, then negative prompts are not generated.",
"Use the same seed for all prompts in this batch": "Usa lo stesso seme per tutti i prompt in questo lotto",

**Comment by adieyal** [comment]
I just pushed a changed - could you please test and let me know if it works for you?

**Comment by Harvester62** [comment]
Sure, I have just synced the repo and I will now check it, and let you know.

**Comment by Harvester62** [comment]
I would say that all those descriptions are now being exported inside the localization.json template file. I will have to check carefully but it seems that you fixed it and did a great job! Thank you very much. If I would find any further issue I will let you know. 
Now the only thing that would need to be fixed is to let Magic Prompt work, which I will have to check. Did you further investigated that issue? But this should be discussed in the other bug report, sorry.

**Comment by adieyal** [comment]
I'm glad it's working.

**Comment by Harvester62** [comment]
Now I will switch to Italian and test that everything is working fine before committing this revision of the it_IT.json.

It is very nice that you've been able to fix this and I hope that your solution might be reused by other developers of Scripts and Extensions, if the solution can be ported to other scripts.

**Comment by adieyal** [comment]
I think it was specific to the way I was creating those labels. I had to move them out of the style.css file and into the javascript file

**Comment by Harvester62** [comment]
Everything is working fine, just to let you know.
