### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ema7569** [adieyal/sd-dynamic-prompts#683]
If I add a syntax like this {0.25::from back} to have just 25% of possibilities for this tag, the returned image is always from back.
 I also tested with {0.0::from back}  and the returned prompt continue to contain the tag despite it has 0.0% chance

**Comment by akx** [comment]
You shouldn't use the curly braces if you want weighted wildcards. That syntax is for variants.

(Sorry for the brief reply, on mobile.)

**Comment by ema7569** [comment]
I solved my two questions, thank for your time
