### ISSUE TITLE
Dynamic prompts not working in A1111 with SDXL

### ISSUE THREAD

**Issue by mprz1024** [adieyal/sd-dynamic-prompts#685]
Is there a reason why, when loading a SDXL checkpoint, Dynamic Prompts which was otherwise working fine in Automatic1111 would stop expanding anything and just send the wildcards to the model?

**Comment by akx** [comment]
No – that doesn't happen for me, it works just fine with SDXL models too.

**Comment by mprz1024** [comment]
You are right; I found what was the problem: I had renamed a LoRA something like SomethingSomething__0.3~0.6.safetensors to remember which weight to use. When I added it, it got added like <lora:SomethingSomething__0.3~0.6.safetensors> and the unclosed double underscore broke dynamyc prompts, even if it was within <...>. I just happened to use this LoRA at the same time as I had switched to SDXL. I renamed my LoRAs using -- and it solved the problem.
