### ISSUE TITLE
camera_models.txt doesn't have proper directory matching structure

### ISSUE THREAD

**Issue by Jonseed** [adieyal/sd-dynamic-prompts#69]
**Describe the bug**
The lines in camera_models.txt don't match the directory matching structure. For example:

```
__camera_models_acer__
__camera_models_agfaphoto__
__camera_models_benq__
__camera_models_canon__
__camera_models_casio__
__camera_models_concord__
```

Shouldn't these be:

```
__camera_models/acer__
__camera_models/agfaphoto__
__camera_models/benq__
__camera_models/canon__
__camera_models/casio__
__camera_models/concord__
```

**Version used**
c7434e7

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. When you use __camera_models__ it doesn't work correctly, and shows errors in the terminal that the models can't be found.

Also mention which checkboxes have been set.

**Expected behaviour**
Using the forward slash after camera_models in the txt file allows the script to find the models in the subdirectory.

**Additional context**
Unless I'm not using it right...

**Comment by adieyal** [comment]
Thanks for that - just uploaded a fix

**Comment by Jonseed** [comment]
Same thing with photographers.txt. Doesn't it need to have by_country/ before each country name?
