### ISSUE TITLE
need update all_negative_prompts

### ISSUE THREAD

**Issue by lilly1987** [adieyal/sd-dynamic-prompts#70]
**Describe the bug**

has all_negative_prompts
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/47a44c7e421b98ca07e92dbf88769b04c9e28f86/modules/processing.py#L127

![2022-11-20 21 35 51](https://user-images.githubusercontent.com/20321215/202902225-96fe7a00-06e5-4d92-9ba6-6d1631a5f426.png)

**Version used**
What version of the extension are you using? You can see it next to **Dynamic Prompt v[VERSION]** in the scripts dropdown.

0.29.1

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:

Also mention which checkboxes have been set.

**Expected behaviour**

**Additional context**

**Comment by adieyal** [comment]
That's great news - thanks for keeping a look out. I'll implement it soon.
