### ISSUE TITLE
Wildcard Manager (auto)search takes ages for short search terms with large amount of wildcards

### ISSUE THREAD

**Issue by pessimal** [adieyal/sd-dynamic-prompts#736]
Let me explain my situation, I have generated wildcard prompt files for every lora with permutations of the possible trigger words (See attachment example). Also I have extracted the prompts from images I deem "good" into their own prompt_*imagename*.txt and negprompt_*imagename*.txt files.

Of course this leads to an ungodly amount of files to search through for the Wildcard Manager. For the autosearch this means if I enter just one character it takes ages to display the results as there are so many hits for just one character. 
As a workaround I can enter the actual full term I look for somewhere else and paste that into the search field, that makes the search almost instant. 
My proposal would be to not autosearch but introduce a button that initiates the search on demand instead. Maybe once the wildcard amount reaches a certain size.
[prompt_lora_Made_of_pieces_broken_glass_v2-000005.txt](https://github.com/adieyal/sd-dynamic-prompts/files/14506073/prompt_lora_Made_of_pieces_broken_glass_v2-000005.txt)

**Comment by akx** [comment]
How many wildcard files do you actually have, so we can figure out what the "certain size" is? Another option is to debounce the search, so it happens after e.g. 0.2 seconds after you enter the last character.

**Comment by pessimal** [comment]
> How many wildcard files do you actually have, so we can figure out what the "certain size" is? Another option is to debounce the search, so it happens after e.g. 0.2 seconds after you enter the last character.

Hi, here is the actual number:

> picard@WOTANBUNTU:/srv/linuxdata/stable-diffusion-webui_dev/extensions/sd-dynamic-prompts/wildcards$ find . -type f -iname "*.txt"|wc -l

23514

From my side I think I would be happy with the debounce idea
