### ISSUE TITLE
Dynamic Installation Error - Version: 0.29.0 --- Requires: 0.30.4

### ISSUE THREAD

**Issue by Hearcharted** [adieyal/sd-dynamic-prompts#744]
Hi, how can I fix this error?

Dynamic Prompts is not installed correctly. You have dynamicprompts version 0.29.0 installed, but this extension requires version ~=0.30.4. Please run `install.py` from the sd-dynamic-prompts extension directory, or `pip install dynamicprompts[attentiongrabber,magicprompt]~=0.30.4`.

As far as I know I need to extract the files of this package **''dynamicprompts-0.30.4-py3-none-any.whl''** somewhere in Google Drive...

Horsepower: **Google Colab**
Notebook: **The Last Ben**

**Many thanks in advance...**

**Comment by akx** [comment]
You shouldn't be extracting wheels by hand. You should either `pip install dynamicprompts-0.30.4-py3-none-any.whl`, or run the `pip install` command the warning message is telling you to.

**Comment by akx** [comment]
Glad you got it sorted out.
