### ISSUE TITLE
Dynamic Prompts not showing in Forge UI - ModuleNotFoundError: No module named 'dynamicprompts'

### ISSUE THREAD

**Issue by wideload1971** [adieyal/sd-dynamic-prompts#766]
First time posting here and I'm not sure if this is a Dynamic Prompts issue, a Forge issue or something else but hopefully someone here can sort this out. This is for Windows.
I had an updated version of both Forge and DP working well until I tried to use the Stable Cable extension and it all went ka-ka. Decided to do a fresh install (acked up everything) and after a couple of issues got it working except for Dynamic Prompts. It shows up in the extensions tab, it's ticked and the info is there but it isn't showing in the main UI.
Here's the full cmd window list:

-----------------------------------------------------------------------------------------------------
venv "C:\Users\aoxg2\Forge UI\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Launching Web UI with arguments: --skip-install --ckpt-dir I:\Automatic1111\models\Stable-diffusion --lora-dir I:\Automatic1111\models\Lora --embeddings-dir I:\Automatic1111\Embeddings
Total VRAM 12287 MB, total RAM 32689 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: C:\Users\aoxg2\Forge UI\stable-diffusion-webui-forge\models\ControlNetPreprocessor
CHv1.8.1: Get Custom Model Folder
[-] ADetailer initialized. version: 24.4.2, num models: 18
*** Error loading script: dynamic_prompting.py
    Traceback (most recent call last):
      File "C:\Users\aoxg2\Forge UI\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\aoxg2\Forge UI\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\aoxg2\Forge UI\stable-diffusion-webui-forge\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 3, in <module>
        from sd_dynamic_prompts.dynamic_prompting import Script
      File "C:\Users\aoxg2\Forge UI\stable-diffusion-webui-forge\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 8, in <module>
        import dynamicprompts
    ModuleNotFoundError: No module named 'dynamicprompts'

---
09:42:57 - ReActor - STATUS - Running v0.7.0-b7 on Device: CUDA
Loading weights [15012c538f] from C:\Users\aoxg2\Forge UI\stable-diffusion-webui-forge\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
No Image data blocks found.
No Image data blocks found.
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  11238.880859375
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  9760.673236846924
Moving model(s) has taken 0.21 seconds
Model loaded in 3.9s (load weights from disk: 0.3s, forge load real models: 1.3s, load textual inversion embeddings: 1.7s, calculate empty prompt: 0.5s).
2024-04-19 09:43:03,118 - ControlNet - INFO - ControlNet UI callback registered.
CHv1.8.1: Set Proxy:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 32.5s (prepare environment: 4.1s, import torch: 7.5s, import gradio: 1.4s, setup paths: 1.5s, initialize shared: 0.3s, other imports: 1.1s, list SD models: 0.6s, load scripts: 7.4s, create ui: 7.7s, gradio launch: 0.8s).
-----------------------------------------------------------------------------------------------------

As you can see it says - ModuleNotFoundError: No module named 'dynamicprompts'
I've tried installing it through the UI, copying my previous extension across, installing it directly through git clone but nothing seems to solve this error. All the other extensions are working fine as far as I can tell. Anyone got any ideas?
Please keep any answers easy to understand with all the steps please as I'm not hugely familiar with all this.
Cheers.

**Comment by wideload1971** [comment]
I may have solved this after a reinstall and by installing the extensions in a different order. I'll confirm once I've checked everything else out.

**Comment by wideload1971** [comment]
Ended up reverting Forge back to an earlier version, then updated with git pull from there.

**Comment by HelloWarcraft** [comment]
same here. My stable-diffusion-webui-forge is the lastest version, to load flux model. 
But Dynamic prompts do not support the lastest version of Forge: When I install this extension, `Dynamic Prompts` Button dos not appear in webUI.

**Comment by HelloWarcraft** [comment]
see: https://github.com/adieyal/sd-dynamic-prompts/discussions/820#discussion-7157216

I hope the author would get started to work as soon as possible🙁
