### ISSUE TITLE
feature request: Extra path to scan for wildcard files

### ISSUE THREAD

**Issue by robertJene** [adieyal/sd-dynamic-prompts#813]
Either that or just have it use another path instead of the default.

I use a few installations of Automatic1111 and Forge and I have sd-dynamic-prompts installed on all of them, I want to be able to manage my wildcard files in one folder only

**Comment by akx** [comment]
See https://github.com/adieyal/sd-dynamic-prompts/issues/454 for alternate solutions, namely symlinking.
