### ISSUE TITLE
Doesn't work when the LoRA has "__" on it's name

### ISSUE THREAD

**Issue by Victorcorcos** [adieyal/sd-dynamic-prompts#818]
I discovered that the Dynamic Prompts fails — it doesn't replace dynamically the prompt values — when we add a `LoRA` that include includes `__` on it's name in the wildcards file. See below an example:

## Example

* Prompt
```rb
score_9, score_8_up, score_7_up, sunny day, colorful, __places__, masterpiece
```

* `places.txt`
```rb
<lora:Example_Lora__I_exist:1> castle, brown, rocks, garden
```

## The issue 🐞 

![LoRA](https://github.com/user-attachments/assets/3b72fbec-74d4-4d03-b983-8a3cad32cd23)

<img width="1087" alt="Screenshot 2024-09-02 at 11 45 08" src="https://github.com/user-attachments/assets/88efedcc-386a-484f-bd31-98cfdb2ce95a">

Looks like this make a mess with the dynamic prompting because the `__` keyword is used for importing the file (`__my_file__`).

This could be resolved by just renaming the `LoRA` and removing the `__` on it's name. Still I'm reporting it as a bug because probably it could be resolved by the developer side by an improved regex matching/replacing.

I'm using [Stable Diffusion WebUI Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge)

**Comment by akx** [comment]
See https://github.com/adieyal/sd-dynamic-prompts/issues/755#issuecomment-2042935590.

**Comment by Victorcorcos** [comment]
I see, thanks @akx... it also could be resolved as a whole by the developer side using an improved regex matching/replacing when there are `__` (or the chosen wildcard start/end keywords) when they are being used inside LoRAs.

**Comment by akx** [comment]
@Victorcorcos Yes, please see https://github.com/adieyal/sd-dynamic-prompts/issues/778. PRs welcome to replace the parser 😉
