### ISSUE TITLE
[small request] Sorting alphabetically the wildcards list

### ISSUE THREAD

**Issue by Extraltodeus** [adieyal/sd-dynamic-prompts#85]
I'm talking about this one :

![image](https://user-images.githubusercontent.com/15731540/204650645-ac3530eb-76e0-4809-a08b-a2a18e0ddad1.png)

The orded is random every time. Could it simply be sorted?

**Comment by adieyal** [comment]
Let me know if that works for you

**Comment by Extraltodeus** [comment]
I just pulled it on a fresh colab session and it is still in random order.

**Comment by Extraltodeus** [comment]
Today it works! Thank you.
