### ISSUE TITLE
duplicated results from wildcards

### ISSUE THREAD

**Issue by Velour-Fog** [adieyal/sd-dynamic-prompts#88]
**Describe the bug**
I have an __enhance__ wildcard with 41 lines in it and no duplicates. When I use {10-20$$__enhance__} in my prompts there are often duplicates. the one I just did had "depth of field" twice.

is this the expected behavior? the documentation seems to imply it would only duplicate if there weren't enough terms avaiable.

**To Reproduce**
1) create a wildcard test.txt with 0 on one line, 1 on the next, 2 on the next, up to 9
2) do {5$$__test__} in a prompt a few times
3) notice occasional duplicates

**Expected behaviour**
Not duplicating prompts from wildcards that have enough terms.

**Comment by adieyal** [comment]
Thanks for the report - turns out that it isn't a trivial fix. I'm looking into it now.

**Comment by adieyal** [comment]
Could please test 0.29.14 and let me know if it works for you?
