### ISSUE TITLE
Magic prompt generation produces different results for first run, then consistently produces results for repeated runs

### ISSUE THREAD

**Issue by unnamedplugins** [adieyal/sd-dynamic-prompts#90]
**Describe the bug**
When running a seed with a magic prompt, the first gen will produce a different image than subsequent gens.  This is visible in x/y grids and manual runs.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Enter a prompt of your choice
2. Set a static seed
3. Enable magic prompt with any settings
4. Generate an image
5. Generate a second image
6. Generate a third image
7. The first image will be very different from the other two images.

**Alternative way to reproduce**
1. Set the same settings for dynamic prompts as above
2. Use the x/y plot script
3. Set the X axis to "Seed", enter in the same seed at least three times (below I used `1,1,1`)
4. The first image will be very different from subsequent gens, and use a different magic prompt
![image](https://user-images.githubusercontent.com/79282950/205362038-98a00c71-1027-4ed8-ae75-74e8bdea67f5.png)

Also mention which checkboxes have been set.
![image](https://user-images.githubusercontent.com/79282950/205360802-95f54852-2a25-458f-881c-4893976f73a6.png)

**Expected behaviour**
The first gen should use the same magic prompt text as the subsequent images.

**Additional context**
This appears to be something to do with the GPT2 pipeline, but I am unable to identify any workarounds.  
I tried:
1. Initializing the pipeline every call to the script
2. Pre-running the pipeline with the incoming prompt and throwing the results away (off-by-one)

I first found the issue when doing x/y plots, but determined it could be repeated by manually changing a seed and re-running the same image generation repeatedly.  It is able to be reproduced with any batch size and count.  

**The trigger seems to be closely related to changing the seed.**

**Comment by adieyal** [comment]
Could you please test 0.29.15 and let me know if it's fixed? I couldn't track down the issue so I'm forcefully setting the random seed in the magic prompt initialiser

**Comment by unnamedplugins** [comment]
That appears to have fixed it as far as I can tell.  Thanks!
