### ISSUE TITLE
Feature request: Jinja2 variable or global way to act based on current model

### ISSUE THREAD

**Issue by pbakaus** [adieyal/sd-dynamic-prompts#94]
Very commonly, the tags you would use for e.g. a Danbooru model vs vanilla 1.5 model are completely different. One option is to simply create different wildcard files for each, but it makes organization somewhat difficult. It would be pretty handy to be able to switch dynamically based on which model is currently active.

For Jinja2, I imagine it could look something like this:
```
{% if model == "waifu.cpt"}
    1girl
    2girls
    ...
    {% else %}
    one woman
    two women
{% endif %}
```

Even better would be a general syntax that makes it easy to simply prefix a line in a wildcard file so it gets ignored if not matching a certain model, like maybe so, imagine this was a file called `styles.txt`:
```
{@sd-v1-4,v1-5-pruned-emaonly@} half body portrait
{@arcane*, comic*@} high detail illustration
# alternate hash based lookup
{@318a302e@} high detail illustration
```

Obviously all pseudo syntax quickly hacked together, but regardless of how, being able to match models would be amazing!

**Comment by adieyal** [comment]
Have a  look here: https://github.com/adieyal/sd-dynamic-prompts/blob/main/jinja2.md#environment-variables

**Comment by pbakaus** [comment]
aaaah perfect. Thank you, will give this a try! Feel free to close this issue.
