### ISSUE TITLE
Bug with wildcard file + combination

### ISSUE THREAD

**Issue by pbakaus** [adieyal/sd-dynamic-prompts#95]
**Describe the bug**
This here used to work:
```
{__wildcard1__|__attr1__ __wildcard2__}
```

but now, only one wildcard include can be in that `{}` bracket for one segment at a time. It's the `__attr1__ __wildcard2__` that breaks it. In the broken state, the process throws an error, and all wildcards are ignored. The following works:

```
__attr1__ {__wildcard1__|__wildcard2__}
```

Pretty sure I never ran into problems with that until recently.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. create three wildcard files with the right names
2. Put `{__wildcard1__|__attr1__ __wildcard2__}` into the prompt
3. Observe command line error

Happens with default configuration for me (no advanced settings used).

**Expected behaviour**
Expectation is that one can use unlimited wildcard inclusions in an "OR" selector.

**Comment by adieyal** [comment]
Are you still getting this error? I can't re-created it, here is my prompt:

`I love {__aesthetics/colours/yellow__|__aesthetics/colours/blue__ __aesthetics/colours/green__ } roses`

**Comment by adieyal** [comment]
I'm closing this issue - please re-open if it happens again
