### ISSUE TITLE
Feature request: Ability to use wildcards in negative prompt field

### ISSUE THREAD

**Issue by pbakaus** [adieyal/sd-dynamic-prompts#96]
Maybe this already works but I couldn't get it to work as expected. I tried to create a folder named `negative` and put a `photo.txt` into it. Then, I simply put the following into the negative prompt:

Negative prompt:
```
__negative/photo__
```

Unfortunately, looking at the metadata the field was simply left untouched by the extension. Not sure if this was intended to work and this is technically a bug request, or whether this never worked in the first place, in which case consider this a feature request :)

**Comment by stysmmaker** [comment]
I haven't double checked for myself but this might be related to https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5251 which was merged just a few days ago

**Comment by adieyal** [comment]
I'm not managing to re-produce this. Here is my prompt and output:
![Screenshot from 2022-12-11 06-21-23](https://user-images.githubusercontent.com/420786/206886275-53727778-c99e-4893-a0c8-83effef8bf30.png)

![Screenshot from 2022-12-11 06-21-38](https://user-images.githubusercontent.com/420786/206886272-74704bc1-4645-4ff8-9403-a77951a9d286.png)

**Comment by adieyal** [comment]
I'm closing this issue - please re-open if it happens again
